#' get_participants_summary:
#'
#'
#'
#'
#' @param participants_data (dataframe) particpants_data generated by proc_redcap
#'
get_participants_summary <- function(participants_data) {

  participants_data$baseline_visit_count <- rowSums(!is.na(participants_data[c("child_protocol_1_date", "child_protocol_2_date", "child_protocol_3_date", "child_protocol_4_date")]))

  xtabs(participants_data$risk_status_maternal.y ~ participants_data$baseline_visit_count)

  participants_data %>%
    dplyr::count(risk_status_maternal.y, baseline_visit_count) %>%
    dplyr::group_by(risk_status_maternal.y)


  #hist(participants_data[participants_data$risk_status_maternal.y == "high-risk",]$baseline_visit_count, labels = TRUE, breaks=seq(.5, 4.5, by=1))

  #hist(participants_data[participants_data$risk_status_maternal.y == "low-risk",]$baseline_visit_count, labels = TRUE, breaks=seq(.5, 4.5, by=1))

  }
