#' json_intake: Generates a json file for intake data
#'
#' This function generates a json file for intake data
#'
#' @return A json file documenting intake data
#'
#'
#' @export

json_intake <- function() {

  intake_list <- list(
    participant_id = list( Description = 'participant id number'),
    visit = list( Description = 'participant id number'),
    session_id = list( Description = ''),

    # visit data
    advertisement_condition = list( Description = ''),
    test_meal_book = list( Description = ''),
    test_meal_start_time = list( Description = ''),
    test_meal_15_min_check = list( Description = ''),
    test_meal_end_time = list( Description = ''),
    test_meal_duration = list( Description = ''),
    test_meal_notes = list( Description = 'Researcher notes about meal protocol'),
    meal_prep_notes = list( Description = 'Researcher notes about meal food preparation'),

    eah_wanting_water = list( Description = 'EAH Wanting Questionnaire example: How much do you want to drink water right now?'),
    eah_wanting_corn_chips = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat corn chips right now?'),
    eah_wanting_pretzels = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat pretzels right now?'),
    eah_wanting_starburst = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Starbursts right now?'),
    eah_wanting_brownies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat brownies right now?'),
    eah_wanting_markers = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these markers right now?'),
    eah_wanting_crayons = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these crayons right now?'),
    eah_wanting_ice_cream = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat ice cream right now?'),
    eah_wanting_color_book_2 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_oonies_2 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this Oonies Inflator right now?'),
    eah_wanting_pencils = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these colored pencils right now?'),
    eah_wanting_activity_book = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this activity book right now?'),
    eah_wanting_oreos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Oreos right now?'),
    eah_wanting_popcorn = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat popcorn right now?'),
    eah_wanting_color_book_1 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_legos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Legos right now?'),
    eah_wanting_squeakee = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Squeakee the Balloon Dog right now?'),
    eah_wanting_hershey_kiss = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Hershey kisses right now?'),
    eah_wanting_dinosaurs = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with dinosaurs right now?'),
    eah_wanting_oonies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Oonies right now?'),
    eah_wanting_skittles = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat skittles right now?'),

    eah_protocol_notes = list( Description = 'Researcher notes about EAH protocol'),
    eah_prep_notes = list( Description = 'Reseacher notes about EAH food preparation'),

    vas_visit = list( Description = 'REACH protocol visit that VAS food liking ratings were collected on',
                      Levels = list ('1' =	'Visit 1',
                                     '5'	= 'Visit 5')),
    vas_popcorn = list( Description = 'How much do you like this popcorn?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    vas_pretzel = list( Description = 'How much do you like this pretzel?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    vas_corn_chip = list( Description = 'How much do you like this corn chip?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    vas_oreo = list( Description = 'How much do you like this cookie?',
                     Levels = list ('0' =	'Hate it',
                                    '1'	= 'Dislike it',
                                    '2'	= 'It\'s okay',
                                    '3'	= 'Like it',
                                    '4'	= 'Love it')),
    vas_brownie = list( Description = 'How much do you like this brownie?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    vas_starburst = list( Description = 'How much do you like this Starburst?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    vas_skittle = list( Description = 'How much do you like this Skittle?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    vas_chocolate = list( Description = 'How much do you like this chocolate (Hershey Kiss)?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    vas_icecream = list( Description = 'How much do you like this ice cream?',
                         Levels = list ('0' =	'Hate it',
                                        '1'	= 'Dislike it',
                                        '2'	= 'It\'s okay',
                                        '3'	= 'Like it',
                                        '4'	= 'Love it')),
    vas_grilled_cheese = list( Description = 'How much do you like this grilled cheese?',
                               Levels = list ('0' =	'Hate it',
                                              '1'	= 'Dislike it',
                                              '2'	= 'It\'s okay',
                                              '3'	= 'Like it',
                                              '4'	= 'Love it')),
    vas_chicken_tender = list( Description = 'How much do you like this chicken tender?',
                               Levels = list ('0' =	'Hate it',
                                              '1'	= 'Dislike it',
                                              '2'	= 'It\'s okay',
                                              '3'	= 'Like it',
                                              '4'	= 'Love it')),
    vas_potato_chips = list( Description = 'How much do you like this potato chip?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    vas_carrot = list( Description = 'How much do you like this baby carrot?',
                       Levels = list ('0' =	'Hate it',
                                      '1'	= 'Dislike it',
                                      '2'	= 'It\'s okay',
                                      '3'	= 'Like it',
                                      '4'	= 'Love it')),
    vas_fruit = list( Description = 'How much do you like this fruit cocktail',
                      Levels = list ('0' =	'Hate it',
                                     '1'	= 'Dislike it',
                                     '2'	= 'It\'s okay',
                                     '3'	= 'Like it',
                                     '4'	= 'Love it')),
    vas_water = list( Description = 'How much do you like this water?',
                      Levels = list ('0' =	'Hate it',
                                     '1'	= 'Dislike it',
                                     '2'	= 'It\'s okay',
                                     '3'	= 'Like it',
                                     '4'	= 'Love it')),

    # double entry data

    bread_pre_w_o_plate = list( Description = 'Pre-meal weight of bread (grilled cheese component) without plate',
                                Unit = "grams"),
    butter_pre_w_o_plate = list( Description = 'Pre-meal weight of butter (grilled cheese component) on bread slice A without plate',
                                 Unit = "grams"),
    butter_2_pre_w_o_plate = list( Description = 'Pre-meal weight of butter (grilled cheese component) on bread slice B without plate',
                                   Unit = "grams"),
    cheese_pre_w_o_plate = list( Description = 'Pre-meal weight of cheese (grilled cheese component) without plate',
                                 Unit = "grams"),

    grilled_cheese_pre_w_o_plate = list( Description = 'Pre-meal weight of grilled cheese without plate',
                                         Unit = "grams"),
    grilled_cheese_pre_w_plate = list( Description = 'Pre-meal weight of grilled cheese with plate',
                                       Unit = "grams"),
    grilled_cheese_post_w_plate = list( Description = 'Post-meal weight of grilled cheese with plate',
                                        Unit = "grams"),

    tender_pre_w_o_plate = list( Description = 'Pre-meal weight of chicken tender without plate',
                                 Unit = "grams"),
    tender_pre_w_plate = list( Description = 'Pre-meal weight of chicken tender with plate',
                               Unit = "grams"),
    tender_post_w_plate = list( Description = 'Post-meal weight of chicken tender with plate',
                                Unit = "grams"),

    carrot_pre_w_o_plate = list( Description = 'Pre-meal weight of carrots without plate',
                                 Unit = "grams"),
    carrot_pre_w_plate = list( Description = 'Pre-meal weight of carrots with plate',
                               Unit = "grams"),
    carrot_post_w_plate = list( Description = 'Post-meal weight of carrots with plate',
                                Unit = "grams"),

    chips_pre_w_o_plate = list( Description = 'Pre-meal weight of potato chips without plate',
                                Unit = "grams"),
    chips_pre_w_plate = list( Description = 'Pre-meal weight of potato chips with plate',
                              Unit = "grams"),
    chips_post_w_plate = list( Description = 'Post-meal weight of potato chips with plate',
                               Unit = "grams"),

    fruit_pre_w_o_plate = list( Description = 'Pre-meal weight of fruit cocktail without plate',
                                Unit = "grams"),
    fruit_pre_w_plate = list( Description = 'Pre-meal weight of fruit cocktail with plate',
                              Unit = "grams"),
    fruit_post_w_plate = list( Description = 'Post-meal weight of fruit cocktail with plate',
                               Unit = "grams"),

    water_pre_w_o_plate = list( Description = 'Pre-meal weight of water without container',
                                Unit = "grams"),
    water_pre_w_plate = list( Description = 'Pre-meal weight of water with container',
                              Unit = "grams"),
    water_post_w_plate = list( Description = 'Post-meal weight of water with container',
                               Unit = "grams"),

    ranch_pre_w_o_plate = list( Description = 'Pre-meal weight of ranch dressing without container',
                                Unit = "grams"),
    ranch_pre_w_plate = list( Description = 'Pre-meal weight of ranch dressing with container',
                              Unit = "grams"),
    ranch_post_w_plate = list( Description = 'Post-meal weight of ranch dressing with container',
                               Unit = "grams"),

    ranch_pre_w_o_plate = list( Description = 'Pre-meal weight of ketchup without container',
                                Unit = "grams"),
    ranch_pre_w_plate = list( Description = 'Pre-meal weight of ketchup with container',
                              Unit = "grams"),
    ranch_post_w_plate = list( Description = 'Post-meal weight of ketchup with container',
                               Unit = "grams"),

    pre_ad_meal_fullness = list( Description = '',
                                 Unit = "mm"),
    pre_meal_fullness = list( Description = '',
                              Unit = "mm"),
    post_meal_fullness = list( Description = '',
                               Unit = "mm"),
    pre_ad_eah_fullness = list( Description = '',
                                Unit = "mm"),
    pre_eah_fullness = list( Description = '',
                             Unit = "mm"),
    post_eah_fullness = list( Description = '',
                              Unit = "mm"),

    brownie_pre_w_o_plate = list( Description = 'Pre-EAH weight of brownies without plate',
                                  Unit = "grams"),
    brownie_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                Unit = "grams"),
    brownie_post_w_plate = list( Description = 'Post-EAH weight of brownies with plate',
                                 Unit = "grams"),

    corn_chip_pre_w_o_plate = list( Description = 'Pre-EAH weight of corn chips without plate',
                                    Unit = "grams"),
    corn_chip_pre_w_plate = list( Description = 'Pre-EAH weight of corn chips with plate',
                                  Unit = "grams"),
    corn_chip_post_w_plate = list( Description = 'Post-EAH weight of corn chips with plate',
                                   Unit = "grams"),

    kiss_pre_w_o_plate = list( Description = 'Pre-EAH weight of Hersheys kiss without plate',
                               Unit = "grams"),
    kiss_pre_w_plate = list( Description = 'Pre-EAH weight of Hersheys kiss with plate',
                             Unit = "grams"),
    kiss_post_w_plate = list( Description = 'Post-EAH weight of Hersheys kiss with plate',
                              Unit = "grams"),

    ice_cream_pre_w_o_plate = list( Description = '',
                                    Unit = "grams"),
    ice_cream_pre_w_plate = list( Description = '',
                                  Unit = "grams"),
    ice_cream_post_w_plate = list( Description = '',
                                   Unit = "grams"),

    oreo_pre_w_o_plate = list( Description = '',
                               Unit = "grams"),
    oreo_pre_w_plate = list( Description = '',
                                   Unit = "grams"),
    oreo_post_w_plate = list( Description = '',
                                    Unit = "grams"),

    popcorn_pre_w_o_plate = list( Description = '',
                                  Unit = "grams"),
    popcorn_pre_w_plate = list( Description = '',
                                      Unit = "grams"),
    popcorn_post_w_plate = list( Description = '',
                                       Unit = "grams"),

    pretzel_pre_w_o_plate = list( Description = '',
                                  Unit = "grams"),
    pretzel_pre_w_plate = list( Description = '',
                                      Unit = "grams"),
    pretzel_post_w_plate = list( Description = '',
                                       Unit = "grams"),

    skittle_pre_w_o_plate = list( Description = '',
                                  Unit = "grams"),
    skittle_pre_w_plate = list( Description = '',
                                      Unit = "grams"),
    skittle_post_w_plate = list( Description = '',
                                       Unit = "grams"),

    starburst_pre_w_o_plate = list( Description = '',
                                    Unit = "grams"),
    starburst_pre_w_plate = list( Description = '',
                                        Unit = "grams"),
    starburst_post_w_plate = list( Description = '',
                                         Unit = "grams"),

    water_eah_pre_w_o_plate = list( Description = '',
                                    Unit = "grams"),
    water_eah_pre_w_plate = list( Description = '',
                                        Unit = "grams"),
    water_eah_post_w_plate = list( Description = '',
                                         Unit = "grams"),

    # derivatives: grilled cheese components

    butter_pre_kcal = list( Description = 'Energy content of butter component for grilled cheese. Computed by multiplying (butter_pre_w_o_plate + butter_2pre_w_o_plate) by butter energy density',
                            Derivative = TRUE,
                            Unit = "kcal"),
    bread_pre_kcal = list( Description = 'Energy content of bread component for grilled cheese. Computed by multiplying bread_pre_w_o_plate by bread energy density',
                          Derivative = TRUE,
                           Unit = "kcal"),
    cheese_pre_kcal = list( Description = 'Energy content of cheese component for grilled cheese. Computed by multiplying cheese_pre_w_o_plate by bread energy density',
                           Derivative = TRUE,
                           Unit = "kcal"),
    grilled_cheese_pre_kcal = list( Description = 'Energy content of grilled cheese. Computed by summing butter_pre_kcal, bread_pre_kcal, cheese_pre_kcal',
                            Derivative = TRUE,
                            Unit = "kcal"),
    grilled_cheese_ed = list( Description = 'Energy density of grilled cheese. Computed by dividing grilled_cheese_pre_kcal by grilled_cheese_pre_w_o_plate',
                              Derivative = TRUE,
                              Unit = "kcal/g"),

    # derivatives: _consumed vars
    grilled_cheese_grams_consumed = list( Description = '',
                              Derivative = TRUE,
                              Unit = "grams"),
    grilled_cheese_kcal_consumed = list( Description = '',
                                         Derivative = TRUE,
                                         Unit = "kcal"),
    tender_grams_consumed = list( Description = '',
                                          Derivative = TRUE,
                                          Unit = "grams"),
    tender_kcal_consumed = list( Description = '',
                                         Derivative = TRUE,
                                         Unit = "kcal"),
    carrot_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    carrot_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    chips_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    chips_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    fruit_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    fruit_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    water_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    water_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ranch_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ranch_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ketchup_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ketchup_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    brownie_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    brownie_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    corn_chip_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    corn_chip_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    kiss_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    kiss_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ice_cream_grams_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ice_cream_kcal_consumed = list( Description = '',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    oreo_grams_consumed = list( Description = '',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    oreo_kcal_consumed = list( Description = '',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    popcorn_grams_consumed = list( Description = '',
                                Derivative = TRUE,
                                Unit = "grams"),
    popcorn_kcal_consumed = list( Description = '',
                               Derivative = TRUE,
                               Unit = "kcal"),
    pretzel_grams_consumed = list( Description = '',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    pretzel_kcal_consumed = list( Description = '',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    skittle_grams_consumed = list( Description = '',
                                   Derivative = TRUE,
                                   Unit = "grams"),
    skittle_kcal_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    starburst_grams_consumed = list( Description = '',
                                   Derivative = TRUE,
                                   Unit = "grams"),
    starburst_kcal_consumed = list( Description = '',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    water_eah_grams_consumed = list( Description = '',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    water_eah_kcal_consumed = list( Description = '',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    meal_grams_consumed = list( Description = '',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    meal_kcal_consumed = list( Description = '',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    eah_grams_consumed = list( Description = '',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    eah_kcal_consumed = list( Description = '',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    total_grams_consumed = list( Description = '',
                               Derivative = TRUE,
                               Unit = "grams"),
    totak_kcal_consumed = list( Description = '',
                              Derivative = TRUE,
                              Unit = "kcal")
  )

  # convert formatting to JSON
  intake_json <- RJSONIO::toJSON(intake_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(intake_json, asText = TRUE))){
    print('Intake visit JSON file may be invalid')
  }

  return(intake_json)

}
