#' json_pwlb: Generates a json file for the Parent Weight Loss Behavior Questionnaire
#'
#' This function generates a json file for the scored Parent Weight Loss Behavior Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_pwlb function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the Parent Weight Loss Behavior Questionnaire
#'
#'
#' @export

json_pwlb <- function() {

  pwlb_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Parent Weight Loss Behavior Questionnaire. Participants were provided the following instructions: "Please read each weight loss strategy listed and indicate how often you have used this strategy IN THE PAST TWO YEARS to lose weight or to maintain weight. If you have never used a strategy, or you have never dieted, please indicate so by marking "Never"."',
      Reference = 'Savage JS, Birch LL. Patterns of weight control strategies predict differences in women’s 4 y weight gain. Obesity (Silver Spring). 2010;18(3):513-520. doi:10.1038/oby.2009.265',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/19696759/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    pwlb_form_date = list( Description = 'Date (YYYY-MM-DD) the PWLB form was completed on Redcap'),
    pwlb1 = list( Description = 'Increase Exercise',
                 Levels = list ('0' =	'Never',
                                '1'	= 'Rarely',
                                '2' =	'Sometimes',
                                '3'	= 'Often',
                                '4'	= 'Always')),
    pwlb2 = list( Description = 'Eat more fruits and vegetables',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb3 = list( Description = 'Eat less fat',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb4 = list( Description = 'Eliminate Snacking',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb5 = list( Description = 'Eliminate sweets and junk',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb6 = list( Description = 'Reduce Calories',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb7 = list( Description = 'Reduce amount of food',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb8 = list( Description = 'Eat low-calorie food',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb9 = list( Description = 'Skip meals',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb10 = list( Description = 'Eat less meat',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb11 = list( Description = 'Fast',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb12 = list( Description = 'Diet Pills',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb13 = list( Description = 'Vomiting',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb14 = list( Description = 'Eat less high-carbohydrate foods',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb15 = list( Description = 'Change type of food eaten',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb16 = list( Description = 'Appetite suppressants',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb17 = list( Description = 'Liquid diets',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb18 = list( Description = 'Drink less alcohol',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb19 = list( Description = 'Increase cigarettes smoked',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb20 = list( Description = 'Laxatives or enemas',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb21 = list( Description = 'Diet centers with food',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb22 = list( Description = 'Weight loss groups',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb23 = list( Description = 'Diuretics',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb24 = list( Description = 'Other*',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb24a = list( Description = 'Describe Other: (free response)'),
    pwlb25 = list( Description = 'Are you currently dieting or exercising to LOSE weight?',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb26 = list( Description = 'Are you currently dieting or exercising to MAINTAIN weight?',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely')),
    pwlb27 = list( Description = 'How successful were you in the past year at losing weight?',
                   Levels = list ('0' =	'I haven\'t tried to lose weight',
                                  '1'	= 'Not at all',
                                  '2' =	'Fairly Successful',
                                  '3'	= 'Very sucessful')),
    pwlb28 = list( Description = 'During the past year, how frequently did you go on a diet?',
                   Levels = list ('0' =	'I haven\'t dieted',
                                  '1'	= 'Once',
                                  '2' =	'2 to 3 times',
                                  '3'	= '4 to 10 times',
                                  '4'	= 'I am on a diet almost all the time')),
    pwlb_healthy = list( Description = 'Healthy Weight Control score: sum of responses to healthy weight control items ("pwlb1", "pwlb2", "pwlb3", "pwlb4", "pwlb5", "pwlb6", "pwlb7", "pwlb8", "pwlb10", "pwlb14"). Raw responses were scaled 1-5 prior to summing.',
                                Derivative = TRUE),
    pwlb_unhealthy = list( Description = 'Unhealthy Weight Control score: sum of responses to healthy weight control items ("pwlb9", "pwlb11", "pwlb12", "pwlb13", "pwlb16", "pwlb17", "pwlb19", "pwlb20", "pwlb23"). Raw responses were scaled 1-5 prior to summing.',
                         Derivative = TRUE),
    pwlb_total = list( Description = 'Total weight control score: sum of responses to all weight control items (pwlb1 - pwlb24)',
                         Derivative = TRUE)
    )


  # convert formatting to JSON
  pwlb_json <- RJSONIO::toJSON(pwlb_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(pwlb_json, asText = TRUE))){
    print('pwlb JSON file may be invalid')
  }

  return(pwlb_json)

}
