#' json_pwlb: Generates a json file for the Parent Weight Loss Behavior Questionnaire
#'
#' This function generates a json file for the scored Parent Weight Loss Behavior Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_pwlb function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the Parent Weight Loss Behavior Questionnaire
#'
#'
#' @export

json_pwlb <- function() {

  pwlb_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Parent Weight Loss Behavior Questionnaire. Participants were provided the following instructions: "Please read each weight loss strategy listed and indicate how often you have used this strategy IN THE PAST TWO YEARS to lose weight or to maintain weight. If you have never used a strategy, or you have never dieted, please indicate so by marking "Never"."',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    pwlb1 = list( Description = 'Increase Exercise',
                 Levels = list ('0' =	'Never',
                                '1'	= 'Rarely',
                                '2' =	'Sometimes',
                                '3'	= 'Often',
                                '4'	= 'Always')),
    pwlb2 = list( Description = 'Eat more fruits and vegetables',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb3 = list( Description = 'Eat less fat',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb4 = list( Description = 'Eliminate Snacking',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb5 = list( Description = 'Eliminate sweets and junk',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb6 = list( Description = 'Reduce Calories',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb7 = list( Description = 'Reduce amount of food',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb8 = list( Description = 'Eat low-calorie food',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb9 = list( Description = 'Skip meals',
                  Levels = list ('0' =	'Never',
                                 '1'	= 'Rarely',
                                 '2' =	'Sometimes',
                                 '3'	= 'Often',
                                 '4'	= 'Always')),
    pwlb10 = list( Description = 'Eat less meat',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb11 = list( Description = 'Fast',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb12 = list( Description = 'Diet Pills',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb13 = list( Description = 'Vomiting',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb14 = list( Description = 'Eat less high-carbohydrate foods',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb15 = list( Description = 'Change type of food eaten',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb16 = list( Description = 'Appetite suppressants',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb17 = list( Description = 'Liquid diets',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb18 = list( Description = 'Drink less alcohol',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb19 = list( Description = 'Increase cigarettes smoked',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb20 = list( Description = 'Laxatives or enemas',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb21 = list( Description = 'Diet centers with food',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb22 = list( Description = 'Weight loss groups',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb23 = list( Description = 'Diuretics',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb24 = list( Description = 'Other*',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb24a = list( Description = 'Describe Other: (free response)'),
    pwlb25 = list( Description = 'Are you currently dieting or exercising to LOSE weight?',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely',
                                  '2' =	'Sometimes',
                                  '3'	= 'Often',
                                  '4'	= 'Always')),
    pwlb26 = list( Description = 'Are you currently dieting or exercising to MAINTAIN weight?',
                   Levels = list ('0' =	'Never',
                                  '1'	= 'Rarely')),
    pwlb27 = list( Description = 'How successful were you in the past year at losing weight?',
                   Levels = list ('0' =	'I haven\'t tried to lose weight',
                                  '1'	= 'Not at all',
                                  '2' =	'Fairly Successful',
                                  '3'	= 'Very sucessful')),
    pwlb28 = list( Description = 'During the past year, how frequently did you go on a diet?',
                   Levels = list ('0' =	'I haven\'t dieted',
                                  '1'	= 'Once',
                                  '2' =	'2 to 3 times',
                                  '3'	= '4 to 10 times',
                                  '4'	= 'I am on a diet almost all the time')),
    pwlb_score = list( Description = '',
                                Derivative = TRUE))


  # convert formatting to JSON
  pwlb_json <- RJSONIO::toJSON(pwlb_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(pwlb_json, asText = TRUE))){
    print('pwlb JSON file may be invalid')
  }

  return(pwlb_json)

}
