#' json_mri_assessment: Generates a json file for MRI visit liking and familiarity assessment
#'
#' This function generates a json file for MRI visit liking and familiarity assessment
#'
#' @return A string with data stored in JSON format containing meta-data
#'
#'
#' @export

json_mri_assessment <- function() {

  mri_assessment_list <- list(
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date (YYYY-MM-DD) of visit this parent report survey was completed'),
    crayola_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Crayola',
                                 Levels = list ('0' = 'No',
                                                '1' = 'Yes')),
    crayola_liking = list( Description = 'How much do you like this product? Crayola crayons - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
    crayola_familiarity = list( Description = 'How familiar are you with this product? Crayola crayons - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
    mcd_sauce_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds Sauce',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
    mcd_sauce_liking = list( Description = 'How much do you like this product? McDonalds Sauce- 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
    mcd_sauce_familiarity = list( Description = 'How familiar are you with this product? McDonalds Sauce - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
    hatchimal_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? HATCHiMALS',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hatchimal_liking = list( Description = 'How much do you like this product? HATCHiMALS - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
    hatchimal_familiarity = list( Description = 'How familiar are you with this product? HATCHiMALS - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
    bk_chicken_nug_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Burger King Chicken Nugget',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
    bk_chicken_nug_liking = list( Description = 'How much do you like this product? Burger King Chicken Nugget - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
    bk_chicken_nug_familiarity = list( Description = 'How familiar are you with this product? Burger King Chicken Nugget - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   lc_pizza_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Little Ceasars Pizza',
                     Levels = list ('0' = 'No',
                                    '1' = 'Yes')),
   lc_pizza_liking = list( Description = 'How much do you like this product? Little Ceasars Pizza - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   lc_pizza_familiarity = list( Description = 'How familiar are you with this product? Little Ceasars Pizza - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   pizza_hut_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Pizza Hut',
                     Levels = list ('0' = 'No',
                                    '1' = 'Yes')),
   pizza_hut_liking = list( Description = 'How much do you like this product? Pizza Hut - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   pizza_hut_familiarity = list( Description = 'How familiar are you with this product? Pizza Hut - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   squeakee_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Squeakee',
                            Levels = list ('0' = 'No',
                                           '1' = 'Yes')),
   squeakee_liking = list( Description = 'How much do you like this product? Squeakee - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   squeakee_familiarity = list( Description = 'How familiar are you with this product? Squeakee - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   creator_cam_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Squeakee',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
   creator_cam_liking = list( Description = 'How much do you like this product? Squeakee - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   creator_cam_familiarity = list( Description = 'How familiar are you with this product? Squeakee - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   smartwatch_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Little Tikes Smart Watch',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
   smartwatch_liking = list( Description = 'How much do you like this product? Little Tikes Smart Watch - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   smartwatch_familiarity = list( Description = 'How familiar are you with this product? Little Tikes Smart Watch - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   monopoly_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Monopoly',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
   monopoly_liking = list( Description = 'How much do you like this product? Monopoly - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   monopoly_familiarity = list( Description = 'How familiar are you with this product? Monopoly - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_mcgriddle_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonald McGriddle',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
   mcd_mcgriddle_liking = list( Description = 'How much do you like this product? McDonald McGriddle - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_mcgriddle_familiarity = list( Description = 'How familiar are you with this product? McDonald McGriddle - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   wendys_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Wendys',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
   wendys_liking = list( Description = 'How much do you like this product? Wendys - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   wendys_familiarity = list( Description = 'How familiar are you with this product? Wendys - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   bk_pancake_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Burger King Pancake',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
   bk_pancake_liking = list( Description = 'How much do you like this product? Burger King Pancake - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   bk_pancake_familiarity = list( Description = 'How familiar are you with this product? Burger King Pancake - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   pixar_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Pixar Interactables',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
   pixar_liking = list( Description = 'How much do you like this product? Pixar Interactables - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   pixar_familiarity = list( Description = 'How familiar are you with this product? Pixar Interactables - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   kfc_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? KFC',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
   kfc_liking = list( Description = 'How much do you like this product? KFC - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   kfc_familiarity = list( Description = 'How familiar are you with this product? KFC - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   little_pet_shop_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Little Pet Shop',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   little_pet_shop_liking = list( Description = 'How much do you like this product? Little Pet Shop - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   little_pet_shop_familiarity = list( Description = 'How familiar are you with this product? Little Pet Shop - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   tb_fry_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Taco Bell Fries',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   tb_fry_liking = list( Description = 'How much do you like this product? Taco Bell Fries - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   tb_fry_familiarity = list( Description = 'How familiar are you with this product? Taco Bell Fries - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   minion_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Mega Blocks Minion',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   minion_liking = list( Description = 'How much do you like this product? Mega Blocks Minion - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   minion_familiarity = list( Description = 'How familiar are you with this product? Mega Blocks Minion - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   chick_fil_a_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Chick-fil-a',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   chick_fil_a_liking = list( Description = 'How much do you like this product? Chick-fil-a - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   chick_fil_a_familiarity = list( Description = 'How familiar are you with this product? Chick-fil-a - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   lego_house_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? LEGO House',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   lego_house_liking = list( Description = 'How much do you like this product? LEGO House - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   lego_house_familiarity = list( Description = 'How familiar are you with this product? LEGO House - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   dominos_1_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Dominos Pizza 1',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   dominos_1_liking = list( Description = 'How much do you like this product? Dominos Pizza 1 - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   dominos_1_familiarity = list( Description = 'How familiar are you with this product? Dominos Pizza 1 - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   lego_unicorn_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? LEGO Unicorn',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   lego_unicorn_liking = list( Description = 'How much do you like this product? LEGO Unicorn - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   lego_unicorn_familiarity = list( Description = 'How familiar are you with this product? LEGO Unicorn - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_burger_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonald Burger',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
   mcd_burger_liking = list( Description = 'How much do you like this product? McDonald Burger - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_burger_familiarity = list( Description = 'How familiar are you with this product? McDonald Burger - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   star_wars_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Star Wars Bladebuilder',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   star_wars_liking = list( Description = 'How much do you like this product? Star Wars Bladebuilder - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   star_wars_familiarity = list( Description = 'How familiar are you with this product? Star Wars Bladebuilder - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   morph_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Morph',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   morph_liking = list( Description = 'How much do you like this product? Morph - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   morph_familiarity = list( Description = 'How familiar are you with this product? Morph - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   robo_fish_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Zuru Robo Fish',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   robo_fish_liking = list( Description = 'How much do you like this product? Zuru Robo Fish - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   robo_fish_familiarity = list( Description = 'How familiar are you with this product? Zuru Robo Fish - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   subway_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Subway',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   subway_liking = list( Description = 'How much do you like this product? Subway - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   subway_familiarity = list( Description = 'How familiar are you with this product? Subway - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_123_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds 123 deal meal',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_123_liking = list( Description = 'How much do you like this product? McDonalds 123 deal meal - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_123_familiarity = list( Description = 'How familiar are you with this product? McDonalds 123 deal meal - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   tb_wrap_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Taco Bell wrap',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   tb_wrap_liking = list( Description = 'How much do you like this product? Taco Bell wrap - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   tb_wrap_familiarity = list( Description = 'How familiar are you with this product? Taco Bell wrap - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   flip_frog_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? IDEAL Flip Frog',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   flip_frog_liking = list( Description = 'How much do you like this product? IDEAL Flip Frog - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   flip_frog_familiarity = list( Description = 'How familiar are you with this product? IDEAL Flip Frog - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   play_doh_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Play-Doh Kitchen',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   play_doh_liking = list( Description = 'How much do you like this product? Play-Doh Kitchen - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   play_doh_familiarity = list( Description = 'How familiar are you with this product? Play-Doh Kitchen - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   fantastic_gym_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? HASBRO Fantastic Gymnastics',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   fantastic_gym_liking = list( Description = 'How much do you like this product? HASBRO Fantastic Gymnastics - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   fantastic_gym_familiarity = list( Description = 'How familiar are you with this product? HASBRO Fantastic Gymnastics - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   bk_bogo_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Burger King BOGO Deal',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   bk_bogo_liking = list( Description = 'How much do you like this product? Burger King BOGO Deal - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   bk_bogo_familiarity = list( Description = 'How familiar are you with this product? Burger King BOGO Deal - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   battle_bot_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? HexBug BattleBots',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   battle_bot_liking = list( Description = 'How much do you like this product? HexBug BattleBots - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   battle_bot_familiarity = list( Description = 'How familiar are you with this product? HexBug BattleBots - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   drone_home_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Playmonster Drone Home',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   drone_home_liking = list( Description = 'How much do you like this product? Playmonster Drone Home - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   drone_home_familiarity = list( Description = 'How familiar are you with this product? Playmonster Drone Home - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   lc_slices_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Little Ceasers Slices',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   lc_slices_liking = list( Description = 'How much do you like this product? Little Ceasers Slices - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   lc_slices_familiarity = list( Description = 'How familiar are you with this product? Little Ceasers Slices - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   minecraft_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? MINECRAFT',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   minecraft_liking = list( Description = 'How much do you like this product? MINECRAFT - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   minecraft_familiarity = list( Description = 'How familiar are you with this product? MINECRAFT - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   harry_potter_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Harry Potter Game',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   harry_potter_liking = list( Description = 'How much do you like this product? Harry Potter Game - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   harry_potter_familiarity = list( Description = 'How familiar are you with this product? Harry Potter Game - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_sandwic_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds Sandwhich',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_sandwic_liking = list( Description = 'How much do you like this product? McDonalds Sandwhich - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_sandwic_familiarity = list( Description = 'How familiar are you with this product? McDonalds Sandwhich - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   huggle_pet_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Huggle Pets',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   huggle_pet_liking = list( Description = 'How much do you like this product? Huggle Pets - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   huggle_pet_familiarity = list( Description = 'How familiar are you with this product? Huggle Pets - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_fry_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds Fries',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_fry_liking = list( Description = 'How much do you like this product? McDonalds Fries - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_fry_familiarity = list( Description = 'How familiar are you with this product? McDonalds Fries - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_big_mac_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds Big Mac',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_big_mac_liking = list( Description = 'How much do you like this product? McDonalds Big Mac - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_big_mac_familiarity = list( Description = 'How familiar are you with this product? McDonalds Big Mac - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   orbeez_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Orbeez',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   orbeez_liking = list( Description = 'How much do you like this product? Orbeez - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   orbeez_familiarity = list( Description = 'How familiar are you with this product? Orbeez - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_burgers_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonald Burgers',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_burgers_liking = list( Description = 'How much do you like this product? McDonald Burgers - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_burgers_familiarity = list( Description = 'How familiar are you with this product? McDonald Burgers - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   tb_nachos_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Taco Bell Nachos',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   tb_nachos_liking = list( Description = 'How much do you like this product? Taco Bell Nachos - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   tb_nachos_familiarity = list( Description = 'How familiar are you with this product? Taco Bell Nachos - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   dominos_2_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Dominos 2',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   dominos_2_liking = list( Description = 'How much do you like this product? Dominos 2 - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   dominos_2_familiarity = list( Description = 'How familiar are you with this product? Dominos 2 - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   tb_chips_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Taco Bell Chips',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   tb_chips_liking = list( Description = 'How much do you like this product? Taco Bell Chips - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   tb_chips_familiarity = list( Description = 'How familiar are you with this product? Taco Bell Chips - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   connect_four_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Connect 4 Shots',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   connect_four_liking = list( Description = 'How much do you like this product? Connect 4 Shots - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   connect_four_familiarity = list( Description = 'How familiar are you with this product? Connect 4 Shots - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   tb_nachos_2_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Taco Bell Nachos 2',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   tb_nachos_2_liking = list( Description = 'How much do you like this product? Taco Bell Nachos 2 - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   tb_nachos_2_familiarity = list( Description = 'How familiar are you with this product? Taco Bell Nachos 2 - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   bacon_king_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Burger King Bacon King',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   bacon_king_liking = list( Description = 'How much do you like this product? Burger King Bacon King - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   bacon_king_familiarity = list( Description = 'How familiar are you with this product? Burger King Bacon King - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   kinetic_sand_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Kinetic Sand',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   kinetic_sand_liking = list( Description = 'How much do you like this product? Kinetic Sand - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   kinetic_sand_familiarity = list( Description = 'How familiar are you with this product? Kinetic Sand - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   doodle_jamz_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Sky Castle Doodle Jamz',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   doodle_jamz_liking = list( Description = 'How much do you like this product? Sky Castle Doodle Jamz - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   doodle_jamz_familiarity = list( Description = 'How familiar are you with this product? Sky Castle Doodle Jamz - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   mcd_combo_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? McDonalds Combo',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   mcd_combo_liking = list( Description = 'How much do you like this product? McDonalds Combo - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   mcd_combo_familiarity = list( Description = 'How familiar are you with this product? McDonalds Combo - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\''),
   unboxing_recall = list( Description = 'Do you remember seeing this commercial in the MRI scanner? Unboxing',
                      Levels = list ('0' = 'No',
                                     '1' = 'Yes')),
   unboxing_liking = list( Description = 'How much do you like this product? Unboxing - 100 point visual analog scale with anchors at 0 - \'Do not like at all\' and 100 - \'Like very much\''),
   unboxing_familiarity = list( Description = 'How familiar are you with this product? Unboxing - 100 point visual analog scale with anchors at 0 - \'Not familiar\' and 100 - \'Very familiar\'')
  )

  # convert formatting to JSON
  mri_assessment_json <- RJSONIO::toJSON(mri_assessment_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(mri_assessment_json, asText = TRUE))){
    print('MRI visit JSON file may be invalid')
  }

  return(mri_visit_json)

}
