#' json_cshq: Generates a json file for the Children\'s Sleep Habits Questionnaire
#'
#' This function generates a json file for the scored Children\'s Sleep Habits Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_cshq function in dataprepr and is only accurate for data collected in Study REACH.
#'
#' @return A string with data stored in JSON format containing meta-data for the Children\'s Sleep Habits Questionnaire
#'
#'
#' @export

json_cshq <- function() {

  cshq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Children\'s Sleep Habits Questionnaire. Participants were provided the following instructions: "The following statements are about your child\'s sleep habits and possible difficulties with sleep. Think about the past week in your child\'s life when answering the questions. If last week was unusual for a specific reason (such as your child had an ear infection and did not sleep well or the TV set was broken) choose the most recent typical week. Answer USUALLY if something occurs 5 or more times in a week. Answer SOMETIMES if it occurs 2-4 times in a week. Answer RARELY if something occurs never or 1 time during a week. Indicate whether or not the sleep habit is a problem by circling "Yes", "No", or "not applicable (N/A)"."',
      Reference = 'Owens, J. A., Spirito, A., & McGuinn, M. (2000). The Children\'s Sleep Habits Questionnaire (CSHQ): Psychometric Properties of A Survey Instrument for School-Aged Children. SLEEP, 23(8), 1043 to 1052',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/11145319/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    cshq_form_date = list( Description = 'Date (YYYY-MM-DD) CSHQ form was completed on redcap'),
    cshq_bed_time = list( Description = 'Child\'s bedtime (Please answer with a 24 hour clock):'),
    cshq_wake_time = list( Description = 'Child\'s usual wake time (Please answer with a 24 hour clock):'),
    cshq_night_sleep_amount_hrs_component = list( Description = 'Child\'s usual amount of sleep each night (no naps): _ hours, _ minutes: Hours component'),
    cshq_night_sleep_amount_min_component = list( Description = 'Child\'s usual amount of sleep each night (no naps): _ hours, _ minutes: Minutes component'),
    cshq_night_sleep_amount_total_mins = list( Description = 'Total amount of time child usually sleeps each night (no naps). If cshq_night_sleep_amount_min_component is n/a, computed using cshq_night_sleep_amount_hrs_component*60. If cshq_nap_amount_min_component provided, computed using (cshq_night_sleep_amount_hrs_component*60 + cshq_night_sleep_amount_min_component)',
                                               Derivative = TRUE,
                                               Units = "minutes"),
    cshq_nap_amount_hrs_component = list( Description = 'Child\'s usual amount of sleep each day (naps): _ hours, _ minutes: Hours component'),
    cshq_nap_amount_min_component = list( Description = 'Child\'s usual amount of sleep each day (naps): _ hours, _ minutes: Minutes component'),
    cshq_nap_amount_total_mins = list( Description = 'Total amount of time child usually naps each day. If cshq_nap_amount_min_component is n/a, computed using cshq_nap_amount_hrs_component*60. If cshq_nap_amount_min_component provided, computed using (cshq_nap_amount_hrs_component*60 + cshq_nap_amount_min_component)',
                                               Derivative = TRUE,
                                               Units = "minutes"),
    cshq_1 = list( Description = 'Child goes to bed at the same time at night',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_2 = list( Description = 'Child falls asleep alone in own bed',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_3 = list( Description = 'Child falls asleep within 20 minutes after going to bed',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_4 = list( Description = 'Child sleeps the right amount',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_5 = list( Description = 'Child sleeps about the same amount each day',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_6 = list( Description = 'Child wakes up by him/herself',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_1_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_2_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_3_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_4_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_5_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_6_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_7 = list( Description = 'Has your child appeared very sleepy or fallen asleep during the following: Watching TV',
                   Levels = list ('1' = 'Not Sleepy',
                                  '2' = 'Very Sleepy',
                                  '3' = 'Falls Asleep')),
    cshq_8 = list( Description = 'Has your child appeared very sleepy or fallen asleep during the following: Riding in a car',
                   Levels = list ('1' = 'Not Sleepy',
                                  '2' = 'Very Sleepy',
                                  '3' = 'Falls Asleep')),
    cshq_9 = list( Description = 'Child falls asleep in parent\'s or sibling\'s bed',
                   Levels = list ('3' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '1' = 'Rarely (0-1 days/wk)')),
    cshq_10 = list( Description = 'Child struggles at bedtime (cries, refuses to stay in bed, etc.)',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_11 = list( Description = 'Child needs parent in the room to fall asleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_12 = list( Description = 'Child is afraid of sleeping alone',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_13 = list( Description = 'Child sleeps too little',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_14 = list( Description = 'Child is afraid of sleeping in the dark',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_15 = list( Description = 'Child has trouble sleeping away from home (visiting relatives, vacation',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_16 = list( Description = 'Child moves to someone else\'s bed during the night (parent, sibling, etc.)',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_17 = list( Description = 'Child awakens once during the night',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_18 = list( Description = 'Child awakens more than once during the night',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    # cshq_18_notes = list( Description = 'Write the number of minutes a night waking usually lasts:'),
    cshq_night_waking_min = list( Description = 'Write the number of minutes a night waking usually lasts:'),
    cshq_9_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes',
                                       '2' = 'N/A')),
    cshq_10_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_11_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_12_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_13_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_14_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_15_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_16_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_17_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_18_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_19 = list( Description = 'Child talks during sleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_20 = list( Description = 'Child is restless and moves a lot during sleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_21 = list( Description = 'Child sleepwalks during the night',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_22 = list( Description = 'Child wets the bed at night',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_23 = list( Description = 'Child grind teeth during sleep (your dentist may have told you this)',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_24 = list( Description = 'Child awakens alarmed by a frightening dream',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_25 = list( Description = 'Child snores loudly',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_26 = list( Description = 'Child seems to stop breathing during sleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_27 = list( Description = 'Child seems to stop breathing during sleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_28 = list( Description = 'Child snorts and/or gasps during sleep',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_29 = list( Description = 'Child wakes up in a negative mood',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_30 = list( Description = 'Adults or siblings wake up child',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_31 = list( Description = 'Child has difficulty getting out of bed in the morning',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_32 = list( Description = 'Child takes a long time to become alert in the morning',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_33 = list( Description = 'Child seems tired in the morning',
                    Levels = list ('3' = 'Usually (5-7 day/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '1' = 'Rarely (0-1 days/wk)')),
    cshq_19_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_20_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_21_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_22_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_23_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_24_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_25_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_26_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_27_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_28_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_29_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_30_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_31_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_32_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_33_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes',
                                        '2' = 'N/A')),
    cshq_bedtime_resit = list( Description = 'Bedtime Resistance.',
                               Derivative = TRUE),
    cshq_sleep_delay = list( Description = 'Sleep Onset Delay.',
                             Derivative = TRUE),
    cshq_sleepdur = list( Description = 'Sleep Duration.',
                          Derivative = TRUE),
    cshq_anxiety = list( Description = 'Sleep Anxiety.',
                         Derivative = TRUE),
    cshq_nightwake = list( Description = 'Night Wakings.',
                           Derivative = TRUE),
    cshq_parasomnias = list( Description = 'Parasomnias.',
                             Derivative = TRUE),
    cshq_dis_breathing = list( Description = 'Sleep Disordered Breathing.',
                               Derivative = TRUE),
    cshq_daysleepy = list( Description = 'Daytime Sleepiness.',
                           Derivative = TRUE),
    cshq_total = list( Description = 'Total Score.',
                       Derivative = TRUE))

  # convert formatting to JSON
  cshq_json <- RJSONIO::toJSON(cshq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cshq_json, asText = TRUE))){
    print('cshq JSON file may be invalid')
  }

  return(cshq_json)

}
