#' json_ffbs: Generates a json file for the Family Food Behavior Survey
#'
#' This function generates a json file for the scored Family Food Behavior Survey and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_ffbs function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Family Food Behavior Survey
#'
#'
#' @export

json_ffbs <- function() {

  ffbs_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Family Food Behavior Survey. Participants were provided the following instructions: "The Family Food Behavior Survey, or FFBS, is a 20 item questionnaire developed to observe family mealtime practices. Please answer each item with a 5-point Likert-Scale, from 0 (never true) to 4 (always true)"',
      Reference = 'McCurdy, K., & Gorman, K. S. (2010). Measuring family food environments in diverse families with young children. Appetite, 54(3), 615–618. https://doi.org/10.1016/j.appet.2010.03.004',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/20227449/'),
    participant_id = list( Description = 'participant id number'),
    ffbs1 = list( Description = 'I decide how many snacks my child has',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs2 = list( Description = 'My child chooses food items while shopping',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs3 = list( Description = 'My child chooses foods from what is served',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs4 = list( Description = 'My child eats and watches TV at mealtimes',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs5 = list( Description = 'I allow my child to take food between meals',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs6 = list( Description = 'My child has regular snack and mealtime routine',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs7 = list( Description = 'My child chooses which food to have for meals',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs8 = list( Description = 'I decide my child\'s snack time',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs9 = list( Description = 'My child wanders during meals',
                  Levels = list ('0' = '0 = Never True',
                                 '1' = '1',
                                 '2' = '2',
                                 '3' = '3',
                                 '4' = '4 = Always True')),
    ffbs10 = list( Description = 'I eat dinner with my child',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs11 = list( Description = 'I decide what my child eats between meals',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs12 = list( Description = 'When my child eats I am in another room',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs13 = list( Description = 'I allow my child to eat snacks whenever s/he wants',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs14 = list( Description = 'My child shops for food with me',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs15 = list( Description = 'I sit down with my child when s/he eats',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs16 = list( Description = 'My child eats snacks/meals whenever s/he wants',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs17 = list( Description = 'I decide the time when my child eats meals',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs18 = list( Description = 'My child and I watch TV while eating meals',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs19 = list( Description = 'My child and I eat at fast food restaurants',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs20 = list( Description = 'My child and I sit and eat together',
                   Levels = list ('0' = '0 = Never True',
                                  '1' = '1',
                                  '2' = '2',
                                  '3' = '3',
                                  '4' = '4 = Always True')),
    ffbs_control = list( Description = 'Maternal Control.',
                         Derivative = TRUE),
    ffbs_presence = list( Description = 'Maternal Presence.',
                          Derivative = TRUE),
    ffbs_ch_choice = list( Description = 'Child Choice.',
                           Derivative = TRUE),
    ffbs_org = list( Description = 'Organization.',
                     Derivative = TRUE))

  # convert formatting to JSON
  ffbs_json <- RJSONIO::toJSON(ffbs_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(ffbs_json, asText = TRUE))){
    print('ffbs JSON file may be invalid')
  }

  return(ffbs_json)

}
