#' json_brief2: Generates a json file for the Behavioral Rating Inventory of Executive Function-2
#'
#' This function generates a json file for the scored Behavioral Rating Inventory of Executive Function-2 and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_brief2 function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the Behavioral Rating Inventory of Executive Function-2
#'
#'
#' @export

json_brief2 <- function() {

  brief_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Behavioral Rating Inventory of Executive Function-2. Participants were provided the following instructions: "Please answer each question as it pertains to your child with never, sometimes or often"',
      Reference = 'Gioia GA, Isquith PK, Guy SC, Kenworthy L. BRIEF-2: Behavior Rating Inventory of Executive Function: Professional Manual. Psychological Assessment Resources; 2015.',
      TermURL = 'https://www.cognitiveatlas.org/task/id/tsk_4a57abb9498ab/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    v2_age = list( Description = 'child age at visit 2 when the BRIEF-2 was completed. Calculated as the difference between visit 2 date and child\'s date of birth',
                   Derivative = TRUE,
                   Units = 'years'),
    sex = list( Description = 'parent-reported child sex',
                Levels = list ('female' = 'female',
                               'male' = 'male')),
    brief1 = list( Description = 'Q1 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief2 = list( Description = 'Q2 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief3 = list( Description = 'Q3 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief4 = list( Description = 'Q4 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief5 = list( Description = 'Q5 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief6 = list( Description = 'Q6 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief7 = list( Description = 'Q7 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief8 = list( Description = 'Q8 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief9 = list( Description = 'Q9 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief10 = list( Description = 'Q10 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief11 = list( Description = 'Q11 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief12 = list( Description = 'Q12 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief13 = list( Description = 'Q13 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief14 = list( Description = 'Q14 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief15 = list( Description = 'Q15 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief16 = list( Description = 'Q16 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief17 = list( Description = 'Q17 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief18 = list( Description = 'Q18 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief19 = list( Description = 'Q19 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief20 = list( Description = 'Q20 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief21 = list( Description = 'Q21 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief22 = list( Description = 'Q22 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief23 = list( Description = 'Q23 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief24 = list( Description = 'Q24 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief25 = list( Description = 'Q25 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief26 = list( Description = 'Q26 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief27 = list( Description = 'Q27 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief28 = list( Description = 'Q28 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief29 = list( Description = 'Q29 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief30 = list( Description = 'Q30 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief31 = list( Description = 'Q31 (proprietary questions)s',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief32 = list( Description = 'Q32 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief33 = list( Description = 'Q33 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief34 = list( Description = 'Q34 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief35 = list( Description = 'Q35 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief36 = list( Description = 'Q36 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief37 = list( Description = 'Q37 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief38 = list( Description = 'Q38 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief39 = list( Description = 'Q39 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief40 = list( Description = 'Q40 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief41 = list( Description = 'Q41 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief42 = list( Description = 'Q42 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief43 = list( Description = 'Q43 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief44 = list( Description = 'Q44 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief45 = list( Description = 'Q45 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief46 = list( Description = 'Q46 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief47 = list( Description = 'Q47 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief48 = list( Description = 'Q48 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief49 = list( Description = 'Q49 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief50 = list( Description = 'Q50 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief51= list( Description = 'Q51 (proprietary questions)',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief52 = list( Description = 'Q52 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief53 = list( Description = 'Q53 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief54 = list( Description = 'Q54 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief55 = list( Description = 'Q55 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief56 = list( Description = 'Q56 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief57 = list( Description = 'Q57 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief58 = list( Description = 'Q58 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief59 = list( Description = 'Q59 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief60 = list( Description = 'Q60 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief61 = list( Description = 'Q61 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief62 = list( Description = 'Q62 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief63 = list( Description = 'Q63 (proprietary questions)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief2_inhibit = list( Description = 'Inhibition raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_inhibit_t = list( Description = 'Inhibition T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_inhibit_p = list( Description = 'Inhibition Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_selfmon = list( Description = 'Self-Monitoring raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_selfmon_t = list( Description = 'Self-Monitoring T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_selfmon_p = list( Description = 'Self-Monitoring Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_shift = list( Description = 'Shifting raw score (sum of all items in subscale)',
                         Derivative = TRUE),
    brief2_shift_t = list( Description = 'Shifting T-score (age and sex normed)',
                           Derivative = TRUE),
    brief2_shift_p = list( Description = 'Shifting Percentile (age and sex normed)',
                           Derivative = TRUE),
    brief2_emcont = list( Description = 'Emotional Control raw score (sum of all items in subscale)',
                          Derivative = TRUE),
    brief2_emcont_t = list( Description = 'Emotional Control T-score (age and sex normed)',
                            Derivative = TRUE),
    brief2_emcont_p = list( Description = 'Emotional Control Percentile (age and sex normed)',
                            Derivative = TRUE),
    brief2_initiate = list( Description = 'Initiate raw score (sum of all items in subscale)',
                            Derivative = TRUE),
    brief2_initiate_t = list( Description = 'Initiate T-score (age and sex normed)',
                              Derivative = TRUE),
    brief2_initiate_p = list( Description = 'Initiate Percentile (age and sex normed)',
                              Derivative = TRUE),
    brief2_wm = list( Description = 'Working Memory raw score (sum of all items in subscale)',
                      Derivative = TRUE),
    brief2_wm_t = list( Description = 'Working Memory T-score (age and sex normed)',
                        Derivative = TRUE),
    brief2_wm_p = list( Description = 'Working Memory Percentile (age and sex normed)',
                        Derivative = TRUE),
    brief2_planorg = list( Description = 'Planning/Organization raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_planorg_t = list( Description = 'Planning/Organization T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_planorg_p = list( Description = 'Planning/Organization Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_taskmon = list( Description = 'Task Monitoring raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_taskmon_t = list( Description = 'Task Monitoring T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_taskmon_p = list( Description = 'Task Monitoring Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_orgmat = list( Description = 'Organiation of Materials raw score (sum of all items in subscale)',
                          Derivative = TRUE),
    brief2_orgmat_t = list( Description = 'Organiation of Materials T-score (age and sex normed)',
                            Derivative = TRUE),
    brief2_orgmat_p = list( Description = 'Organiation of Materials Percentile (age and sex normed)',
                            Derivative = TRUE),
    brief2_bri = list( Description = 'Behavioral Regulation Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_bri_t = list( Description = 'Behavioral Regulation Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_bri_p = list( Description = 'Behavioral Regulation Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_eri = list( Description = 'Emotional Regulaiton Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_eri_t = list( Description = 'Emotional Regulaiton Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_eri_p = list( Description = 'Emotional Regulaiton Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_cri = list( Description = 'Cognitive Regulation Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_cri_t = list( Description = 'Cognitive Regulation Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_cri_p = list( Description = 'Cognitive Regulation Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_gec = list( Description = 'General Executive Composite raw score (sum of all items in questionnaire)',
                       Derivative = TRUE),
    brief2_gec_t = list( Description = 'General Executive Composite T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_gec_p = list( Description = 'General Executive Composite Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_negativity = list( Description = 'Negativity Check - raw score',
                              Derivative = TRUE),
    brief2_negativity_p = list( Description = 'Negativity Check Percentile',
                                Levels = list ('0' = '<=98',
                                               '1' = '99',
                                               '2' = '>99'),
                                Derivative = TRUE),
    brief2_negativity_cat = list( Description = 'Negativity Check Category',
                                  Levels = list ('0' = 'Acceptable',
                                                 '1' = 'Elevated',
                                                 '2' = 'Highly Elevated'),
                                  Derivative = TRUE),
    brief2_inconsistency = list( Description = 'Inconsistency Check - raw score',
                                 Derivative = TRUE),
    brief2_inconsistency_p = list( Description = 'Inconsistency Check Percentile',
                                   Levels = list ('0' = '<=98',
                                                  '1' = '99',
                                                  '2' = '>99'),
                                   Derivative = TRUE),
    brief2_inconsistency_cat = list( Description = 'Inconsistency Check Category',
                                     Levels = list ('0' = 'Acceptable',
                                                    '1' = 'Questionable',
                                                    '2' = 'Inconsistent'),
                                     Derivative = TRUE),
    brief2_infrequency = list( Description = 'Infrequency - raw score',
                               Derivative = TRUE),
    brief2_infrequency_p = list( Description = 'Infrequency Percentile',
                                 Levels = list ('0' = '99',
                                                '1' = '>99'),
                                 Derivative = TRUE),
    brief2_infrequency_cat = list( Description = 'Infrequency Category',
                                   Levels = list ('0' = 'Acceptable',
                                                  '1' = 'Questionable'),
                                   Derivative = TRUE)
  )


  # convert formatting to JSON
  brief_json <- RJSONIO::toJSON(brief_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(brief_json, asText = TRUE))){
    print('BRIEF JSON file may be invalid')
  }

  return(brief_json)

}
