#' json_sleeplog: Generates a json file for the Sleep Log
#'
#' This function generates a json file for the Sleep Log
#'
#' @return A string with data stored in JSON format containing meta-data for the Sleep Log
#'
#'
#' @export

json_sleeplog <- function() {

  sleeplog_list <- list(
    'MeasurementToolMetadata' = list(
      Description = '',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    date_mon = list( Description = 'Monday date in the morning (YYYY-MM-DD)'),
    date_tu = list( Description = 'Tuesday date in the morning(YYYY-MM-DD)'),
    date_wed = list( Description = 'Wednesday date in the morning(YYYY-MM-DD)'),
    date_th = list( Description = 'Thursday date in the morning(YYYY-MM-DD)'),
    date_fri = list( Description = 'Friday date in the morning(YYYY-MM-DD)'),
    date_sat = list( Description = 'Saturday date in the morning(YYYY-MM-DD)'),
    date_sun = list( Description = 'Sunday date in the morning (YYYY-MM-DD)'),
    bedtime_mon = list( Description = 'What time did you go to bed?: Monday',
                        Unit = "hh:mm:ss"),
    bedtime_tu = list( Description = 'What time did you go to bed?: Tuesday',
                       Unit = "hh:mm:ss"),
    bedtime_wed = list( Description = 'What time did you go to bed?: Wednesday',
                        Unit = "hh:mm:ss"),
    bedtime_th = list( Description = 'What time did you go to bed?: Thursday',
                       Unit = "hh:mm:ss"),
    bedtime_fri = list( Description = 'What time did you go to bed?: Friday',
                        Unit = "hh:mm:ss"),
    bedtime_sat = list( Description = 'What time did you go to bed?: Saturday',
                        Unit = "hh:mm:ss"),
    bedtime_sun = list( Description = 'What time did you go to bed?: Sunday',
                        Unit = "hh:mm:ss"),
    attempt_mon = list( Description = 'What time did you try to go to sleep: Monday',
                        Unit = "hh:mm:ss"),
    attempt_tu = list( Description = 'What time did you try to go to sleep: Tuesday',
                       Unit = "hh:mm:ss"),
    attempt_wed = list( Description = 'What time did you try to go to sleep: Wednesday',
                        Unit = "hh:mm:ss"),
    attempt_th = list( Description = 'What time did you try to go to sleep: Thursday',
                       Unit = "hh:mm:ss"),
    attempt_fri = list( Description = 'What time did you try to go to sleep: Friday',
                        Unit = "hh:mm:ss"),
    attempt_sat = list( Description = 'What time did you try to go to sleep: Saturday',
                        Unit = "hh:mm:ss"),
    attempt_sun = list( Description = 'What time did you try to go to sleep: Sunday',
                        Unit = "hh:mm:ss"),
    asleep_mon = list( Description = 'What time did you fall asleep: Monday',
                       Unit = "hh:mm:ss"),
    asleep_tu = list( Description = 'What time did you fall asleep: Tuesday',
                      Unit = "hh:mm:ss"),
    asleep_wed = list( Description = 'What time did you fall asleep: Wednesday',
                       Unit = "hh:mm:ss"),
    asleep_th = list( Description = 'What time did you fall asleep: Thursday',
                      Unit = "hh:mm:ss"),
    asleep_fri = list( Description = 'What time did you fall asleep: Friday',
                       Unit = "hh:mm:ss"),
    asleep_sat = list( Description = 'What time did you fall asleep: Saturday',
                       Unit = "hh:mm:ss"),
    asleep_sun = list( Description = 'What time did you fall asleep: Sunday',
                       Unit = "hh:mm:ss"),
    times_mon = list( Description = 'How many times did you wake up during the night?: Monday'),
    times_tu = list( Description = 'How many times did you wake up during the night?: Tuesday'),
    times_wed = list( Description = 'How many times did you wake up during the night?: Wednesday'),
    times_th = list( Description = 'How many times did you wake up during the night?: Thursday'),
    times_fri = list( Description = 'How many times did you wake up during the night?: Friday'),
    times_sat = list( Description = 'How many times did you wake up during the night?: Saturday'),
    times_sun = list( Description = 'How many times did you wake up during the night?: Sunday'),
    waso_mon = list( Description = 'In total, how long did those awakenings last?: Monday'),
    waso_tu = list( Description = 'In total, how long did those awakenings last?: Tuesday'),
    waso_wed = list( Description = 'In total, how long did those awakenings last?: Wednesday'),
    waso_th = list( Description = 'In total, how long did those awakenings last?: Thursday'),
    waso_fri = list( Description = 'In total, how long did those awakenings last?: Friday'),
    waso_sat = list( Description = 'In total, how long did those awakenings last?: Saturday'),
    waso_sun = list( Description = 'In total, how long did those awakenings last?: Sunday'),
    awake_mon = list( Description = 'What time did you wake up from sleep?: Monday',
                      Unit = "hh:mm:ss"),
    awake_tu = list( Description = 'What time did you wake up from sleep?: Tuesday',
                     Unit = "hh:mm:ss"),
    awake_wed = list( Description = 'What time did you wake up from sleep?: Wednesday',
                      Unit = "hh:mm:ss"),
    awake_th = list( Description = 'What time did you wake up from sleep?: Thursday',
                     Unit = "hh:mm:ss"),
    awake_fri = list( Description = 'What time did you wake up from sleep?: Friday',
                      Unit = "hh:mm:ss"),
    awake_sat = list( Description = 'What time did you wake up from sleep?: Saturday',
                      Unit = "hh:mm:ss"),
    awake_sun = list( Description = 'What time did you wake up from sleep?: Sunday',
                      Unit = "hh:mm:ss"),
    out_on_mon = list( Description = 'What time did you get out of bed to start your day?: Monday',
                       Unit = "hh:mm:ss"),
    out_on_tu = list( Description = 'What time did you get out of bed to start your day?: Tuesday',
                      Unit = "hh:mm:ss"),
    out_on_wed = list( Description = 'What time did you get out of bed to start your day?: Wednesday',
                       Unit = "hh:mm:ss"),
    out_on_th = list( Description = 'What time did you get out of bed to start your day?: Thursday',
                      Unit = "hh:mm:ss"),
    out_on_fri = list( Description = 'What time did you get out of bed to start your day?: Friday',
                       Unit = "hh:mm:ss"),
    out_on_sat = list( Description = 'What time did you get out of bed to start your day?: Saturday',
                       Unit = "hh:mm:ss"),
    out_on_sun = list( Description = 'What time did you get out of bed to start your day?: Sunday',
                       Unit = "hh:mm:ss"),
    rating_mon = list( Description = 'How well did you sleep?: Monday'),
    rating_tu = list( Description = 'How well did you sleep?: Tuesday'),
    rating_wed = list( Description = 'How well did you sleep?: Wednesday'),
    rating_th = list( Description = 'How well did you sleep?: Thursday'),
    rating_fri = list( Description = 'How well did you sleep?: Friday'),
    rating_sat = list( Description = 'How well did you sleep?: Saturday'),
    rating_sun = list( Description = 'How well did you sleep?: Sunday'),
    comment_mon = list( Description = 'Comments: Monday'),
    comment_tu = list( Description = 'Comments: Tuesday'),
    comment_wed = list( Description = 'Comments: Wednesday'),
    comment_th = list( Description = 'Comments: Thursday'),
    comment_fri = list( Description = 'Comments: Friday'),
    comment_sat = list( Description = 'Comments: Saturday'),
    comment_sun = list( Description = 'Comments: Sunday')
    )

  # convert formatting to JSON
  sleeplog_json <- RJSONIO::toJSON(sleeplog_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(sleeplog_json, asText = TRUE))){
    print('sleeplog JSON file may be invalid')
  }

  return(sleeplog_json)

}
