#' json_stq: Generates a json file for the Child Screen Time Questionnaire
#'
#' This function generates a json file for the scored? Child Screen Time Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_stq function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Child Screen Time Questionnaire
#'
#'
#' @export

json_stq <- function() {

  stq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Child Screen Time Questionnaire. Participants were provided the following instrctions: "Now you are going to answer some questions about screen-time. For each question please tell much time per day you do this activity. Your options are: None, < 30 minutes, 30 minutes, 1 hour, 2 hours, 3 hours, More than 4 hours."',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    stq1 = list( Description = 'On a typical weekday, how many hours do you watch TV shows or movies?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq2 = list( Description = 'On a typical weekday, how many hours do you watch videos (such as Youtube)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq3 = list( Description = 'On a typical weekday, how many hours do you play video games on a computer, console, phone or other device (Xbox, Play Station, iPad)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq4 = list( Description = 'On a typical weekday, how many hours do you play active video games, like Wii-fit, Oculus/Virtual Reality, Just Dance, etc. on a computer, console, phone, or other device (Xbox, Play Station, iPad)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq5 = list( Description = 'One a typical weekday, how many hours do you text on a cell phone, tablet, or computer (e.g. GChat, Whatsapp, etc.)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq6 = list( Description = 'On a typical weekday, how many hours do you visit social networking sites like Facebook, Twitter, Instagram, etc.?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq7 = list( Description = 'On a typical weekday, how many hours do you video chat (Skype, FaceTime, etc.)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq8 = list( Description = 'On a typical weekend, how many hours do you watch TV shows or movies? ',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),
    stq9 = list( Description = 'On a typical weekend, how many hours do you watch videos (such as YouTube)?',
                  Levels = list ('0' = 'None',
                                 '1' = '< 30 minutes',
                                 '2' = '30 minutes',
                                 '3' = '1 hour',
                                 '4' = '2 hours',
                                 '5' = '3 hours',
                                 '6' = '4+ hours')),    stq10 = list( Description = 'On a typical weekend, how many hours do you play video games on a computer, console, phone or other device (Xbox, Play Station, iPad)?',
                   Levels = list ('0' = 'None',
                                  '1' = '< 30 minutes',
                                  '2' = '30 minutes',
                                  '3' = '1 hour',
                                  '4' = '2 hours',
                                  '5' = '3 hours',
                                  '6' = '4+ hours')),
    stq11 = list( Description = 'On a typical weekend, how many hours do you play active video games, like Wii-fit, Oculus/Virtual Reality, Just Dance, etc. on a computer, console, phone, or other device (Xbox, Play Station, iPad)?',
                   Levels = list ('0' = 'None',
                                  '1' = '< 30 minutes',
                                  '2' = '30 minutes',
                                  '3' = '1 hour',
                                  '4' = '2 hours',
                                  '5' = '3 hours',
                                  '6' = '4+ hours')),
    stq12 = list( Description = 'On a typical weekend, how many hours do you text on a cell phone, tablet, or computer (e.g. GChat, Whatsapp, etc.)?',
                   Levels = list ('0' = 'None',
                                  '1' = '< 30 minutes',
                                  '2' = '30 minutes',
                                  '3' = '1 hour',
                                  '4' = '2 hours',
                                  '5' = '3 hours',
                                  '6' = '4+ hours')),
    stq13 = list( Description = 'On a typical weekend, how many hours do you visit social networking sites like Facebook, Twitter, Instagram, etc.?',
                   Levels = list ('0' = 'None',
                                  '1' = '< 30 minutes',
                                  '2' = '30 minutes',
                                  '3' = '1 hour',
                                  '4' = '2 hours',
                                  '5' = '3 hours',
                                  '6' = '4+ hours')),
    stq14 = list( Description = 'On a typical weekend, how many hours do you video chat (Skype, FaceTime, etc.)?',
                   Levels = list ('0' = 'None',
                                  '1' = '< 30 minutes',
                                  '2' = '30 minutes',
                                  '3' = '1 hour',
                                  '4' = '2 hours',
                                  '5' = '3 hours',
                                  '6' = '4+ hours')),
    stq15 = list( Description = 'How often do you play mature-rated video games (e.g., Call of Duty, Grand Theft Auto, Assassin\'s Creed, etc.)? ',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Once in a while',
                                  '2' = 'Regularly',
                                  '3' = 'All the time')),
    stq16 = list( Description = 'How often do you watch R-rated movies?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Once in a while',
                                 '2' = 'Regularly',
                                 '3' = 'All the time')),
    stq17 = list( Description = 'Do you watch TV, videos, play video games, text, visit social media sites, or video chat while eating meals?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Once in a while',
                                 '2' = 'Regularly',
                                 '3' = 'All the time')),
    stq_notes = list(Description = "" ))

  # convert formatting to JSON
  stq_json <- RJSONIO::toJSON(stq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(stq_json, asText = TRUE))){
    print('stq JSON file may be invalid')
  }

  return(stq_json)

}
