#' json_debq: Generates a json file for the Dutch Eating Behavior Questionnaire
#'
#' This function generates a json file for the scored Dutch Eating Behavior Questionnaire and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Dutch Eating Behavior Questionnaire
#'
#'
#' @export

json_debq <- function() {

  debq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Dutch Eating Behavior Questionnaire.',
      Reference = 'Wardle J. Eating style: a validation study of the Dutch Eating Behaviour Questionnaire in normal subjects and women with eating disorders. J Psychosom Res. 1987;31(2):161-9. doi: 10.1016/0022-3999(87)90072-9. PMID: 3473234.',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/3473234/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    debq1 = list( Description = 'Do you have the desire to eat when you are irritated?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq2 = list( Description = 'If food tastes good to you, do you eat more than usual?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq3 = list( Description = 'Do you have a desire to eat when you have nothing to do?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq4 = list( Description = 'If you have put on weight, do you eat less than you usually do?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq5 = list( Description = 'Do you have a desire to eat when you are depressed or discouraged?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq6 = list( Description = 'If food smells and looks good, do you eat more than usual?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq7 = list( Description = 'How often do you refuse food or drink offered because you are concerned about your weight?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq8 = list( Description = 'Do you have a desire to eat when you are feeling lonely?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq9 = list( Description = 'If you see or smell something delicious, do you have a desire to eat it?',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Seldom',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Very Often')),
    debq10 = list( Description = 'Do you have a desire to eat when somebody lets you down?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq11 = list( Description = 'Do you try to eat less at mealtimes than you would like to eat?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq12 = list( Description = 'If you have something delicious to eat, do you eat it straight away?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq13 = list( Description = 'Do you have a desire to eat when you are cross?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq14 = list( Description = 'Do you watch exactly what you eat?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq15 = list( Description = 'If you walk past the baker do you have the desire to buy something delicious?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq16 = list( Description = 'Do you have a desire to eat when you are approaching something unpleasant to happen?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq17 = list( Description = 'Do you deliberately eat foods that are slimming?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq18 = list( Description = 'If you see others eating, do you also have the desire to eat?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq19 = list( Description = 'When you have eaten too much, do you eat less than usual the following days?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq20 = list( Description = 'Do you get the desire to eat when things are going against you or when things have gone wrong?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq21 = list( Description = 'Can you resist eating delicious foods',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq22 = list( Description = 'Do you deliberately eat less in order not to become heavier?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq23 = list( Description = 'Do you have a desire to eat when things are going against you or when things have gone wrong?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq24 = list( Description = 'If you walk past a snack bar or a caf\u00E9, do you have the desire to buy something delicious?',
                     Levels = list ('0' = 'Never',
                                    '1' = 'Seldom',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Very Often')),
    debq25 = list( Description = 'Do you have the desire to eat when you are emotionally upset?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq26 = list( Description = 'How often do you try not to eat between meals because you are watching your weight?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq27 = list( Description = 'Do you eat more than usual when you see others eating?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq28 = list( Description = 'Do you have a desire to eat when you are bored or restless?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq29 = list( Description = 'How often in the evening do you try not to eat because you are watching your weight?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq30 = list( Description = 'Do you have a desire to eat when you are frightened?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq31 = list( Description = 'Do you take into account your weight with what you eat?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq32 = list( Description = 'Do you have a desire to eat when you are disappointed?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq33 = list( Description = 'When you are preparing a meal are you inclined to eat?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Seldom',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Very Often')),
    debq_emotional = list( Description = 'emotional eating',
                Derivative = TRUE),
    debq_external = list( Description = 'external eating',
                Derivative = TRUE),
    debq_restrained = list( Description = 'restrained eating',
                           Derivative = TRUE)
  )

  # convert formatting to JSON
  debq_json <- RJSONIO::toJSON(debq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(debq_json, asText = TRUE))){
    print('debq JSON file may be invalid')
  }

  return(debq_json)

}
