#' json_pstca: Generates a json file for the Parental Strategies to Teach Children about Advertising Questionnaire
#'
#' This function generates a json file for the Parental Strategies to Teach Children about Advertising Questionnaire
#'
#' @return A string with data stored in JSON format containing meta-data for the Parental Strategies to Teach Children about Advertising Questionnaire
#'
#'
#' @export

json_pstca <- function() {

  pstca_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Parental Strategies to Teach Children about Advertising. This survey was developed by the Keller Lab based on multiple existing scales/questionnaires for Project REACH.'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    pstca_form_date = list( Description = 'Date (YYYY-MM-DD) pstca form was completed on redcap'),
    pstca_1 = list( Description = 'What is your age in years?'),
    pstca_2a = list( Description = 'In an average week, how many days on average does your child do the following activities?: Watching TV',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_2b = list( Description = 'In an average week, how many days on average does your child do the following activities?: Watching DVDs or VHS',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_2c = list( Description = 'In an average week, how many days on average does your child do the following activities?: Watching programs on the internet through streaming',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_2d = list( Description = 'In an average week, how many days on average does your child do the following activities?: Using apps or smartphones, iPod, iPad, or tablet',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_2e = list( Description = 'In an average week, how many days on average does your child do the following activities?: Using the internet',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_2f = list( Description = 'In an average week, how many days on average does your child do the following activities?: Playing games on a gaming station or computer',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_3a = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Watching TV',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_3b = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Watching DVDs or VHS',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_3c = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Watching programs on the internet through streaming on services like Netflix',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_3d = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Using apps or smartphone, iPod, iPad, or tablet',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_3e = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Viewing webpages on the internet that show video content',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_3f = list( Description = 'For each of the following activities you reported above, how many hours per day does your child engage in: Playing game on a gaming station or computer',
                     Levels = list ('0' =	'Less than 1 hour',
                                    '1'	= '1 hour',
                                    '2'	= '2 hours',
                                    '3'	= '3 hours',
                                    '4'	= '4 hours',
                                    '5'	= '4 or more hours',
                                    '6'	= 'N/A')),
    pstca_4a = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Baby first TV',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4b = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Boomerang',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4c = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Discovery Familia',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4d = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Discovery Family Channel',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4e = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Disney Channel',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4f = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Disney Junior',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4g = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Disney XD',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4h = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Nick Junior',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4i = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Nick-at-Nite',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4j = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Nickelodeon',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4k = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Nicktoons',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4l = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: TeenNick',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4m = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: The Cartoon Network',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4n = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: PBS',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4o = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Universal Kids',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4p = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Diet and Fitness Content',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4q = list( Description = 'Please answer "Yes or No" by the TV networks below that your child usually watches: Other',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_4q_response = list( Description = 'Other TV networks your child watches:'),
    pstca_5 = list( Description = 'Does your child watch YouTube?'),
    pstca_6 = list( Description = 'When your child watches YouTube, what do they primarily watch?',
                    Levels = list ('0' =	'Mostly regular YouTube',
                                   '1'	= 'Mostly YouTube kids',
                                   '2'	= 'Both regular Youtube and YouTube kids')),
    pstca_7 = list( Description = 'On YouTube there is...',
                    Levels = list ('0' =	'too little advertising',
                                   '1'	= 'just enough advertising',
                                   '2'	= 'too much advertising')),
    pstca_8a = list( Description = 'What does your child watch on YouTube?: Cooking videos (e.g. Kids Baking Championship...)',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8b = list( Description = 'What does your child watch on YouTube?: Nature/history videos',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8c = list( Description = 'What does your child watch on YouTube?: Science (e.g, TechRax, Minutephysics...)',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8d = list( Description = 'What does your child watch on YouTube?: Animated cartoons',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8e = list( Description = 'What does your child watch on YouTube?: YouTube Gaming* (e.g. DanTDM, Ethan Gamer...) [*YouTube Gaming: videos of gamers playing and commenting on games]',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8f = list( Description = 'What does your child watch on YouTube?: Unboxing videos* [*Unboxing Videos: videos where adults or children unwrap toys and games to play with]',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8g = list( Description = 'What does your child watch on YouTube?: Movies',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8h = list( Description = 'What does your child watch on YouTube?: Videos that feature real-kids and families playing with food (e.g., Ryan\'s World, Kids Kitchen Pretend Recipes on New Sky Kids channel...)',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8i = list( Description = 'What does your child watch on YouTube?: Sketch/comedy videos',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8j = list( Description = 'What does your child watch on YouTube?: Diet and Fitness videos',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8k = list( Description = 'What does your child watch on YouTube?: Other',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_8k_response = list( Description = 'Other videos your child watches on YouTube:'),
    pstca_9 = list( Description = 'The use of famous people on YouTube targeting children to promote food... (A YouTuber (Youtube content creator) produces videos for YouTube abour various subjects (e.g., video games, sports, make-up tutorials, food, etc...). Some YouTube personalities have sponors who pay for product placement in their YouTube clips. )',
                    Levels = list ('0' =	'annoys me',
                                   '1'	= 'doesn\'t bother me',
                                   '2' = 'makes me happy')),
    pstca_10 = list( Description = 'On how many days of the week does your child watch YouTube for entertainment?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_11 = list( Description = 'On an average Weekday, how many mintues does your child spend watching YouTube for entertainment? (e.g, "120" = two hours)'),
    pstca_12 = list( Description = 'On an average Weekend day, how many minutes does your child spend watching YouTube for entertainment?'),
    pstca_13 = list( Description = 'How many days of the week on average does your child ask for food products that they have seen on YouTube?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_14 = list( Description = 'How many days of the week on average do you purchase products that your child has seen on YouTube?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_15 = list( Description = 'Does your child watch Hulu or any other streaming services?',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_16 = list( Description = 'On how many days of the week does your child watch Hulu, or other streaming services (besides YouTube), for entertainment?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_17 = list( Description = 'On an average Weekday, how many minutes does your child spend watching Hulu or other streaming services (besides YouTube) for entertainment?'),
    pstca_18 = list( Description = 'On an average Weekend day, how many minutes does your child spend watching Hulu or other streaming services (besides YouTube) for entertainment?'),
    pstca_19 = list( Description = 'How many days of the week on average does your child ask for food products that they have seen on Hulu or other streaming services (besides YouTube)?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_20 = list( Description = 'How many days of the week on average do you purchase products that your child has seen on Hulu or other streaming services (besides YouTube)?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_21 = list( Description = 'Does your child watch TV for entertainment? ',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_22 = list( Description = 'On TV there is ________ advertising.',
                     Levels = list ('0' =	'too little',
                                    '1'	= 'just enough',
                                    '2'	= 'too much')),
    pstca_23a = list( Description = 'What does your child watch on TV?: Cooking shows (e.g., Kids Baking Championship, Be Our Chef on Disney Plus)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_23b = list( Description = 'What does your child watch on TV?: Nature/history shows (e.g., NatGeo...)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_23c = list( Description = 'What does your child watch on TV?: Science shows',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_23d = list( Description = 'What does your child watch on TV?: Animated cartoons',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_23e = list( Description = 'What does your child watch on TV?: Movies',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_23f = list( Description = 'What does your child watch on TV?: Sketch/comedy',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    pstca_24 = list( Description = 'On how many days of the week does your child watch TV for entertainment?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_25 = list( Description = 'On an average Weekday, how many minutes does your child spend watching TV for entertainment? '),
    pstca_26 = list( Description = 'On an average Weekend day, how many minutes does your child spend watching TV or entertainment? '),
    pstca_27 = list( Description = 'How many days in an average week does your child ask for food products that they have seen on TV?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_28 = list( Description = 'How many days of the week on average do you purchase products that your child has seen on TV?',
                     Levels = list ('0' =	'0 days',
                                    '1'	= '1 day',
                                    '2'	= '2 days',
                                    '3'	= '3 days',
                                    '4'	= '4 days',
                                    '5'	= '5 days',
                                    '6'	= '6 days',
                                    '7'	= '7 days')),
    pstca_29a = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she pays attention to the ads',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29b = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she skips the skippable ads',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29c = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she looks away when watching the screen',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29d = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she does not care about the ads',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29e = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she grumbles when an ad pops up and interrupts the show',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29f = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she makes positive comments about the products',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29g = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she makes negative comments about the products',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29h = list( Description = 'How many days of the week on average does your child exhibit the following behaviors while viewing advertisements?: He/she asks a caretaker to purchase the products',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_29i = list( Description = 'Are there are other behaviors you observe when your child is watching YouTube or TV? '),
    pstca_30 = list( Description = 'Do you try to teach your child about the effects of advertising?',
                     Levels = list ('0' =	'No',
                                    '1'	= 'Yes')),
    pstca_31a = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that advertising depicts products as better than they actually are?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31b = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that advertising does not always tell the truth?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31c = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that the purpose of advertising is to sell products?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31d = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that not all advertised products are of good quality?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31e = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that some advertised products are not good for children?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31f = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that people in advertisements are not as cool as they seem?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_31g = list( Description = 'How many days of the week on average do you try to teach your child the following about advertising?: that products in the advertisements do not always work like they do on TV.',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_32a = list( Description = 'How many days of the week on average do you teach your child...: to skip the ad when it is skippable',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_32b = list( Description = 'How many days of the week on average do you teach your child...: not to watch the screen or mute the computer or TV when the advertisement pops up',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_33 = list( Description = 'How often do you restrict the amount of time your child spends on a streaming service or TV in order to avoid exposure to advertising?',
                     Levels = list ('0' =	'Never',
                                    '1'	= 'Rarely',
                                    '2'	= 'Sometimes',
                                    '3'	= 'Often',
                                    '4'	= 'Always')),
    pstca_34 = list( Description = 'How often do you put restrictions on your child\'s electronic devices so he/she is not exposed to advertising?',
                     Levels = list ('0' =	'Never',
                                    '1'	= 'Rarely',
                                    '2'	= 'Sometimes',
                                    '3'	= 'Often',
                                    '4'	= 'Always')),
    pstca_35 = list( Description = 'How often do you prerecord shows for your child or watch On Demand/Netflix so that advertising content can be skipped? ',
                     Levels = list ('0' =	'Never',
                                    '1'	= 'Rarely',
                                    '2'	= 'Sometimes',
                                    '3'	= 'Often',
                                    '4'	= 'Always')),
    pstca_36a = list( Description = 'How many days of the week on average do you tell your child...: that every member of your family should have some say in family purchase decisions?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_36b = list( Description = 'How many days of the week on average do you tell your child...: to give his/her opinion when discussing family purchases?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_36c = list( Description = 'How many days of the week on average do you tell your child...: to give his/her opinion about products and brands?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_36d = list( Description = 'How many days of the week on average do you tell your child...: that you respect his/her expertise on certain products and brands?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_36e = list( Description = 'How many days of the week on average do you tell your child...: to consider the advantages and disadvantages of products and brands?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_36f = list( Description = 'How many days of the week on average do you tell your child...: that he/she can co-decide when you make purchases for him/her?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37a = list( Description = 'How many days of the week on average do you tell your child...: that you know which products are best for him/her?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37b = list( Description = 'How many days of the week on average do you tell your child...: not to argue with you when you say no to his/her product request?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37c = list( Description = 'How many days of the week on average do you tell your child...: that you expect him/her to accept your decisions about product purchases?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37d = list( Description = 'How many days of the week on average do you tell your child...: which products he/she should or should not buy?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37e = list( Description = 'How many days of the week on average do you tell your child...: that you have strict and clear rules when it comes to product purchases?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_37f = list( Description = 'How many days of the week on average do you tell your child...: that (s)he is not allowed to ask for products?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_38a = list( Description = 'How many days of the week on average does your child show the following behaviors when you attempt to teach him/her about the effects of advertising: He/she skips ads?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_38b = list( Description = 'How many days of the week on average does your child show the following behaviors when you attempt to teach him/her about the effects of advertising: He/she recognizes and points out ads?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_38c = list( Description = 'How many days of the week on average does your child show the following behaviors when you attempt to teach him/her about the effects of advertising: He/she tells you when he/she sees ads?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_38d = list( Description = 'How many days of the week on average does your child show the following behaviors when you attempt to teach him/her about the effects of advertising: He/she makes requests for you to buy healthy foods?',
                      Levels = list ('0' =	'0 days',
                                     '1'	= '1 day',
                                     '2'	= '2 days',
                                     '3'	= '3 days',
                                     '4'	= '4 days',
                                     '5'	= '5 days',
                                     '6'	= '6 days',
                                     '7'	= '7 days')),
    pstca_38e = list( Description = 'Other behaviors your child shows when you attempt to teach him/her about the effects of advertising?')
    )

  # convert formatting to JSON
  pstca_json <- RJSONIO::toJSON(pstca_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(pstca_json, asText = TRUE))){
    print('pstca JSON file may be invalid')
  }

  return(pstca_json)

}
