#' json_cbq: Generates a json file for the Children\'s Behavior Questionnaire
#'
#' This function generates a json file for the scored Children\'s Behavior Questionnaire and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Child Behavior Questionnaire
#'
#'
#' @export

json_cbq <- function() {

  cbq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Children\'s Behavior Questionnaire. Participants were provided the following instructions: "Please read carefully before starting. You will see a set of statements that describe children\'s reactions to a number of situations. We would like you to tell us what your child\'s reaction is likely to be in those situations. There are of course no "correct" ways of reacting; children differ widely in their reactions, and it is these differences we are trying to learn about. Please read each statement and decide whether it is a "true" or "untrue" description of your child\'s reaction within the past six months. If you cannot answer one of the items because you have never seen the child in that situation, for example, if the statement is about the child\'s reaction to your singing and you have never sung to your child, then choose NA (not applicable). Please be sure to choose an answer or NA for every item."',
      Reference = 'Putnam SP, Rothbart MK. Development of Short and Very Short Forms of the Children\'s Behavior Questionnaire. Journal of Personality Assessment. 2006;87(1). doi:10.1207/s15327752jpa8701_09',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/16856791/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                    Levels = list ('ses-1' = 'session 1 / baseline',
                                   'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    cbq1 = list( Description = 'Seems always in a big hurry to get from one place to another.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq2 = list( Description = 'Gets angry when told s/he has to go to bed.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq3 = list( Description = 'Is not very bothered by pain.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq4 = list( Description = 'Likes going down high slides or other adventurous activities.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq5 = list( Description = 'Notices the smoothness or roughness of objects s/he touches.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq6 = list( Description = 'Gets so worked up before an exciting event that s/he has trouble sitting still.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq7 = list( Description = 'Usually rushes into an activity without thinking about it.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq8 = list( Description = 'Cries sadly when a favorite toy gets lost or broken.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq9 = list( Description = 'Becomes quite uncomfortable when cold and/or wet.',
                 LLevels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq10 = list( Description = 'Likes to play so wild and recklessly that s/he might get hurt.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq11 = list( Description = 'Seems to be at ease with almost any person.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq12 = list( Description = 'Tends to run rather than walk from room to room.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq13 = list( Description = 'Notices it when parents are wearing new clothing.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq14 = list( Description = 'Has temper tantrums when s/he doesn\'t get what s/he wants.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq15 = list( Description = 'Gets very enthusiastic about the things s/he does.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq16 = list( Description = 'When practicing an activity, has a hard time keeping her/his mind on it.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq17 = list( Description = 'Is afraid of burglars or the "boogie man."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq18 = list( Description = 'When outside, often sits quietly.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq19 = list( Description = 'Enjoys funny stories but usually doesn\'t laugh at them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq20 = list( Description = 'Tends to become sad if the family\'s plans don\'t work out.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq21 = list( Description = 'Will move from one task to another without completing any of them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq22 = list( Description = 'Moves about actively (runs, climbs, jumps) when playing in the house.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq23 = list( Description = 'Is afraid of loud noises.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq24 = list( Description = 'Seems to listen to even quiet sounds.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq25 = list( Description = 'Has a hard time settling down after an exciting activity.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq26 = list( Description = 'Enjoys taking warm baths.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq27 = list( Description = 'Seems to feel depressed when unable to accomplish some task.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq28 = list( Description = 'Often rushes into new situations.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq29 = list( Description = 'Is quite upset by a little cut or bruise.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq30 = list( Description = 'Gets quite frustrated when prevented from doing something s/he wants to do.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq31 = list( Description = 'Becomes upset when loved relatives or friends are getting ready to leave following a visit.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq32 = list( Description = 'Comments when a parent has changed his/her appearance.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq33 = list( Description = 'Enjoys activities such as being chased, spun around by the arms, etc.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq34 = list( Description = 'When angry about something, s/he tends to stay upset for ten minutes or longer.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq35 = list( Description = 'Is not afraid of the dark.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq36 = list( Description = 'Takes a long time in approaching new situations.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq37 = list( Description = 'Is sometimes shy even around people s/he has known for a long time.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq38 = list( Description = 'Can wait before entering into new activities if s/he is asked to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq39 = list( Description = 'Enjoys "snuggling up" net to a parent or babysitter."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq40 = list( Description = 'Gets angry when s/he can\'t find something s/he wants to play with.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq41 = list( Description = 'Is afraid of fire.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq42 = list( Description = 'Sometimes seems nervous when talking to adults s/he has just met.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq43 = list( Description = 'Is slow and unhurried in deciding what to do next.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq44 = list( Description = 'Changes from being upset to feeling much better within a few minutes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq45 = list( Description = 'Prepares for trips and outings by planning things s/he will need.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq46 = list( Description = 'Becomes very excited while planning for trips.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq47 = list( Description = 'Is quickly aware of some new item in the living room.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq48 = list( Description = 'Hardly ever laughs out loud during play with other children.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq49 = list( Description = 'Is not very upset at minor cuts or bruises.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq50 = list( Description = 'Prefers quiet activities to active games.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq51= list( Description = 'Tends to say the first thing that comes to mind, without stopping to think about it.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq52 = list( Description = 'Acts shy around new people.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq53 = list( Description = 'Has trouble sitting still when s/he is told to (at movies, church, etc.).',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq54 = list( Description = 'Rarely cries when s/he hears a sad story.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq55 = list( Description = 'Sometimes smiles or giggles playing by her/himself.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq56 = list( Description = 'Rarely becomes upset when watching a sad event in a TV show.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq57 = list( Description = 'Enjoys just being talked to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq58 = list( Description = 'Becomes very excited before an outing (e.g., picnic, party).',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq59 = list( Description = 'If upset, cheers up quickly when s/he thinks about something else.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq60 = list( Description = 'Is comfortable asking other children to play.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq61 = list( Description = 'Rarely gets upset when told s/he has to go to bed.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq62 = list( Description = 'When drawing or coloring in a book, shows strong concentration.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq63 = list( Description = 'Is afraid of the dark.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq64 = list( Description = 'Is likely to cry when even a little bit hurt.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq65 = list( Description = 'Enjoys looking at picture books.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq66 = list( Description = 'Is easy to soothe when s/he is upset.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq67 = list( Description = 'Is good at following instructions.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq68 = list( Description = 'Is rarely frightened by "monsters" seen on TV or at movies.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq69 = list( Description = 'Likes to go high and fast when pushed on a swing.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq70 = list( Description = 'Sometimes turns away shyly from new acquaintances.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq71 = list( Description = 'When building or putting something together, becomes very involved in what s/he is doing, and works for long periods.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq72 = list( Description = 'Likes being sung to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq73 = list( Description = 'Approaches places s/he has been told are dangerous slowly and cautiously.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq74 = list( Description = 'Rarely becomes discouraged when s/he has trouble making something work.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq75 = list( Description = 'Is very difficult to soothe when s/he has become upset.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq76 = list( Description = 'Likes the sound of words, such as nursery rhymes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq77 = list( Description = 'Smiles a lot at people s/he likes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq78 = list( Description = 'Dislikes rough and rowdy games.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq79 = list( Description = 'Often laughs out loud in play with other children.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq80 = list( Description = 'Rarely laughs aloud while watching TV or movie comedies.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq81 = list( Description = 'Can easily stop an activity when s/he is told "no."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq82 = list( Description = 'Is among the last children to try out a new activity.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq83 = list( Description = 'Doesn\'t usually notice odors such as perfume, smoke, cooking, etc.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq84 = list( Description = 'Is easily distracted when listening to a story.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq85 = list( Description = 'Is full of energy, even in the evening.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq86 = list( Description = 'Enjoys sitting on parent\'s lap.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq87 = list( Description = 'Gets angry when called in from play before s/he is ready to quit.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq88 = list( Description = 'Enjoys riding a tricycle or bicycle fast and recklessly.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq89 = list( Description = 'Sometimes becomes absorbed in a picture book and looks at if for a long time.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq90 = list( Description = 'Remains pretty calm about upcoming desserts like ice cream.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq91 = list( Description = 'Hardly ever complains when ill with a cold.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq92 = list( Description = 'Looks forward to family outings, but does not get too excited about them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq93 = list( Description = 'Likes to sit quietly and watch people do things.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq94 = list( Description = 'Enjoys gentle rhythmic activities, such as rocking or swaying.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),

    cbq_activity = list( Description = 'Activity Level. Mean of items "cbq1", "cbq12", "cbq18", "cbq22", "cbq50", "cbq85", "cbq93"',
                                 Derivative = TRUE),
    cbq_anger = list( Description = 'Anger/Frustration. Mean of items "cbq2", "cbq14", "cbq30", "cbq40", "cbq61", "cbq87"',
                         Derivative = TRUE),
    cbq_approach = list( Description = 'Approach/Positive Anticipation. Mean of items "cbq6", "cbq15", "cbq46", "cbq58", "cbq90", "cbq92"',
                         Derivative = TRUE),
    cbq_attention = list( Description = 'Attentional Focusing. Mean of items "cbq16", "cbq21", "cbq62", "cbq71", "cbq84", "cbq89"',
                         Derivative = TRUE),
    cbq_discomfort = list( Description = 'Discomfort. Mean of items "cbq3", "cbq9", "cbq29", "cbq49", "cbq64", "cbq91',
                         Derivative = TRUE),
    cbq_soothability = list( Description = 'Falling Reactivity/Soothability. Mean of items "cbq25", "cbq34", "cbq44", "cbq59", "cbq66", "cbq75"',
                         Derivative = TRUE),
    cbq_fear = list( Description = 'Fear. Mean of "cbq17", "cbq23", "cbq35", "cbq41", "cbq63", "cbq68"',
                             Derivative = TRUE),
    cbq_highintensity_pleasure = list( Description = 'High Intensity Pleasure. Mean of "cbq4", "cbq10", "cbq33", "cbq69", "cbq78", "cbq88"',
                     Derivative = TRUE),
    cbq_impulsivity = list( Description = 'Impulsivity. Mean of "cbq7", "cbq28", "cbq36", "cbq43", "cbq51", "cbq82"',
                     Derivative = TRUE),
    cbq_inhibitory_cont = list( Description = 'Inhibitory control. Mean of "cbq38", "cbq45", "cbq53", "cbq67", "cbq73", "cbq81"',
                     Derivative = TRUE),
    cbq_lowintensity_pleasure = list( Description = 'Low Intensity Pleasure. Mean of "cbq26", "cbq39", "cbq57", "cbq65", "cbq72", "cbq76","cbq86", "cbq94"',
                     Derivative = TRUE),
    cbq_perceptual_sensitivity = list( Description = 'Perceptual Sensitivity. Mean of items "cbq5", "cbq13", "cbq24", "cbq32", "cbq47", "cbq83"',
                         Derivative = TRUE),
    cbq_sadness = list( Description = 'Sadness. Mean of items "cbq8", "cbq20", "cbq27", "cbq31", "cbq54", "cbq56", "cbq74"',
                         Derivative = TRUE),
    cbq_shyness = list( Description = 'Shyness. Mean of items "cbq11", "cbq37", "cbq42", "cbq52", "cbq60", "cbq70"',
                         Derivative = TRUE),
    cbq_smile_laughter = list( Description = 'Smiling and Laughter. Mean of items "cbq19", "cbq48", "cbq55", "cbq77", "cbq79", "cbq80"',
                         Derivative = TRUE),
    cbq_surgency = list( Description = 'Big 3 - Surgency',
                         Derivative = TRUE),
    cbq_neg_affect = list( Description = 'Big 3 - Negative Affect',
                         Derivative = TRUE),
    cbq_effortful_cont = list( Description = 'Big 3 - Effortful Control',
                         Derivative = TRUE)
    )



  # convert formatting to JSON
  cbq_json <- RJSONIO::toJSON(cbq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cbq_json, asText = TRUE))){
    print('cbq JSON file may be invalid')
  }

  return(cbq_json)

}
