#' json_participants: Generates a json file for participants.tsv
#'
#' This function generates a json file for participants.tsv
#'
#' @return A string with data stored in JSON format containing meta-data for participants.tsv
#'
#'
#' @export

json_participants <- function() {

  participants_list <- list(
    participant_id = list( Description = 'participant id number'),
    risk_status = list( Description = 'Familial risk status for obesity based on maternal_bmi_v1',
                        Levels = list('low-risk' = 'maternal bmi at visit 1: 18.5-25',
                                      'high-risk' = 'maternal bmi at visit 1: >= 30.0'),
                        Derivative = TRUE),
    sex = list( Description = 'Parent-reported child sex',
                Levels = list ('female' = 'female',
                               'male' = 'male')),
    ethnicity = list( Description = 'Parent-reported child ethnicity',
                      Levels = list ('0' = 'Not Hispanic or Latino',
                                     '1' = 'Hispanic or Latino')),
    race = list( Description = 'Parent-reported child race',
                 Levels = list ('0' = 'American Indian/Alaskan Native',
                                '1' = 'Asian',
                                '2' = 'Black or African American',
                                '3' = 'White',
                                '4' = 'Hawaiian/Pacific Islander',
                                '5' = 'Other')),
    child_protocol_1_age = list( Description = 'Child age at child visit protocol 1. Computed as difference between child_protocol_1_date and child date of birth (not shared)',
                   Unit = 'years',
                   Derivative = TRUE),
    child_protocol_1_age = list( Description = 'Child age at child visit protocol 2. Computed as difference between child_protocol_2_date and child date of birth (not shared',
                   Unit = 'years',
                   Derivative = TRUE),
    child_protocol_1_age = list( Description = 'Child age at child visit protocol 3. Computed as difference between child_protocol_3_date and child date of birth (not shared',
                   Unit = 'years',
                   Derivative = TRUE),
    child_protocol_1_age = list( Description = 'Child age at child visit protocol 4. Computed as difference between child_protocol_4_date and child date of birth (not shared',
                   Unit = 'years',
                   Derivative = TRUE),
    child_protocol_1_age = list( Description = 'Child age at child visit protocol 5. Computed as difference between child_protocol_5_date and child date of birth (not shared',
                   Unit = 'years',
                   Derivative = TRUE),
    demo_education_mom_v1 = list( Description = 'Parent-reported maternal education on visit 1. Can also be found in household.tsv (demo_education_mom where session_id = "ses-1") ',
                                  Levels = list ('0' = 'None',
                                                 '1' = 'Preschool',
                                                 '2' = 'Kindergarten',
                                                 '3' = '1st grade',
                                                 '4' = '2nd grade',
                                                 '5' = '3rd grade',
                                                 '6' = '4th grade',
                                                 '7' = '5th grade',
                                                 '8' = '6th grade',
                                                 '9' = '7th grade',
                                                 '10' = '8th grade',
                                                 '11' = '9th grade',
                                                 '12' = '10th grade',
                                                 '13' = '11th grade',
                                                 '14' = 'GED',
                                                 '15' = 'High School graduate',
                                                 '16' = 'Some college but less than 1 year',
                                                 '17' = 'One or more years of college at a 2-year program, No degree obtained',
                                                 '18' = 'One year of college at a 4-year program, No degree obtained',
                                                 '19' = 'Two years of college at a 4-year program, No degree obtained',
                                                 '20' = 'Three years of college at a 4-year program, No degree obtained',
                                                 '21' = 'Associates degree (AA, AS)',
                                                 '22' = 'Bachelor\'s Degree (BA, AB, BS)',
                                                 '23' = 'Master\'s degree (MA, MS, MEng, MEd, MSW, MBA, MPH)',
                                                 '24' = 'Professional Degree (MD, DDS, DVM, LLB, JD, DPT, PharmD)',
                                                 '25' = 'Doctoral Degree (PhD, EdD, PsyD)',
                                                 '26' = 'N/A')),
    demo_education_mom_v5 = list( Description = 'Parent-reported maternal education on visit 5. Can also be found in household.tsv (demo_education_mom where session_id = "ses-2")',
                                  Levels = list ('0' = 'None',
                                                 '1' = 'Preschool',
                                                 '2' = 'Kindergarten',
                                                 '3' = '1st grade',
                                                 '4' = '2nd grade',
                                                 '5' = '3rd grade',
                                                 '6' = '4th grade',
                                                 '7' = '5th grade',
                                                 '8' = '6th grade',
                                                 '9' = '7th grade',
                                                 '10' = '8th grade',
                                                 '11' = '9th grade',
                                                 '12' = '10th grade',
                                                 '13' = '11th grade',
                                                 '14' = 'GED',
                                                 '15' = 'High School graduate',
                                                 '16' = 'Some college but less than 1 year',
                                                 '17' = 'One or more years of college at a 2-year program, No degree obtained',
                                                 '18' = 'One year of college at a 4-year program, No degree obtained',
                                                 '19' = 'Two years of college at a 4-year program, No degree obtained',
                                                 '20' = 'Three years of college at a 4-year program, No degree obtained',
                                                 '21' = 'Associates degree (AA, AS)',
                                                 '22' = 'Bachelor\'s Degree (BA, AB, BS)',
                                                 '23' = 'Master\'s degree (MA, MS, MEng, MEd, MSW, MBA, MPH)',
                                                 '24' = 'Professional Degree (MD, DDS, DVM, LLB, JD, DPT, PharmD)',
                                                 '25' = 'Doctoral Degree (PhD, EdD, PsyD)',
                                                 '26' = 'N/A')),
    demo_income_v1 = list( Description = 'Parent-reported family income on visit 1. Can also be found in household.tsv (demo_income where session_id = "ses-1"). Parent\'s were asked: "Including ALL sources (such as social security income, child support payments, government assistance, dividends from investments, etc.) what was your household\'s combined yearly income last year BEFORE taxes?"',
                        Levels = list ('0' = 'Less than $20,000',
                                       '1' = '$21,000 - $35,000',
                                       '2' = '$36,000 - $50,000',
                                       '3' = '$51,000 - $75,000',
                                       '4' = '$76,000 - $100,000',
                                       '5' = '$100,000 +')),
    demo_income_v5 = list( Description = 'Parent-reported family income on visit 5. Can also be found in household.tsv (demo_income where session_id = "ses-2") Parent\'s were asked: "Including ALL sources (such as social security income, child support payments, government assistance, dividends from investments, etc.) what was your household\'s combined yearly income last year BEFORE taxes?"',
                           Levels = list ('0' = 'Less than $20,000',
                                          '1' = '$21,000 - $35,000',
                                          '2' = '$36,000 - $50,000',
                                          '3' = '$51,000 - $75,000',
                                          '4' = '$76,000 - $100,000',
                                          '5' = '$100,000 +')),
    maternal_bmi_v1 = list( Description = 'Maternal BMI at visit 1',
                            Derivative = TRUE,
                            Unit = 'kg/m^2'),
    maternal_anthro_method_v1 = list( Description = 'Method used to determine maternal_bmi_v1',
                                      Levels = list('measured' = 'BMI calculated from height and weight measurements on visit 1',
                                                    'reported' = 'BMI calculated from parent-reported height and weight values on visit 1.')),
    child_protocol_order = list( Description = 'Child protocol visit order based on child_protocol dates',
                                 Derivative = TRUE),
    child_protocol_1_date = list( Description = 'Date of child visit protocol 1 (YYYY-MM-DD). This was always the first visit of the study'),
    child_protocol_2_date = list( Description = 'Date of child visit protocol 2 (YYYY-MM-DD)'),
    child_protocol_3_date = list( Description = 'Date of child visit protocol 3 (YYYY-MM-DD)'),
    child_protocol_4_date = list( Description = 'Date of child visit protocol 4 (YYYY-MM-DD)'),
    child_protocol_5_date = list( Description = 'Date of child visit protocol 5 (YYYY-MM-DD). This was always the final visit of the study')
    )

  # convert formatting to JSON
  participants_json <- RJSONIO::toJSON(participants_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(participants_json, asText = TRUE))){
    print('Participants JSON file may be invalid')
  }

  return(participants_json)

}
