#' json_cfpq: Generates a json file for the Comprehensive Feeding Practices Questionnaire
#'
#' This function generates a json file for the scored Comprehensive Feeding Practices Questionnaire and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Comprehensive Feeding Practices Questionnaire
#'
#'
#' @export

json_cfpq <- function() {

  cfpq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Comprehensive Feeding Practices Questionnaire. Participants were provided the following instructions: "Please answer the following questions about your child:"',
      Reference = 'Musher-Eizenman, D., Holub. S., Comprehensive Feeding Practices Questionnaire: Validation of a New Measure of Parental Feeding Practices, Journal of Pediatric Psychology, 32, 8, September 2007, Pages 960 to 972',
      TermURL = 'https://doi.org/10.1093/jpepsy/jsm037'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    cfpq1 = list( Description = 'How much do you keep track of the sweets (candy, ice cream, cakes) that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq2 = list( Description = 'How much do you keep track of the snack food (potato chips, cheese puffs, Doritos) that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq3 = list( Description = 'How much do you keep track of the high-fat foods that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq4 = list( Description = 'How much do you keep track of the sugary drinks (soda/pop, kool-aid) that your child drinks?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq5 = list( Description = 'Do you let your child eat whatever s/he wants?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq6 = list( Description = 'At dinner, do you let this child choose the foods s/he wants from what is served?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq7 = list( Description = 'When this child gets fussy, is giving him/her something to eat or drink the first thing you do?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq8 = list( Description = 'Do you give this child something to eat/drink if s/he is bored even if you think s/he is not hungry?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq9 = list( Description = 'Do you give this child something to eat/drink if s/he is upset even if you think s/he is not hungry?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfpq10 = list( Description = 'If this child does not like what is being served, do you make something else?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq11 = list( Description = 'Do you allow this child to eat snacks whenever s/he wants?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq12 = list( Description = 'Do you allow this child to leave the table when s/he is full, even if your family is not done eating?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq13 = list( Description = 'Do you encourage this child to eat healthy foods before unhealthy ones?',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq14 = list( Description = 'Most of the food I keep in the house is healthy.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq15 = list( Description = 'I involve my child in planning family meals.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq16 = list( Description = 'I keep a lot of snack food (potato chips, cheese puffs, Doritos) in my house',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq17 = list( Description = 'My child should always eat all the food on his/her plate.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq18 = list( Description = 'I have to be sure my child does not eat too many high-fat foods.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq19 = list( Description = 'I offer my child his/her favorite foods in exchange for good behavior.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq20 = list( Description = 'I allow my child to help prepare family meals.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq21 = list( Description = 'If I did not guide or regulate my child\'s eating, s/he would eat too much of his/her favorite foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq22 = list( Description = 'A variety of healthy foods are available to my child at each meal served at home.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq23 = list( Description = 'I offer sweets (candy, ice cream, cakes, pies) to my child as a reward for good behavior',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq24 = list( Description = 'I encourage my child to try new foods.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq25 = list( Description = 'I discuss with my child why it\'s important to eat healthy foods.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq26 = list( Description = 'I tell my child that healthy food tastes good',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq27 = list( Description = 'I encourage my child to eat less so he/she won\'t get fat',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq28 = list( Description = 'If I did not guide or regulate my child\'s eating, he/she would eat too many junk foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq29 = list( Description = 'I give my child small helpings at meals to control his/her weight.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq30 = list( Description = 'If my child says, "I\'m not hungry," I try to get him/her to eat anyway',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq31 = list( Description = 'I discuss with my child the nutritional value of foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq32 = list( Description = 'I encourage my child to participate in grocery shopping.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq33 = list( Description = 'If my child eats more than usual at one meal, I try to restrict his/her eating at the next meal.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq34 = list( Description = 'I restrict the food my child eats that might make him/her fat',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq35 = list( Description = 'There are certain foods my child shouldn\'t eat because they will make him/her fat.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq36 = list( Description = 'I withhold sweets/dessert from my child in response to bad behavior',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq37 = list( Description = 'I keep a lot of sweets (candy, ice cream, cakes, pies, pastries) in my house.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq38 = list( Description = 'I encourage my child to try a variety of foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq39 = list( Description = 'If my child eats only a small helping, I try to get him/her to eat more',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq40 = list( Description = 'I have to be sure that my child does not eat too much of his/her favorite foods.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq41 = list( Description = 'I don\'t allow my child to eat between meals because I don\'t want him/her to get fat.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq42 = list( Description = 'I tell my child what to eat and what not to eat without explanation.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq43 = list( Description = 'I have to be sure that my child does not eat too many sweets (candy, ice cream, cake or pastries).',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq44 = list( Description = 'I model healthy eating for my child by eating healthy foods myself.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq45 = list( Description = 'I often put my child on a diet to control his/her weight.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq46 = list( Description = 'I try to eat healthy foods in front of my child, even if they are not my favorite.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq47 = list( Description = 'I try to show enthusiasm about eating healthy foods.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq48 = list( Description = 'I show my child how much I enjoy eating healthy foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq49 = list( Description = 'When s/he says s/he is finished eating, I try to get my child to eat one more (two more, etc.) bites of food.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Mostly',
                                  '4' = 'Always')),
    cfpq_control = list(Description = 'Child Control',
                        Derivative = TRUE),
    cfpq_emoreg = list( Description = 'Emotion regulation',
                        Derivative = TRUE),
    cfpq_balance = list(Description = 'Encourage balance and variety',
                        Derivative = TRUE),
    cfpq_env = list(Description = 'Environment',
                    Derivative = TRUE),
    cfpq_reward = list(Description = 'Food as reward',
                        Derivative = TRUE),
    cfpq_involve = list(Description = 'Involvement',
                        Derivative = TRUE),
    cfpq_model = list(Description = 'Modeling',
                      Derivative = TRUE),
    cfpq_monitor = list(Description = 'Monitoring',
                        Derivative = TRUE),
    cfpq_pressure = list(Description = 'Pressure',
                          Derivative = TRUE),
    cfpq_restrict_health = list(Description = 'Restriction for Health',
                                Derivative = TRUE),
    cfpq_restrict_weight = list(Description = 'Restriction for weight control',
                                Derivative = TRUE),
    cfpq_teach = list( Description = 'Teaching about nutrition',
                       Derivative = TRUE))


  # convert formatting to JSON
  cfpq_json <- RJSONIO::toJSON(cfpq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cfpq_json, asText = TRUE))){
    print('cfpq JSON file may be invalid')
  }

  return(cfpq_json)

}
