#' json_cbq: Generates a json file for the Child Behavior Questionnaire
#'
#' This function generates a json file for the scored Child Behavior Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_cbq function in dataprepr and is only accurate for data collected in Study BREAK
#'
#' @return A json file documenting the raw inputs and scored values for the Child Behavior Questionnaire
#'
#'
#' @export

json_cbq <- function() {

  cbq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Child Behavior Questionnaire',
      Reference = 'Putnam SP, Rothbart MK. Development of Short and Very Short Forms of the Children’s Behavior Questionnaire. Journal of Personality Assessment. 2006;87(1):102-112. doi:10.1207/s15327752jpa8701_09',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/16856791/'),
    participant_id = list( Description = 'participant id number'),
    session = list( Description = 'Session of data collection',
                    Levels = list ('ses-1' = 'session 1 / baseline',
                                   'ses-2' = 'session 2 / follow-up')),
    visit = list( Description = 'REACH visit protocol for data collection'),
    cbq1 = list( Description = 'Seems always in a big hurry to get from one place to another.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq2 = list( Description = 'Gets angry when told s/he has to go to bed.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq3 = list( Description = 'Is not very bothered by pain.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq4 = list( Description = 'Likes going down high slides or other adventurous activities.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq5 = list( Description = 'Notices the smoothness or roughness of objects s/he touches.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq6 = list( Description = 'Gets so worked up before an exciting event that s/he has trouble sitting still.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq7 = list( Description = 'Usually rushes into an activity without thinking about it.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq8 = list( Description = 'Cries sadly when a favorite toy gets lost or broken.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq9 = list( Description = 'Becomes quite uncomfortable when cold and/or wet.',
                 LLevels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq10 = list( Description = 'Likes to play so wild and recklessly that s/he might get hurt.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq11 = list( Description = 'Seems to be at ease with almost any person.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq12 = list( Description = 'Tends to run rather than walk from room to room.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq13 = list( Description = 'Notices it when parents are wearing new clothing.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq14 = list( Description = 'Has temper tantrums when s/he doesn\'t get what s/he wants.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq15 = list( Description = 'Gets very enthusiastic about the things s/he does.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq16 = list( Description = 'When practicing an activity, has a hard time keeping her/his mind on it.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq17 = list( Description = 'Is afraid of burglars or the "boogie man."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq18 = list( Description = 'When outside, often sits quietly.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq19 = list( Description = 'Enjoys funny stories but usually doesn\'t laugh at them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq20 = list( Description = 'Tends to become sad if the family\'s plans don\'t work out.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq21 = list( Description = 'Will move from one task to another without completing any of them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq22 = list( Description = 'Moves about actively (runs, climbs, jumps) when playing in the house.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq23 = list( Description = 'Is afraid of loud noises.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq24 = list( Description = 'Seems to listen to even quiet sounds.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq25 = list( Description = 'Has a hard time settling down after an exciting activity.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq26 = list( Description = 'Enjoys taking warm baths.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq27 = list( Description = 'Seems to feel depressed when unable to accomplish some task.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq28 = list( Description = 'Often rushes into new situations.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq29 = list( Description = 'Is quite upset by a little cut or bruise.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq30 = list( Description = 'Gets quite frustrated when prevented from doing something s/he wants to do.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq31 = list( Description = 'Becomes upset when loved relatives or friends are getting ready to leave following a visit.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq32 = list( Description = 'Comments when a parent has changed his/her appearance.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq33 = list( Description = 'Enjoys activities such as being chased, spun around by the arms, etc.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq34 = list( Description = 'When angry about something, s/he tends to stay upset for ten minutes or longer.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq35 = list( Description = 'Is not afraid of the dark.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq36 = list( Description = 'Takes a long time in approaching new situations.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq37 = list( Description = 'Is sometimes shy even around people s/he has known for a long time.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq38 = list( Description = 'Can wait before entering into new activities if s/he is asked to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq39 = list( Description = 'Enjoys "snuggling up" net to a parent or babysitter."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq40 = list( Description = 'Gets angry when s/he can\'t find something s/he wants to play with.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq41 = list( Description = 'Is afraid of fire.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq42 = list( Description = 'Sometimes seems nervous when talking to adults s/he has just met.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq43 = list( Description = 'Is slow and unhurried in deciding what to do next.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq44 = list( Description = 'Changes from being upset to feeling much better within a few minutes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq45 = list( Description = 'Prepares for trips and outings by planning things s/he will need.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq46 = list( Description = 'Becomes very excited while planning for trips.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq47 = list( Description = 'Is quickly aware of some new item in the living room.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq48 = list( Description = 'Hardly ever laughs out loud during play with other children.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq49 = list( Description = 'Is not very upset at minor cuts or bruises.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq50 = list( Description = 'Prefers quiet activities to active games.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq51= list( Description = 'Tends to say the first thing that comes to mind, without stopping to think about it.',
                 Levels = list ('0' =	'extremely untrue of your child',
                                '1'	= 'quite untrue of your child',
                                '2' =	'slightly untrue of your child',
                                '3'	= 'neither true nor false of your child',
                                '4'	= 'slightly true of your child',
                                '5'	= 'quite true of your child',
                                '6'	= 'extremely true of your child',
                                '7' = 'N/A')),
    cbq52 = list( Description = 'Acts shy around new people.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq53 = list( Description = 'Has trouble sitting still when s/he is told to (at movies, church, etc.).',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq54 = list( Description = 'Rarely cries when s/he hears a sad story.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq55 = list( Description = 'Sometimes smiles or giggles playing by her/himself.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq56 = list( Description = 'Rarely becomes upset when watching a sad event in a TV show.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq57 = list( Description = 'Enjoys just being talked to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq58 = list( Description = 'Becomes very excited before an outing (e.g., picnic, party).',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq59 = list( Description = 'If upset, cheers up quickly when s/he thinks about something else.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq60 = list( Description = 'Is comfortable asking other children to play.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq61 = list( Description = 'Rarely gets upset when told s/he has to go to bed.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq62 = list( Description = 'When drawing or coloring in a book, shows strong concentration.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq63 = list( Description = 'Is afraid of the dark.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq64 = list( Description = 'Is likely to cry when even a little bit hurt.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq65 = list( Description = 'Enjoys looking at picture books.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq66 = list( Description = 'Is easy to soothe when s/he is upset.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq67 = list( Description = 'Is good at following instructions.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq68 = list( Description = 'Is rarely frightened by "monsters" seen on TV or at movies.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq69 = list( Description = 'Likes to go high and fast when pushed on a swing.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq70 = list( Description = 'Sometimes turns away shyly from new acquaintances.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq71 = list( Description = 'When building or putting something together, becomes very involved in what s/he is doing, and works for long periods.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq72 = list( Description = 'Likes being sung to.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq73 = list( Description = 'Approaches places s/he has been told are dangerous slowly and cautiously.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq74 = list( Description = 'Rarely becomes discouraged when s/he has trouble making something work.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq75 = list( Description = 'Is very difficult to soothe when s/he has become upset.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq76 = list( Description = 'Likes the sound of words, such as nursery rhymes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq77 = list( Description = 'Smiles a lot at people s/he likes.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq78 = list( Description = 'Dislikes rough and rowdy games.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq79 = list( Description = 'Often laughs out loud in play with other children.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq80 = list( Description = 'Rarely laughs aloud while watching TV or movie comedies.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq81 = list( Description = 'Can easily stop an activity when s/he is told "no."',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq82 = list( Description = 'Is among the last children to try out a new activity.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq83 = list( Description = 'Doesn\'t usually notice odors such as perfume, smoke, cooking, etc.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq84 = list( Description = 'Is easily distracted when listening to a story.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq85 = list( Description = 'Is full of energy, even in the evening.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq86 = list( Description = 'Enjoys sitting on parent\'s lap.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq87 = list( Description = 'Gets angry when called in from play before s/he is ready to quit.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq88 = list( Description = 'Enjoys riding a tricycle or bicycle fast and recklessly.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq89 = list( Description = 'Sometimes becomes absorbed in a picture book and looks at if for a long time.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq90 = list( Description = 'Remains pretty calm about upcoming desserts like ice cream.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq91 = list( Description = 'Hardly ever complains when ill with a cold.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq92 = list( Description = 'Looks forward to family outings, but does not get too excited about them.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq93 = list( Description = 'Likes to sit quietly and watch people do things.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq94 = list( Description = 'Enjoys gentle rhythmic activities, such as rocking or swaying.',
                  Levels = list ('0' =	'extremely untrue of your child',
                                 '1'	= 'quite untrue of your child',
                                 '2' =	'slightly untrue of your child',
                                 '3'	= 'neither true nor false of your child',
                                 '4'	= 'slightly true of your child',
                                 '5'	= 'quite true of your child',
                                 '6'	= 'extremely true of your child',
                                 '7' = 'N/A')),
    cbq_inhibit = list( Description = 'Inhibition',
                        Derivative = TRUE),
    cbq_inhibit_t = list( Description = 'Inhibition T-score',
                          Derivative = TRUE),
    cbq_inhibit_p = list( Description = 'Inhibition Percentile',
                          Derivative = TRUE),
    cbq_selfmon = list( Description = 'Self-Monitoring',
                        Derivative = TRUE),
    cbq_selfmon_t = list( Description = 'Self-Monitoring T-score',
                          Derivative = TRUE),
    cbq_selfmon_p = list( Description = 'Self-Monitoring Percentile',
                          Derivative = TRUE),
    cbq_shift = list( Description = 'Shifting',
                      Derivative = TRUE),
    cbq_shift_t = list( Description = 'Shifting T-score',
                        Derivative = TRUE),
    cbq_shift_p = list( Description = 'Shifting Percentile',
                        Derivative = TRUE),
    cbq_emcont = list( Description = 'Emotional Control',
                       Derivative = TRUE),
    cbq_emcont_t = list( Description = 'Emotional Control T-score',
                         Derivative = TRUE),
    cbq_emcont_p = list( Description = 'Emotional Control Percentile',
                         Derivative = TRUE),
    cbq_initiate = list( Description = 'Initiate',
                         Derivative = TRUE),
    cbq_initiate_t = list( Description = 'Initiate T-score',
                           Derivative = TRUE),
    cbq_initiate_p = list( Description = 'Initiate Percentile',
                           Derivative = TRUE),
    cbq_wm = list( Description = 'Working Memory',
                   Derivative = TRUE),
    cbq_wm_t = list( Description = 'Working Memory T-score',
                     Derivative = TRUE),
    cbq_wm_p = list( Description = 'Working Memory Percentile',
                     Derivative = TRUE),
    cbq_planorg = list( Description = 'Planning/Organization',
                        Derivative = TRUE),
    cbq_planorg_t = list( Description = 'Planning/Organization T-score',
                          Derivative = TRUE),
    cbq_planorg_p = list( Description = 'Planning/Organization Percentile',
                          Derivative = TRUE),
    cbq_taskmon = list( Description = 'Task Monitoring',
                        Derivative = TRUE),
    cbq_taskmon_t = list( Description = 'Task Monitoring T-score',
                          Derivative = TRUE),
    cbq_taskmon_p = list( Description = 'Task Monitoring Percentile',
                          Derivative = TRUE),
    cbq_orgmat = list( Description = 'Organiation of Materials',
                       Derivative = TRUE),
    cbq_orgmat_t = list( Description = 'Organiation of Materials T-score',
                         Derivative = TRUE),
    cbq_orgmat_p = list( Description = 'Organiation of Materials Percentile',
                         Derivative = TRUE),
    cbq_bri = list( Description = 'Behavioral Regulation Index',
                    Derivative = TRUE),
    cbq_bri_t = list( Description = 'Behavioral Regulation Index T-score',
                      Derivative = TRUE),
    cbq_bri_p = list( Description = 'Behavioral Regulation Index Percentile',
                      Derivative = TRUE),
    cbq_eri = list( Description = 'Emotional Regulaiton Index',
                    Derivative = TRUE),
    cbq_eri_t = list( Description = 'Emotional Regulaiton Index T-score',
                      Derivative = TRUE),
    cbq_eri_p = list( Description = 'Emotional Regulaiton Index Percentile',
                      Derivative = TRUE),
    cbq_cri = list( Description = 'Cognitive Regulation Index',
                    Derivative = TRUE),
    cbq_cri_t = list( Description = 'Cognitive Regulation Index T-score',
                      Derivative = TRUE),
    cbq_cri_p = list( Description = 'Cognitive Regulation Index Percentile',
                      Derivative = TRUE),
    cbq_gec = list( Description = 'General Executive Composite',
                    Derivative = TRUE),
    cbq_gec_t = list( Description = 'General Executive Composite T-score',
                      Derivative = TRUE),
    cbq_gec_p = list( Description = 'General Executive Composite Percentile',
                      Derivative = TRUE),
    cbq_negativity = list( Description = 'Negativity Check',
                           Derivative = TRUE),
    cbq_negativity_p = list( Description = 'Negativity Check Percentile',
                             Derivative = TRUE),
    cbq_negativity_cat = list( Description = 'Negativity Check Category',
                               Levels = list ('0' = '<=98',
                                              '1' = '99',
                                              '2' = '>99'),
                               Derivative = TRUE),
    cbq_inconsistency = list( Description = 'Inconsistency Check',
                              Derivative = TRUE),
    cbq_inconsistency_p = list( Description = 'Inconsistency Check Percentile',
                                Derivative = TRUE),
    cbq_inconsistency_cat = list( Description = 'Inconsistency Check Category',
                                  Levels = list ('0' = '<=98',
                                                 '1' = '99',
                                                 '2' = '>99'),
                                  Derivative = TRUE),
    cbq_infrequency = list( Description = 'Infrequency',
                            Derivative = TRUE),
    cbq_infrequency_p = list( Description = 'Infrequency Percentile',
                              Derivative = TRUE),
    cbq_infrequency_cat = list( Description = 'Infrequency Category',
                                Levels = list ('0' = 'Acceptable',
                                               '1' = 'Questionable'),
                                Derivative = TRUE))


  # convert formatting to JSON
  cbq_json <- RJSONIO::toJSON(cbq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cbq_json, asText = TRUE))){
    print('cbq JSON file may be invalid')
  }

  return(cbq_json)

}
