#' json_hfi: Generates a json file for the Fulkerson Home Food Inventory
#'
#' This function generates a json file for the scored Fulkerson Home Food Inventory and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Fulkerson Home Food Inventory
#'
#'
#' @export

json_hfi <- function() {

  hfi_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Fulkerson Home Food Inventory. Participants were provided the following instructions: "Think about the areas in your home where your household stores food, including the refrigerator, freezer, pantries, cupboards, and other storage areas (list follows in that order). Please check "yes" or "no" to each of the food product/item/category below. Check "yes" to a food product/item/category if it is present anywhere in your home (opened or unopened) as you are completing this form. Check "no" to a food product/item/category if it is not present anywhere in your home as you are completing this form. Lower fat products will be labeled as "reduced-fat," "low-fat," "light," "nonfat," or "skim" on product and can be interchangeable"',
      Reference = 'Fulkerson JA, Nelson MC, Lytle LA, Moe S, Heitzler C, Pasch KE. The validation of a home food inventory. International Journal of Behavioral Nutrition and Physical Activity, 2008, 5;55',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/18983668/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),
    hfi_date = list( Description = 'Today\'s Date.'),
    hfi_cheese_a = list( Description = 'Shredded or block regular cheese (e.g.: American, cheddar)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_b = list( Description = 'Sliced regular cheese (e.g.: American, cheddar)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_c = list( Description = 'Shredded or block of reduced-fat cheese (e.g.: low fat cheddar)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_d = list( Description = 'Sliced reduced-fat cheese (e.g.: low fat cheddar, low fat swiss)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_e = list( Description = 'String cheese',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_f = list( Description = 'Mozzarella cheese',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_g = list( Description = 'Regular ricotta or cottage cheese (minimum of 4% fat)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_h = list( Description = 'Reduced -fat ricotta or cottage cheese (2% or low fat on label)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_i = list( Description = 'Regular cream cheese',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_j = list( Description = 'Reduced-fat cream cheese or neufchatel',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_cheese_k = list( Description = 'Cheez Whiz, Velveeta, canned cheese or other similar cheese',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_dairy_a = list( Description = 'Skim milk',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_b = list( Description = '1% or 2% low fat milk',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_c = list( Description = 'Whole milk',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_d = list( Description = 'Half and half, whipping cream or heavy cream',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_e = list( Description = 'Sour cream or sour cream/cheese dips',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_f = list( Description = 'Reduced-fat sour or low fat sour cream/cheese dips',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_g = list( Description = 'Chocolate or flavored milk',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_h = list( Description = 'Reduced-fat yogurt (with or without fruit)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_i = list( Description = 'Regular yogurt (made from whole milk, with or without fruit)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_dairy_j = list( Description = 'Reduced-fat yogurt drinks',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_extra_nondairy = list( Description = 'Other milks (nut milk, oat milk)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_oils_a = list( Description = 'Regular butter',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_b = list( Description = 'Light butter',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_c = list( Description = 'Regular margarine or butter substitute',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_d = list( Description = 'Light margarine or butter substitute',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_e = list( Description = 'Olive oil',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_f = list( Description = 'Vegetable oil (e.g.: canola oil, corn oil)',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_g = list( Description = 'Seed oil (e.g.: sunflower oil, sesame oil)',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_oils_h = list( Description = 'Lard or shortening',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_dressing_a = list( Description = 'Regular dressing (e.g., blue cheese dressing, Caesar, ranch)',
                           Levels = list ('0' =	'No',
                                          '1'	= 'Yes')),
    hfi_dressing_b = list( Description = 'Light/reduced fat dressing (e.g.: light blue cheese, light Italian)',
                           Levels = list ('0' =	'No',
                                          '1'	= 'Yes')),
    hfi_cond_a = list( Description = 'Regular mayonnaise',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_cond_b = list( Description = 'Light/reduced fat mayonnaise',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_cond_c = list( Description = 'Miracle Whip or other sandwich spread',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_cond_d = list( Description = 'Mustard or ketchup',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_6 = list( Description = 'How many other types of condiments (e.g., BBQ sauce, horseradish sauce, tartar sauce, steak sauce) do you estimate you have in your home?',
                       Levels = list ('0' =	'None',
                                      '1'	= '1-5',
                                      '2' = '6-10',
                                      '3' = 'More than 10')),
    hfi_veg_a = list( Description = 'Asparagus',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_a_type0 = list( Description = 'Asparagus: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_a_type1 = list( Description = 'Asparagus: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_a_type2 = list( Description = 'Asparagus: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_b = list( Description = 'Beets',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_b_type0 = list( Description = 'Beets: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_b_type1 = list( Description = 'Beets: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_b_type2 = list( Description = 'Beets: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_c = list( Description = 'Bell Peppers (e.g., green, red)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_c_type0 = list( Description = 'Bell Peppers (e.g., green, red): Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_c_type1 = list( Description = 'Bell Peppers (e.g., green, red): Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_c_type2 = list( Description = 'Bell Peppers (e.g., green, red): Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_d = list( Description = 'Broccoli',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_d_type0 = list( Description = 'Broccoli: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_d_type1 = list( Description = 'Broccoli: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_d_type2 = list( Description = 'Broccoli: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_e = list( Description = 'Cabbage',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_e_type0 = list( Description = 'Cabbage: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_e_type1 = list( Description = 'Cabbage: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_e_type2 = list( Description = 'Cabbage: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_f = list( Description = 'Cauliflower',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_f_type0 = list( Description = 'Cauliflower: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_f_type1 = list( Description = 'Cauliflower: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_f_type2 = list( Description = 'Cauliflower: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_g = list( Description = 'Carrots',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_g_type0 = list( Description = 'Carrots: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_g_type1 = list( Description = 'Carrots: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_g_type2 = list( Description = 'Carrots: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_h = list( Description = 'Celery',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_h_type0 = list( Description = 'Celery: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_h_type1 = list( Description = 'Celery: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_h_type2 = list( Description = 'Celery: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_i = list( Description = 'Corn',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_i_type0 = list( Description = 'Corn: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_i_type1 = list( Description = 'Corn: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_i_type2 = list( Description = 'Corn: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_j = list( Description = 'Cucumbers',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_j_type0 = list( Description = 'Cucumbers: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_j_type1 = list( Description = 'Cucumbers: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_j_type2 = list( Description = 'Cucumbers: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_k = list( Description = 'Green beans',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_k_type0 = list( Description = 'Green beans: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_k_type1 = list( Description = 'Green beans: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_k_type2 = list( Description = 'Green beans: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_l = list( Description = 'Lettuce (e.g.: romaine, endive)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_l_type0 = list( Description = 'Lettuce (e.g.: romaine, endive): Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_l_type1 = list( Description = 'Lettuce (e.g.: romaine, endive): Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_l_type2 = list( Description = 'Lettuce (e.g.: romaine, endive): Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_m = list( Description = 'Mushrooms',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_m_type0 = list( Description = 'Mushrooms: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_m_type1 = list( Description = 'Mushrooms: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_m_type2 = list( Description = 'Mushrooms: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_n = list( Description = 'Peas',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_n_type0 = list( Description = 'Peas: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_n_type1 = list( Description = 'Peas: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_n_type2 = list( Description = 'Peas: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_o = list( Description = 'Potatoes',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_o_type0 = list( Description = 'Potatoes: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_o_type1 = list( Description = 'Potatoes: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_o_type2 = list( Description = 'Potatoes: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_p = list( Description = 'Spinach/other greens (collard)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_p_type0 = list( Description = 'Spinach/other greens (collard): Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_p_type1 = list( Description = 'Spinach/other greens (collard): Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_p_type2 = list( Description = 'Spinach/other greens (collard): Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_q = list( Description = 'Squash (e.g.: butternut, zucchini)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_q_type0 = list( Description = 'Squash (e.g.: butternut, zucchini): Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_q_type1 = list( Description = 'Squash (e.g.: butternut, zucchini): Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_q_type2 = list( Description = 'Squash (e.g.: butternut, zucchini): Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_r = list( Description = 'Sweet Potatoes',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_r_type0 = list( Description = 'Sweet Potatoes: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_r_type1 = list( Description = 'Sweet Potatoes: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_r_type2 = list( Description = 'Sweet Potatoes: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_s = list( Description = 'Tomatoes',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_s_type0 = list( Description = 'Tomatoes: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_s_type1 = list( Description = 'Tomatoes: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_s_type2 = list( Description = 'Tomatoes: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_t = list( Description = 'Mixed vegetables',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_veg_t_type0 = list( Description = 'Mixed vegetables: Fresh',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_t_type1 = list( Description = 'Mixed vegetables: Can/Jar',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_veg_t_type2 = list( Description = 'Mixed vegetables: Frozen',
                            Levels = list ('0' =	'No',
                                           '1'	= 'Yes')),
    hfi_fruit_a = list( Description = 'Apples',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_a_type0 = list( Description = 'Apples: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_a_type1 = list( Description = 'Apples: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_a_type2 = list( Description = 'Apples: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_a_type3 = list( Description = 'Apples: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_b = list( Description = 'Apple sauce',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_b_type0 = list( Description = 'Apple sauce: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_b_type1 = list( Description = 'Apple sauce: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_b_type2 = list( Description = 'Apple sauce: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_b_type3 = list( Description = 'Apple sauce: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_c = list( Description = 'Apricots',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_c_type0 = list( Description = 'Apricots: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_c_type1 = list( Description = 'Apricots: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_c_type2 = list( Description = 'Apricots: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_c_type3 = list( Description = 'Apricots: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_d = list( Description = 'Avocado',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_d_type0 = list( Description = 'Avocado: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_d_type1 = list( Description = 'Avocado: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_d_type2 = list( Description = 'Avocado: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_d_type3 = list( Description = 'Avocado: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_e = list( Description = 'Bananas',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_e_type0 = list( Description = 'Bananas: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_e_type1 = list( Description = 'Bananas: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_e_type2 = list( Description = 'Bananas: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_e_type3 = list( Description = 'Bananas: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_f = list( Description = 'Blueberries',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_f_type0 = list( Description = 'Blueberries: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_f_type1 = list( Description = 'Blueberries: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_f_type2 = list( Description = 'Blueberries: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_f_type3 = list( Description = 'Blueberries: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_g = list( Description = 'Cranberries',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_g_type0 = list( Description = 'Cranberries: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_g_type1 = list( Description = 'Cranberries: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_g_type2 = list( Description = 'Cranberries: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_g_type3 = list( Description = 'Cranberries: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_h = list( Description = 'Dates',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_h_type0 = list( Description = 'Dates: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_h_type1 = list( Description = 'Dates: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_h_type2 = list( Description = 'Dates: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_h_type3 = list( Description = 'Dates: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_i = list( Description = 'Grapes (red or green)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_i_type0 = list( Description = 'Grapes (red or green): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_i_type1 = list( Description = 'Grapes (red or green): Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_i_type2 = list( Description = 'Grapes (red or green): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_i_type3 = list( Description = 'Grapes (red or green): Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_j = list( Description = 'Grapefruit',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_j_type0 = list( Description = 'Grapefruit: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_j_type1 = list( Description = 'Grapefruit: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_j_type2 = list( Description = 'Grapefruit: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_j_type3 = list( Description = 'Grapefruit: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_k = list( Description = 'Kiwi',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_k_type0 = list( Description = 'Kiwi: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_k_type1 = list( Description = 'Kiwi: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_k_type2 = list( Description = 'Kiwi: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_k_type3 = list( Description = 'Kiwi: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_l = list( Description = 'Lemons or limes',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_l_type0 = list( Description = 'Lemons or limes: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_l_type1 = list( Description = 'Lemons or limes: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_l_type2 = list( Description = 'Lemons or limes: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_l_type3 = list( Description = 'Lemons or limes: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_m = list( Description = 'Mango',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_m_type0 = list( Description = 'Mango: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_m_type1 = list( Description = 'Mango: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_m_type2 = list( Description = 'Mango: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_m_type3 = list( Description = 'Mango: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_n = list( Description = 'Melons (e.g.: watermelon)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_n_type0 = list( Description = 'Melons (e.g.: watermelon): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_n_type1 = list( Description = 'Melons (e.g.: watermelon): Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_n_type2 = list( Description = 'Melons (e.g.: watermelon): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_n_type3 = list( Description = 'Melons (e.g.: watermelon): Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_o = list( Description = 'Mixed fruit/fruit cocktail',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_o_type0 = list( Description = 'Mixed fruit/fruit cocktail: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_o_type1 = list( Description = 'Mixed fruit/fruit cocktail: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_o_type2 = list( Description = 'Mixed fruit/fruit cocktail: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_o_type3 = list( Description = 'Mixed fruit/fruit cocktail: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_p = list( Description = 'Nectarines',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_p_type0 = list( Description = 'Nectarines: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_p_type1 = list( Description = 'Nectarines: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_p_type2 = list( Description = 'Nectarines: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_p_type3 = list( Description = 'Nectarines: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_q = list( Description = 'Oranges',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_q_type0 = list( Description = 'Oranges: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_q_type1 = list( Description = 'Oranges: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_q_type2 = list( Description = 'Oranges: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_q_type3 = list( Description = 'Oranges: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_r = list( Description = 'Pears',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_r_type0 = list( Description = 'Pears: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_r_type1 = list( Description = 'Pears: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_r_type2 = list( Description = 'Pears: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_r_type3 = list( Description = 'Pears: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_s = list( Description = 'Peaches',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_s_type0 = list( Description = 'Peaches: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_s_type1 = list( Description = 'Peaches: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_s_type2 = list( Description = 'Peaches: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_s_type3 = list( Description = 'Peaches: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_t = list( Description = 'Pineapple',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_t_type0 = list( Description = 'Pineapple: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_t_type1 = list( Description = 'Pineapple: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_t_type2 = list( Description = 'Pineapple: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_t_type3 = list( Description = 'Pineapple: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_u = list( Description = 'Plums',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_u_type0 = list( Description = 'Plums: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_u_type1 = list( Description = 'Plums: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_u_type2 = list( Description = 'Plums: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_u_type3 = list( Description = 'Plums: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_v = list( Description = 'Prunes',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_v_type0 = list( Description = 'Prunes: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_v_type1 = list( Description = 'Prunes: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_v_type2 = list( Description = 'Prunes: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_v_type3 = list( Description = 'Prunes: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_w = list( Description = 'Raisins',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_w_type0 = list( Description = 'Raisins: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_w_type1 = list( Description = 'Raisins: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_w_type2 = list( Description = 'Raisins: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_w_type3 = list( Description = 'Raisins: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_x = list( Description = 'Raspberries',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_x_type0 = list( Description = 'Raspberries: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_x_type1 = list( Description = 'Raspberries: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_x_type2 = list( Description = 'Raspberries: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_x_type3 = list( Description = 'Raspberries: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_y = list( Description = 'Strawberries',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_y_type0 = list( Description = 'Strawberries: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_y_type1 = list( Description = 'Strawberries: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_y_type2 = list( Description = 'Strawberries: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_y_type3 = list( Description = 'Strawberries: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_z = list( Description = 'Tangerines/clementines',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_fruit_z_type0 = list( Description = 'Tangerines/clementines: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_z_type1 = list( Description = 'Tangerines/clementines: Can/Jar',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_z_type2 = list( Description = 'Tangerines/clementines: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_fruit_z_type3 = list( Description = 'Tangerines/clementines: Dried',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_deli_a = list( Description = 'Sliced turkey or chicken deli meat',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_deli_b = list( Description = 'Sliced ham, roast beef',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_deli_c = list( Description = 'Bologna',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_deli_d = list( Description = 'Salami, summer sausage, pepperoni',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_deli_e = list( Description = 'Bacon, breakfast sausage',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_deli_f = list( Description = 'Hot dogs, bratwurst, polish sausage',
                       Levels = list ('0' =	'No',
                                      '1'	= 'Yes')),
    hfi_protein_a = list( Description = 'Chicken/turkey (e.g.: burgers, breasts, whole)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_b = list( Description = 'Beef, pork, lamb (e.g.: burgers, steaks, roasts, chops)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_c = list( Description = 'Tofu, seitan, tempe, textured vegetable protein (TVP)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_d = list( Description = 'Veggie burgers',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_e = list( Description = 'Fish (e.g., canned, packet, fresh or frozen tuna, salmon, cod)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_f = list( Description = 'Shellfish (e.g.: shrimp, scallops, crab)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_g = list( Description = 'Lentils',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_h = list( Description = 'Beans (e.g.: black beans, pinto beans, kidney beans)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_i = list( Description = 'Peanut butter or other nut butter',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_protein_j = list( Description = 'Eggs',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_frozen_a = list( Description = 'Regular ice cream (any flavor)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_b = list( Description = 'Reduced-fat ice cream (any flavor)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_c = list( Description = 'Frozen yogurt (any flavor)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_d = list( Description = 'Frozen treats made with ice cream or pudding',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_e = list( Description = 'Frozen treats made with ice milk, frozen yogurt, sherbet, sorbet',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_f = list( Description = 'Frozen fruit juice bars',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_frozen_g = list( Description = 'Frozen soy or rice desserts',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_quick_a = list( Description = 'Pizza (any variety)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_b = list( Description = 'Hot Pockets (any flavor)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_c = list( Description = 'Pizza rolls or bagel snacks (any flavor)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_d = list( Description = 'Burritos or other Mexican snacks',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_e = list( Description = 'Chicken nuggets',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_f = list( Description = 'French fries or tater tots',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_g = list( Description = 'Egg rolls',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_quick_h = list( Description = 'Ramen noodles',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_a = list( Description = 'Wheat bread/rolls',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_a_type0 = list( Description = 'Wheat bread/rolls: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_a_type1 = list( Description = 'Wheat bread/rolls: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_b = list( Description = 'White bread/rolls (e.g.: baguette)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_b_type0 = list( Description = 'White bread/rolls (e.g.: baguette): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_b_type1 = list( Description = 'White bread/rolls (e.g.: baguette): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_c = list( Description = 'English muffins (wheat)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_c_type0 = list( Description = 'English muffins (wheat): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_c_type1 = list( Description = 'English muffins (wheat): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_d = list( Description = 'English muffins (white)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_d_type0 = list( Description = 'English muffins (white): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_d_type1 = list( Description = 'English muffins (white): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_e = list( Description = 'Bagels (wheat)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_e_type0 = list( Description = 'Bagels (wheat): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_e_type1 = list( Description = 'Bagels (wheat): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_f = list( Description = 'Bagels (white, any flavor)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_f_type0 = list( Description = 'Bagels (white, any flavor): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_f_type1 = list( Description = 'Bagels (white, any flavor): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_g = list( Description = 'Tortillas (wheat, sprout)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_g_type0 = list( Description = 'Tortillas (wheat, sprout): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_g_type1 = list( Description = 'Tortillas (wheat, sprout): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_h = list( Description = 'Tortillas (flour, any flavors)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_h_type0 = list( Description = 'Tortillas (flour, any flavors): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_h_type1 = list( Description = 'Tortillas (flour, any flavors): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_i = list( Description = 'Tortillas (corn)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_i_type0 = list( Description = 'Tortillas (corn): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_i_type1 = list( Description = 'Tortillas (corn): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_j = list( Description = 'Pita bread (wheat, sprout)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_j_type0 = list( Description = 'Pita bread (wheat, sprout): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_j_type1 = list( Description = 'Pita bread (wheat, sprout): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_k = list( Description = 'Pita bread (white, any flavor)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_k_type0 = list( Description = 'Pita bread (white, any flavor): Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_k_type1 = list( Description = 'Pita bread (white, any flavor): Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_l = list( Description = 'Croissants',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_bread_l_type0 = list( Description = 'Croissants: Fresh',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_bread_l_type1 = list( Description = 'Croissants: Frozen',
                              Levels = list ('0' =	'No',
                                             '1'	= 'Yes')),
    hfi_dessert_a = list( Description = 'Regular cookies (any flavor/variety)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_a_type0 = list( Description = 'Regular cookies (any flavor/variety): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_a_type1 = list( Description = 'Regular cookies (any flavor/variety): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_b = list( Description = 'Reduced-fat cookies (any flavor/variety)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_b_type0 = list( Description = 'Reduced-fat cookies (any flavor/variety): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_b_type1 = list( Description = 'Reduced-fat cookies (any flavor/variety): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_c = list( Description = 'Regular cake/cupcakes (any flavor)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_c_type0 = list( Description = 'Regular cake/cupcakes (any flavor): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_c_type1 = list( Description = ' Regular cake/cupcakes (any flavor): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_d = list( Description = 'Reduced-fat cake/cupcakes (any flavor)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_d_type0 = list( Description = 'Reduced-fat cake/cupcakes (any flavor): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_d_type1 = list( Description = 'Reduced-fat cake/cupcakes (any flavor): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_e = list( Description = 'Regular muffins (any flavor/variety)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_e_type0 = list( Description = 'Regular muffins (any flavor/variety): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_e_type1 = list( Description = 'Regular muffins (any flavor/variety): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_f = list( Description = 'Brownies/bars (any variety)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_f_type0 = list( Description = 'Brownies/bars (any variety): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_f_type1 = list( Description = 'Brownies/bars (any variety): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_g = list( Description = 'Other snack cakes (any variety)',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_g_type0 = list( Description = 'Other snack cakes (any variety): Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_g_type1 = list( Description = 'Other snack cakes (any variety): Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_h = list( Description = 'Pastry, sweet rolls, donuts ',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_dessert_h_type0 = list( Description = 'Pastry, sweet rolls, donuts : Store-bought',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_dessert_h_type1 = list( Description = 'Pastry, sweet rolls, donuts : Homemade',
                                Levels = list ('0' =	'No',
                                               '1'	= 'Yes')),
    hfi_snacks_a = list( Description = 'Whole grain snack crackers (labeled "whole grain" or "whole wheat", e.g.: Triscuit)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_b = list( Description = 'Regular snack crackers (e.g.: Saltines, Wheat Thins)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_c = list( Description = 'Reduced-fat snack crackers (e.g.: Reduced fat Wheat Thins)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_d = list( Description = 'Regular potato chips',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_e = list( Description = 'Reduced-fat potato chips (e.g.: Baked Lays)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_f = list( Description = 'Corn chips (e.g.: Fritos)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_g = list( Description = 'Tortilla chips',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_h = list( Description = 'Reduced-fat tortilla chips (e.g.: baked tortilla chips)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_i = list( Description = 'Cheese curls or puffs',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_j = list( Description = 'Reduced-fat cheese curls or puffs (e.g.: baked Cheetos)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_k = list( Description = 'Regular bagel chips',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_l = list( Description = 'Reduced-fat bagel chips',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_m = list( Description = 'Graham crackers',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_n = list( Description = 'Pretzels, any shape',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_o = list( Description = 'Popcorn (microwave bags or bags of prepared popcorn)',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_p = list( Description = 'Peanuts, cashews or other nuts',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_q = list( Description = 'Regular granola bars, sports bars',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_snacks_r = list( Description = 'Reduced-fat granola bars, sports bars',
                         Levels = list ('0' =	'No',
                                        '1'	= 'Yes')),
    hfi_16 = list( Description = 'Are any of the chips, crackers or other snacks checked above in prepackaged snack size or single size portions (do not count granola, sports bars, meal supplement bars)?',
                   Levels = list ('0' =	'No',
                                  '1'	= 'Yes')),
    hfi_17 = list( Description = 'How many ready-to-eat cereals do you have that are labeled "whole grain", "whole wheat" or have at least 3 grams of fiber per serving?',
                   Levels = list ('0' =	'None',
                                  '1'	= 'One',
                                  '2' = 'Two or three',
                                  '3' = 'Four or more')),
    hfi_18 = list( Description = 'How many ready-to-eat cereals indicate on the nutrition label that they have less than 6 grams of sugar per serving?',
                   Levels = list ('0' =	'None',
                                  '1'	= 'One',
                                  '2' = 'Two or three',
                                  '3' = 'Four or more')),
    hfi_19 = list( Description = 'How many ready-to-eat cereals indicate on the nutrition label that they have 6 or more grams of sugar per serving?',
                   Levels = list ('0' =	'None',
                                  '1'	= 'One',
                                  '2' = 'Two or three',
                                  '3' = 'Four or more')),
    hfi_beverage_a = list( Description = 'Regular soda pop (any variety, flavor)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_b = list( Description = 'Diet soda pop (any variety, flavor)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_c = list( Description = 'Prepared iced teas or lemonade (e.g., Snapple)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_d = list( Description = 'Prepared light iced teas or lemonade (e.g.: diet Snapple)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_e = list( Description = 'Sports drinks (e.g.: Gatorade)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_f = list( Description = '100% fruit juice (labeled as 100% juice)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_g = list( Description = 'Fruit drinks (e.g.: < 100% juice, Capri Sun)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_h = list( Description = 'Bottled water (unsweetened, any variety, flavor)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_beverage_i = list( Description = 'Soy milk, rice milk (any variety, flavor)',
                      Levels = list ('0' =	'No',
                                     '1'	= 'Yes')),
    hfi_candy_a = list( Description = 'Chocolate candy (any variety, except chocolate exclusively for baking)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_candy_b = list( Description = 'Hard candy',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_candy_c = list( Description = 'Gummis',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_candy_d = list( Description = 'Fruit rollups, fruit snacks or other fruit based candy',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_candy_e = list( Description = 'Chewy candy (e.g.: Skittles, caramel)',
                        Levels = list ('0' =	'No',
                                       '1'	= 'Yes')),
    hfi_accessible_a = list( Description = 'Fresh fruit',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_b = list( Description = 'Canned or dried fruit',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_c = list( Description = 'Fresh vegetables',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_d = list( Description = 'Regular snack crackers, pretzels, chips, popcorn',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_e = list( Description = 'Reduced-fat snack crackers, pretzels, chips, popcorn',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_f = list( Description = 'Dry cereal',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_g = list( Description = 'Bread or rolls',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_h = list( Description = 'Regular soda pop',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_i = list( Description = 'Diet soda pop',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_j = list( Description = 'Candy',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_k = list( Description = 'Regular cookies, cake, cupcakes, muffins',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_l = list( Description = 'Reduced-fat cookies, cake, cupcakes, muffins',
                          Levels = list ('0' =	'No',
                                         '1'	= 'Yes')),
    hfi_accessible_fridge_a = list( Description = 'Skim milk (any flavor)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_b = list( Description = '1% or 2% low fat milk (any flavor)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_c = list( Description = 'Whole milk (any flavor)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_extra_accessible_fridge = list( Description = 'Other milks (nut milk, oat milk)',
                                    Levels = list ('0' =	'No',
                                                   '1'	= 'Yes')),
    hfi_accessible_fridge_d = list( Description = '100 % fruit juice (any flavor)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_e = list( Description = 'Fruit drinks/sports drinks (not 100% juice)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_f = list( Description = 'Regular soda pop',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_g = list( Description = 'Diet soda pop',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_h = list( Description = 'Bottled/contained water',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_i = list( Description = 'Regular cheese (e.g.: American, cheddar, Swiss, parmesan)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_j = list( Description = 'Reduced-fat cheese (e.g.: low fat cheddar, low fat Swiss)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_k = list( Description = 'Reduced-fat yogurt (with or without fruit)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_l = list( Description = 'Regular yogurt (made from whole milk, with or without fruit)',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_m = list( Description = 'Reduced-fat yogurt drinks',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_n = list( Description = 'Fresh ready-to-eat vegetables',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_accessible_fridge_o = list( Description = 'Fresh ready-to-eat fruit',
                                 Levels = list ('0' =	'No',
                                                '1'	= 'Yes')),
    hfi_dairy = list( Description = 'Dairy',
                      Derivative = TRUE),
    hfi_dairy_highfat = list( Description = 'Dairy: high fat/regular fat items',
                              Derivative = TRUE),
    hfi_vegetables = list( Description = 'Vegetables',
                           Derivative = TRUE),
    hfi_veg_nopotato = list( Description = 'Vegetables: No Potatoes',
                             Derivative = TRUE),
    hfi_fruit = list( Description = 'Fruit',
                      Derivative = TRUE),
    hfi_meat_protein = list( Description = 'Meat/Protein',
                             Derivative = TRUE),
    hfi_meat_protein_processed = list( Description = 'Processed Meats',
                                       Derivative = TRUE),
    hfi_added_fat = list( Description = 'Added Fats',
                          Derivative = TRUE),
    hfi_added_fat_reg = list( Description = 'Added Fats: regular (i.e., not reduced fat)',
                              Derivative = TRUE),
    hfi_prepared_dessert = list( Description = 'Prepared Desserts',
                                 Derivative = TRUE),
    hfi_prepared_dessert_highfat = list( Description = 'Prepared Desserts: high fat/regular fat items',
                                         Derivative = TRUE),
    hfi_savory_snacks = list( Description = 'Savory Snacks',
                              Derivative = TRUE),
    hfi_savory_snacks_highfat = list( Description = 'Savory Snacks: high fat/regular fat items',
                                      Derivative = TRUE),
    hfi_bread = list( Description = 'Breads',
                      Derivative = TRUE),
    hfi_bread_wheat = list( Description = 'Breads: Wheat',
                            Derivative = TRUE),
    hfi_cereal = list( Description = 'Cereal',
                       Derivative = TRUE),
    hfi_cereal_highsugar = list( Description = 'Cereal: high sugar',
                                 Derivative = TRUE),
    hfi_candy = list( Description = 'Candy',
                      Derivative = TRUE),
    hfi_beverages = list( Description = 'Beverages',
                          Derivative = TRUE),
    hfi_bev_highsugar = list( Description = 'Beverages: high sugar/regular (not diet)',
                              Derivative = TRUE),
    hfi_microwave_quickfood = list( Description = 'Microwavable or quick foods',
                                    Derivative = TRUE),
    hfi_fridge_accessible = list( Description = 'Foods accessible/Accessible in Fridge',
                                  Derivative = TRUE),
    hfi_fridge_healthy = list( Description = 'Foods accessible/Accessible in Fridge: Healthy',
                               Derivative = TRUE),
    hfi_fridge_unhealthy = list( Description = 'Foods accessible/Accessible in Fridge: Unhealthy',
                                 Derivative = TRUE),
    hfi_kitchen_accessible = list( Description = 'Foods accessible/Accessible in Kitchen',
                                   Derivative = TRUE),
    hfi_kitchen_healthy = list( Description = 'Foods accessible/Accessible in Kitchen: Healthy',
                                Derivative = TRUE),
    hfi_kitchen_unhealthy = list( Description = 'Foods accessible/Accessible in Kitchen: Unhealthy',
                                  Derivative = TRUE),
    hfi_obesogenic_foods = list( Description = 'Obesogenic foods (out of 71)',
                                 Derivative = TRUE))


  # convert formatting to JSON
  hfi_json <- RJSONIO::toJSON(hfi_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(hfi_json, asText = TRUE))){
    print('Fulkerson hfi (hfi) JSON file may be invalid')
  }

  return(hfi_json)

}
