#' json_cebq: Generates a json file for the Children\'s Eating Behavior Questionnaire
#'
#' This function generates a json file for the scored Children\'s Eating Behavior Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_cebq function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the Children\'s Eating Behavior Questionnaire
#'
#'
#' @export

json_cebq <- function() {

  cebq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Children\'s Eating Behavior Questionnaire. Participants were provided the following instructions: "Please read the following statements and tick the boxes most appropriate to your child\'s eating behavior."',
      Reference = 'Wardle, J., Guthrie, C. A., Sanderson, S., & Rapoport, L. (2001). Development of the children\'s eating behaviour questionnaire. Journal of Child Psychology and Psychiatry, 42, 963 to 970. https://doi.org/10.1017/S0021963001007727',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/11693591/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                    Levels = list ('ses-1' = 'session 1 / baseline',
                                   'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date (YYYY-MM-DD) of visit this parent report survey was completed'),
    cebq1 = list( Description = 'My child loves food',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq2 = list( Description = 'My child eats more when worried',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq3 = list( Description = 'My child has a big appetite',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq4 = list( Description = 'My child finishes his/her meal quickly',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq5 = list( Description = 'My child is interested in food',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq6 = list( Description = 'My child is always asking for a drink',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq7 = list( Description = 'My child refuses new foods at first',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq8 = list( Description = 'My child eats slowly',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq9 = list( Description = 'My child eats less when angry',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    cebq10 = list( Description = 'My child enjoys tasting new foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq11 = list( Description = 'My child eats less when s/he is tired',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq12 = list( Description = 'My child is always asking for food',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq13 = list( Description = 'My child eats more when annoyed',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq14 = list( Description = 'If allowed to, my child would eat too much',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq15 = list( Description = 'My child eats more when anxious',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq16 = list( Description = 'My child enjoys a wide variety of foods',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq17 = list( Description = 'My child leaves food on his/her plate at the end  of a meal',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq18 = list( Description = 'My child takes more than 30 minutes to finish a  meal',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq19 = list( Description = 'Given the choice, my child would eat most of the time',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq20 = list( Description = 'My child looks forward to mealtimes',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq21 = list( Description = 'My child gets full before his/her meal is finished',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq22 = list( Description = 'My child enjoys eating',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq23 = list( Description = 'My child eats more when he/she is happy',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq24 = list( Description = 'My child is difficult to please with meals',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq25 = list( Description = 'My child eats less when upset',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq26 = list( Description = 'My child gets full up easily',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq27 = list( Description = 'My child eats more when s/he has nothing else to do',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq28 = list( Description = 'Even if my child is full up s/he finds room to eat  his/her favorite food',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq29 = list( Description = 'If given the chance, my child would drink continuously throughout the day',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq30 = list( Description = 'My child cannot eat a meal if s/he has had a snack just before',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq31 = list( Description = 'If given the chance, my child would always be having a drink',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq32 = list( Description = 'My child is interested in tasting food s/he hasn\'t tasted before',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq33 = list( Description = 'My child decides that s/he doesn\'t like a food, even without tasting it',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq34 = list( Description = 'If given the chance, my child would always have food in his/her mouth',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq35 = list( Description = 'My child eats more and more slowly during the course of a meal',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    cebq_fr = list( Description = 'Food responsiveness.',
                    Derivative = TRUE),
    cebq_eoe = list( Description = 'Emotional overeating.',
                     Derivative = TRUE),
    cebq_ef = list( Description = 'Enjoyment of food.',
                    Derivative = TRUE),
    cebq_dd = list( Description = 'Desire to drink.',
                    Derivative = TRUE),
    cebq_sr = list( Description = 'Satiety responsiveness.',
                    Derivative = TRUE),
    cebq_se = list( Description = 'Slowness in eating.',
                    Derivative = TRUE),
    cebq_eue = list( Description = 'Emotional under eating.',
                     Derivative = TRUE),
    cebq_ff = list( Description = 'Food fussiness.',
                    Derivative = TRUE),
    cebq_approach = list( Description = 'Food approach.',
                          Derivative = TRUE),
    cebq_avoid = list( Description = 'Food avoidance.',
                       Derivative = TRUE),
    cebq_rbe = list( Description = 'Reward-based eating.',
                     Derivative = TRUE,
                     Reference = 'Manzano MA, Strong DR, Kang Sim DE, Rhee KE, Boutelle KN. Psychometric properties of the Child Eating Behavior Questionnaire (CEBQ) in school age children with overweight and obesity: A proposed three factor structure. Pediatric Obesity. 2021;16(10):e12795. doi:10.1111/ijpo.12795'),
    cebq_pe = list( Description = 'Picky eating.',
                    Derivative = TRUE,
                    Reference = 'Manzano MA, Strong DR, Kang Sim DE, Rhee KE, Boutelle KN. Psychometric properties of the Child Eating Behavior Questionnaire (CEBQ) in school age children with overweight and obesity: A proposed three factor structure. Pediatric Obesity. 2021;16(10):e12795. doi:10.1111/ijpo.12795'),
    cebq_ee = list( Description = 'Emotional eating.',
                    Derivative = TRUE,
                    Reference = 'Manzano MA, Strong DR, Kang Sim DE, Rhee KE, Boutelle KN. Psychometric properties of the Child Eating Behavior Questionnaire (CEBQ) in school age children with overweight and obesity: A proposed three factor structure. Pediatric Obesity. 2021;16(10):e12795. doi:10.1111/ijpo.12795'))

  # convert formatting to JSON
  cebq_json <- RJSONIO::toJSON(cebq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cebq_json, asText = TRUE))){
    print('CEBQ JSON file may be invalid')
  }

  return(cebq_json)

}
