#' json_brief2: Generates a json file for the Behavioral Rating Inventory of Executive Function-2
#'
#' This function generates a json file for the scored Behavioral Rating Inventory of Executive Function-2 and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_brief2 function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Behavioral Rating Inventory of Executive Function-2
#'
#'
#' @export

json_brief2 <- function() {

  brief_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Behavioral Rating Inventory of Executive Function-2. Participants were provided the following instructions: "Please answer each question as it pertains to your child with never, sometimes or often"',
      Reference = 'Gioia GA, Isquith PK, Guy SC, Kenworthy L. BRIEF-2: Behavior Rating Inventory of Executive Function: Professional Manual. Psychological Assessment Resources; 2015.',
      TermURL = 'https://www.cognitiveatlas.org/task/id/tsk_4a57abb9498ab/'),
    participant_id = list( Description = 'participant id number'),
    sex = list( Description = 'sex',
                Levels = list ('0' = 'female',
                               '1' = 'male')),
    age = list( Description = 'child age at visit 2',
                Units = 'years'),
    brief1 = list( Description = 'My child is fidgety',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief2 = list( Description = 'My child resists or has trouble accepting a different way to solve a problem with schoolwork, friends, tasks, etc.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief3 = list( Description = 'My child, when given three things to do, remembers only the first or last',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief4 = list( Description = 'My child is unaware of how his/her behavior affects or bothers others',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief5 = list( Description = 'My child\'s work is sloppy',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief6 = list( Description = 'My child has explosive, angry outbursts',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief7 = list( Description = 'My child does not plan ahead for school assignments',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief8 = list( Description = 'My child cannot find things in their room or in their school desk',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief9 = list( Description = 'My child is not a self-starter',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief10 = list( Description = 'My child does not think before doing (is impulsive)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief11 = list( Description = 'My child has trouble getting used to new situations (classes, groups, friends, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief12 = list( Description = 'My child has a short attention span',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief13 = list( Description = 'My child has poor understanding of own strengths and weaknesses',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief14 = list( Description = 'My child has outbursts for little reason',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief15 = list( Description = 'My child gets caught up in details and misses the big picture',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief16 = list( Description = 'My child gets out of control more than friends',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief17 = list( Description = 'My child gets stuck on one topic or activity',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief18 = list( Description = 'My child forgets his/her name',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief19 = list( Description = 'My child has trouble with chores or tasks that have more than one step',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief20 = list( Description = 'My child does not realize that certain actions bother others',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief21 = list( Description = 'My child\'s written work is poorly organized',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief22 = list( Description = 'Small events trigger big reactions with my child',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief23 = list( Description = 'My child has good ideas but does not get the job done (lacks follow-through)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief24 = list( Description = 'My child talks at the wrong time',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief25 = list( Description = 'My child has trouble finishing tasks (chores, homework, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief26 = list( Description = 'My child does not notice when his/her behavior causes negative reactions',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief27 = list( Description = 'My child reacts more strongly to situations than other children',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief28 = list( Description = 'My child has trouble remembering things, even for a few minutes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief29 = list( Description = 'My child makes careless errors',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief30 = list( Description = 'My child gets out of seat at the wrong times',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief31 = list( Description = 'My child becomes upset with new situations',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief32 = list( Description = 'My child has trouble concentrating on tasks, schoolwork, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief33 = list( Description = 'My child has poor handwriting',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief34 = list( Description = 'My child\'s mood changes frequently',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief35 = list( Description = 'My child has good ideas but cannot get them on paper',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief36 = list( Description = 'My child has trouble counting to three',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief37 = list( Description = 'My child leaves messes that others have to clean up',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief38 = list( Description = 'My child needs to be told when to begin a task even when willing',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief39 = list( Description = 'My child acts too wild or "out of control"',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief40 = list( Description = 'My child thinks too much about the same topic',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief41 = list( Description = 'My child forgets what he/she was doing',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief42 = list( Description = 'My child does not check work for mistakes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief43 = list( Description = 'My child\'s angry or tearful outbursts are intense but end suddenly',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief44 = list( Description = 'My child becomes overwhelmed by large assignments',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief45 = list( Description = 'My child loses lunch box, lunch money, permission slips, homework, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief46 = list( Description = 'My child needs help from an adult to stay on task',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief47 = list( Description = 'My child forgets to hand in homework, even when completed',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief48 = list( Description = 'My child has trouble putting the brakes on his/her actions',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief49 = list( Description = 'My child resists change of routine, foods, places, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief50 = list( Description = 'My child has trouble getting started on homework or tasks',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief51= list( Description = 'My child\'s mood is easily influenced by the situation',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief52 = list( Description = 'My child underestimates time needed to finish tasks',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief53 = list( Description = 'My child does not bring home homework, assignment sheets, materials, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief54 = list( Description = 'My child cannot find the front door of home',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief55 = list( Description = 'My child does not take initiative',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief56 = list( Description = 'My child becomes upset too easily',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief57 = list( Description = 'My child starts assignments or tasks at the last minute',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief58 = list( Description = 'My child has trouble moving from one activity to another',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief59 = list( Description = 'My child has trouble carrying out the actions needed to reach goals (saving money for special item, studying to get a good grade, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief60 = list( Description = 'My child is disturbed by change of teacher or class',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief61 = list( Description = 'My child has trouble organizing activities with friends',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief62 = list( Description = 'My child becomes too silly',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief2_inhibit = list( Description = 'Inhibition',
                           Derivative = TRUE),
    brief2_inhibit_t = list( Description = 'Inhibition T-score',
                             Derivative = TRUE),
    brief2_inhibit_p = list( Description = 'Inhibition Percentile',
                             Derivative = TRUE),
    brief2_selfmon = list( Description = 'Self-Monitoring',
                           Derivative = TRUE),
    brief2_selfmon_t = list( Description = 'Self-Monitoring T-score',
                             Derivative = TRUE),
    brief2_selfmon_p = list( Description = 'Self-Monitoring Percentile',
                             Derivative = TRUE),
    brief2_shift = list( Description = 'Shifting',
                         Derivative = TRUE),
    brief2_shift_t = list( Description = 'Shifting T-score',
                           Derivative = TRUE),
    brief2_shift_p = list( Description = 'Shifting Percentile',
                           Derivative = TRUE),
    brief2_emcont = list( Description = 'Emotional Control',
                          Derivative = TRUE),
    brief2_emcont_t = list( Description = 'Emotional Control T-score',
                            Derivative = TRUE),
    brief2_emcont_p = list( Description = 'Emotional Control Percentile',
                            Derivative = TRUE),
    brief2_initiate = list( Description = 'Initiate',
                            Derivative = TRUE),
    brief2_initiate_t = list( Description = 'Initiate T-score',
                              Derivative = TRUE),
    brief2_initiate_p = list( Description = 'Initiate Percentile',
                              Derivative = TRUE),
    brief2_wm = list( Description = 'Working Memory',
                      Derivative = TRUE),
    brief2_wm_t = list( Description = 'Working Memory T-score',
                        Derivative = TRUE),
    brief2_wm_p = list( Description = 'Working Memory Percentile',
                        Derivative = TRUE),
    brief2_planorg = list( Description = 'Planning/Organization',
                           Derivative = TRUE),
    brief2_planorg_t = list( Description = 'Planning/Organization T-score',
                             Derivative = TRUE),
    brief2_planorg_p = list( Description = 'Planning/Organization Percentile',
                             Derivative = TRUE),
    brief2_taskmon = list( Description = 'Task Monitoring',
                           Derivative = TRUE),
    brief2_taskmon_t = list( Description = 'Task Monitoring T-score',
                             Derivative = TRUE),
    brief2_taskmon_p = list( Description = 'Task Monitoring Percentile',
                             Derivative = TRUE),
    brief2_orgmat = list( Description = 'Organiation of Materials',
                          Derivative = TRUE),
    brief2_orgmat_t = list( Description = 'Organiation of Materials T-score',
                            Derivative = TRUE),
    brief2_orgmat_p = list( Description = 'Organiation of Materials Percentile',
                            Derivative = TRUE),
    brief2_bri = list( Description = 'Behavioral Regulation Index',
                       Derivative = TRUE),
    brief2_bri_t = list( Description = 'Behavioral Regulation Index T-score',
                         Derivative = TRUE),
    brief2_bri_p = list( Description = 'Behavioral Regulation Index Percentile',
                         Derivative = TRUE),
    brief2_eri = list( Description = 'Emotional Regulaiton Index',
                       Derivative = TRUE),
    brief2_eri_t = list( Description = 'Emotional Regulaiton Index T-score',
                         Derivative = TRUE),
    brief2_eri_p = list( Description = 'Emotional Regulaiton Index Percentile',
                         Derivative = TRUE),
    brief2_cri = list( Description = 'Cognitive Regulation Index',
                       Derivative = TRUE),
    brief2_cri_t = list( Description = 'Cognitive Regulation Index T-score',
                         Derivative = TRUE),
    brief2_cri_p = list( Description = 'Cognitive Regulation Index Percentile',
                         Derivative = TRUE),
    brief2_gec = list( Description = 'General Executive Composite',
                       Derivative = TRUE),
    brief2_gec_t = list( Description = 'General Executive Composite T-score',
                         Derivative = TRUE),
    brief2_gec_p = list( Description = 'General Executive Composite Percentile',
                         Derivative = TRUE),
    brief2_negativity = list( Description = 'Negativity Check',
                              Derivative = TRUE),
    brief2_negativity_p = list( Description = 'Negativity Check Percentile',
                                Derivative = TRUE),
    brief2_negativity_cat = list( Description = 'Negativity Check Category',
                                  Levels = list ('0' = '<=98',
                                                 '1' = '99',
                                                 '2' = '>99'),
                                  Derivative = TRUE),
    brief2_inconsistency = list( Description = 'Inconsistency Check',
                                 Derivative = TRUE),
    brief2_inconsistency_p = list( Description = 'Inconsistency Check Percentile',
                                   Derivative = TRUE),
    brief2_inconsistency_cat = list( Description = 'Inconsistency Check Category',
                                     Levels = list ('0' = '<=98',
                                                    '1' = '99',
                                                    '2' = '>99'),
                                     Derivative = TRUE),
    brief2_infrequency = list( Description = 'Infrequency',
                               Derivative = TRUE),
    brief2_infrequency_p = list( Description = 'Infrequency Percentile',
                                 Derivative = TRUE),
    brief2_infrequency_cat = list( Description = 'Infrequency Category',
                                   Levels = list ('0' = 'Acceptable',
                                                  '1' = 'Questionable'),
                                   Derivative = TRUE))


  # convert formatting to JSON
  brief_json <- RJSONIO::toJSON(brief_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(brief_json, asText = TRUE))){
    print('BRIEF JSON file may be invalid')
  }

  return(brief_json)

}
