#' json_household: Generates a json file for the household demographic questionnaire
#'
#' This function provides a json file for household demographic questionnaire collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the household demographic questionnaire
#'
#'
#' @export

json_household <- function() {

  household_list <- list(
    'MeasurementToolMetadata' = list(
      Description = '',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit = list( Description = 'REACH visit protocol for data collection'),

    # these are part of the demo questionnaire collected on V1 only:
    # demo_birth_length = list( Description = 'What was your child\'s birth length, in inches?'),
    # demo_birthweight_pounds = list( Description = 'Child\'s birth weight (pounds):'),
    # demo_birthweight_ounces = list( Description = 'Child birth weight (ounces):'),
    # demo_premature = list( Description = ''),
    # demo_premature_weeks = list( Description = ''),
    # demo_feeding = list( Description = ''),
    # demo_exclusive_feeding = list( Description = ''),
    # demo_tot_breastfeeding = list( Description = ''),
    # demo_solid_food = list( Description = ''),

    demo_child_relationship = list( Description = 'What is your relationship to the child in the study?',
                                    Levels = list ('0' = 'Biological mother',
                                                   '1' = 'Biological father',
                                                   '2' = 'Non-biological mother',
                                                   '3' = 'Non-biological father',
                                                   '4' = 'Other')),
    demo_relationship_other = list( Description = 'Please specify other relationship with child:'),
    demo_number_of_children = list( Description = 'How many children do you have? (Enter a number)'),
    demo_birth_number = list( Description = 'What is the birth number of the child in the study (E.g. If the child is first born, enter 1)'),
    demo_child_edu = list( Description = 'What is the highest level of education completed by the child enrolled in the study?',
                           Levels = list ('0' = 'Kindergarten',
                                          '1' = '1st grade',
                                          '2' = '2nd grade',
                                          '3' = '3rd grade',
                                          '4' = '4th grade',
                                          '5' = '5th grade',
                                          '6' = '6th grade')),
    demo_parent_age = list( Description = 'Age of parent calculated from self-reported parent date of birth (data not shared) and date of form completion (data not shared)',
                            Unit = "years",
                            Derivative = TRUE),
    demo_parent_ethnicity = list( Description = 'What is your ethnicity?',
                                  Levels = list ('0' = 'Hispanic or Latino',
                                                 '1' = 'Not Hispanic or Latino')),
    demo_parent_race = list( Description = 'What is your race?',
                             Levels = list ('0' = 'American Indian/Alaskan Native',
                                            '1' = 'Asian',
                                            '2' = 'Black or African American',
                                            '3' = 'White',
                                            '4' = 'Hawaiian/Pacific Islander',
                                            '5' = 'Other')),
    demo_parent_other_race = list( Description = 'Other race (please state):'),
    demo_live_mother = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Mother'),
    demo_live_father = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Father'),
    demo_live_siblings = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Siblings'),
    demo_live_uncle = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Uncle'),
    demo_live_aunt = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Aunt'),
    demo_live_grandma = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Grandmother'),
    demo_live_grandpa = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Grandfather'),
    demo_live_cousins = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Cousin'),
    demo_live_other = list( Description = 'Please indicate the number of people, INCLUDING YOURSELF, who currently live in your child\'s primary household (the one he or she spends the most time in). If the person does not live there, just mark 0.: Other'),
    demo_parent_seperations = list( Description = 'How many parental/parental figure separations has your child experienced? (Enter a number)'),
    demo_foster_care = list( Description = 'How many foster care placements has your child experienced, prior to his/her current living arrangement? (Enter a Number)'),
    demo_partner = list( Description = 'Do you have a spouse, partner, or significant other?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_parents_together = list( Description = 'Does your spouse, partner, or significant other currently reside in your child\'s primary household?'),
    demo_partner_relationship = list( Description = 'What is your spouse, partner, or significant other\'s relationship to the child?',
                                      Levels = list ('0' = 'Biological mother',
                                                     '1' = 'Biological father',
                                                     '2' = 'Non-biological mother',
                                                     '3' = 'Non-biological father',
                                                     '4' = 'Other')),
    demo_partner_relationship_other = list( Description = 'Please specify other relationship with child:'),
    demo_marital_status = list( Description = 'What is your marital status?',
                                Levels = list ('0' = 'Married',
                                               '1' = 'Single (never married)',
                                               '2' = 'Widowed',
                                               '3' = 'Divorced',
                                               '4' = 'Separated',
                                               '5' = 'Remarried',
                                               '6' = 'Living together, not married')),
    # demo_income -- moved to demo/participants
    # demo_education_mom  -- moved to demo/participants
    demo_education_dad = list( Description = 'What is the child\'s biological father\'s highest level of formal education?',
                               Levels = list ('0' = 'None',
                                              '1' = 'Preschool',
                                              '2' = 'Kindergarten',
                                              '3' = '1st grade',
                                              '4' = '2nd grade',
                                              '5' = '3rd grade',
                                              '6' = '4th grade',
                                              '7' = '5th grade',
                                              '8' = '6th grade',
                                              '9' = '7th grade',
                                              '10' = '8th grade',
                                              '11' = '9th grade',
                                              '12' = '10th grade',
                                              '13' = '11th grade',
                                              '14' = 'GED',
                                              '15' = 'High School graduate',
                                              '16' = 'Some college but less than 1 year',
                                              '17' = 'One or more years of college at a 2-year program, No degree obtained',
                                              '18' = 'One year of college at a 4-year program, No degree obtained',
                                              '19' = 'Two years of college at a 4-year program, No degree obtained',
                                              '20' = 'Three years of college at a 4-year program, No degree obtained',
                                              '21' = 'Associates degree (AA, AS)',
                                              '22' = 'Bachelor\'s Degree (BA, AB, BS)',
                                              '23' = 'Master\'s degree (MA, MS, MEng, MEd, MSW, MBA, MPH)',
                                              '24' = 'Professional Degree (MD, DDS, DVM, LLB, JD, DPT, PharmD)',
                                              '25' = 'Doctoral Degree (PhD, EdD, PsyD)',
                                              '26' = 'N/A')),
    demo_education_partner = list( Description = 'What is your partner\'s highest level of formal education?',
                                   Levels = list ('0' = 'None',
                                                  '1' = 'Preschool',
                                                  '2' = 'Kindergarten',
                                                  '3' = '1st grade',
                                                  '4' = '2nd grade',
                                                  '5' = '3rd grade',
                                                  '6' = '4th grade',
                                                  '7' = '5th grade',
                                                  '8' = '6th grade',
                                                  '9' = '7th grade',
                                                  '10' = '8th grade',
                                                  '11' = '9th grade',
                                                  '12' = '10th grade',
                                                  '13' = '11th grade',
                                                  '14' = 'GED',
                                                  '15' = 'High School graduate',
                                                  '16' = 'Some college but less than 1 year',
                                                  '17' = 'One or more years of college at a 2-year program, No degree obtained',
                                                  '18' = 'One year of college at a 4-year program, No degree obtained',
                                                  '19' = 'Two years of college at a 4-year program, No degree obtained',
                                                  '20' = 'Three years of college at a 4-year program, No degree obtained',
                                                  '21' = 'Associates degree (AA, AS)',
                                                  '22' = 'Bachelor\'s Degree (BA, AB, BS)',
                                                  '23' = 'Master\'s degree (MA, MS, MEng, MEd, MSW, MBA, MPH)',
                                                  '24' = 'Professional Degree (MD, DDS, DVM, LLB, JD, DPT, PharmD)',
                                                  '25' = 'Doctoral Degree (PhD, EdD, PsyD)',
                                                  '26' = 'N/A')),
    demo_employed = list( Description = 'Are you currently employed?',
                          Levels = list ('0' = 'No',
                                         '1' = 'Yes')),
    demo_work_hours = list( Description = 'How many hours per week are you at work (not traveling to and from)?'),
    demo_retired = list( Description = 'Are you currently retired?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_partner_employment = list( Description = 'Is your spouse, partner, or significant other currently employed?'),
    demo_partner_workhours = list( Description = 'How many hours per week is your spouse, partner, or significant other at work (not traveling to and from)?'),
    demo_partner_retired = list( Description = 'Is your spouse, partner, or significant other currently retired?',
                                 Levels = list ('0' = 'No',
                                                '1' = 'Yes')),
    demo_weight_past_month = list( Description = 'Has your child\'s biological mother lost or gained 10 or more pounds in the past month?',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_pre_pregnancy_weight = list( Description = 'What was your (or your child\'s biological mothers) pre-pregnancy weight prior to becoming pregnant with your child that is enrolled in the study? Please enter in pounds:'),
    demo_weight_changes = list( Description = 'How has your body weight changed over the last three years? ',
                                Levels = list ('0' = 'Stable/no change',
                                               '1' = 'Increased',
                                               '2' = 'Decreased')),
    demo_weight_last_year = list( Description = 'What is your typical body weight over the last year? Please provide your average weight in pounds:'),
    demo_weight_two_years = list( Description = 'What was your typical body weight two years ago? Please provide your average weight in pounds:'),
    demo_weight_three_years = list( Description = 'What was your typical body weight three years ago? Please provide your average weight in pounds: '),
    demo_weight_five_years = list( Description = 'What was your typical body weight five years ago? Please provide your average weight in pounds: '),
    demo_lost_weight_one_year = list( Description = 'Have you or your spouse, partner, or significant other lost more than ten pounds in the past year, excluding weight from pregnancy?',
                                      Levels = list ('0' = 'No',
                                                     '1' = 'Yes')),
    demo_parent2_reported_height_ft_component = list( Description = 'What is your child\'s biological parent\'s height who was not measured or present at today\'s visit (Feet):'),
    demo_parent2_reported_height_inch_component = list( Description = 'What is your child\'s biological parent\'s height who was not measured or present at today\'s visit (Inches):'),
    demo_parent2_reported_weight_lbs = list( Description = 'What is the weight, in pounds, of your child\'s biological parent who is not present at todays visit?'),
    demo_feeding_child = list( Description = 'Who is primarily responsible for feeding your child?',
                               Levels = list ('0' = 'You',
                                              '1' = 'Your partner',
                                              '2' = 'Both',
                                              '3' = 'School',
                                              '4' = 'Other')),
    demo_feeding_child_other = list( Description = 'Others feeding child (please specify):'),
    demo_buys_food = list( Description = 'Who is primarily responsible for buying food in your household?',
                           Levels = list ('0' = 'You',
                                          '1' = 'Your partner',
                                          '2' = 'Both',
                                          '3' = 'Other')),
    demo_buys_food_other = list( Description = 'Others buying food (please specify):'),
    demo_eat_out = list( Description = 'On average, how frequently does your family eat out or get delivery/take out for dinner?',
                         Levels = list ('0' = 'Once a month or less',
                                        '1' = 'Twice a month',
                                        '2' = 'Once a week',
                                        '3' = 'Two times a week',
                                        '4' = 'Three times a week',
                                        '5' = 'Four or more times a week')),
    demo_dinner_together = list( Description = 'On average, how many nights a week does your family eat dinner together as a group (with most family members present)?'),
    demo_prepared_lunch = list( Description = 'On average, how many times per week does your child eat lunch that he/she brings from home?'),
    demo_food_condition = list( Description = 'Does anyone in your household have a condition that affects the food they eat?',
                                Levels = list ('0' = 'No',
                                               '1' = 'Yes')),
    demo_programs___0 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: I have not used assistance programs'),
    demo_programs___1 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: SNAP (food stamps)'),
    demo_programs___2 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: WIC'),
    demo_programs___3 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: TNAF (cash assistance)'),
    demo_programs___4 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Medicaid (Medical assistance)'),
    demo_programs___5 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: LIHEAP (Home energy assistance)'),
    demo_programs___6 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Partial Free/Reduced School Meal Program (only some meals)'),
    demo_programs___7 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Full Free/Reduced School Meal Programs (all meal'),
    demo_programs___8 = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Other assistance programs'),
    demo_programs_other = list( Description = 'Other assistance programs (please state):'),
    demo_food_pantry = list( Description = 'Have you ever received food from a food pantry or soup kitchen?',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
    demo_foodpantry_times = list( Description = 'How many times have you received food from a food pantry or soup kitchen in the past 12 months?'),
    demo_food_costs = list( Description = 'In a typical month, how much money do you spend on food for your household, including food you buy at any stores and restaurants?',
                            Levels = list ('0' = 'Less than $100 a month',
                                           '1' = '$100 - $200 a month',
                                           '2' = '$200 - $300 a month',
                                           '3' = '$300 - $400 a month',
                                           '4' = '$400 - $500 a month',
                                           '5' = 'More than $500 a month')),
    demo_store_choice = list( Description = 'Which grocery store do you use most often when going on a typical food shopping trip?',
                              Levels = list ('0' = 'Giant',
                                             '1' = 'Sam\'s Club',
                                             '2' = 'Target',
                                             '3' = 'Trader Joe\'s',
                                             '4' = 'Walmart',
                                             '5' = 'Wegmans',
                                             '6' = 'Weis',
                                             '7' = 'ALDI',
                                             '8' = 'A speciality of international food store, such as International Market')),
    demo_grow_own_food___0 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Fruits',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___1 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Vegetables',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___2 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Jelly, jam, or any other spreads/dips made from your fruits or vegetables',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___3 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Nuts or seeds',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___4 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Milk',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___5 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Cheese',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___6 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Butter',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___7 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Eggs',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___8 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Red meat',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___9 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Poultry meat',
                                   Levels = list ('0' = 'Box Unchecked (do not grow or produce item in household)',
                                                  '1' = 'Box Checked (grow or produce item in household)')),
    demo_grow_own_food___10 = list( Description = 'Do you grow or produce any of these food items for your household (for example, in your own garden or farm)? Check all that apply: Do not produce any of these food items',
                                    Levels = list ('0' = 'Box Unchecked',
                                                   '1' = 'Box Checked')),
    demo_allowance = list( Description = 'Does your child get money as an allowance?',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
    demo_allowance_other = list( Description = 'About how much money per week do you give your child for their allowance?',
                                 Levels = list ('0' = 'Less than $1 a week',
                                                '1' = '$1 - $5 a week',
                                                '2' = 'More than $5 a week')))

  # variables to add:
  # parent2_reported_height_m -- derivative computed from reported feet and inches
  # parent2_reported_bmi -- derivative. will this be included? or just report in anthro form?

  # convert formatting to JSON
  household_json <- RJSONIO::toJSON(household_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(household_json, asText = TRUE))){
    print('household demo JSON file may be invalid')
  }

  return(household_json)

}
