#' json_rank: Generates a json file for the Ranking Food Item Questionnaire
#'
#' This function generates a json file for the Ranking Food Item Questionnaire.
#'
#' @return A string with data stored in JSON format containing meta-data for the Ranking Food Item Questionnaire
#'
#'
#' @export

json_rank <- function() {

  rank_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Ranking Food Item Questionnaire. Participants were provided the following instructions: "Imagine that you are on a typical food shopping trip at your preferred grocery store. Listed below are the different items that you can choose from. Please rank each item based on how important it is for you to buy during your typical grocery trip. The very important items should be foods that you won\'t leave the store without, or always make it into your budget. Items in the middle should be ones you would like to have, but are willing to cut from your budget if needed. Finally, the not important items should be foods that you don\'t buy on a typical trip or don\'t fit into your typical budget."',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                    Levels = list ('ses-1' = 'session 1 / baseline',
                                   'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date (YYYY-MM-DD) of visit this parent report survey was completed'),
    rank_package_breads = list(Description = 'Pre-packaged bread items, such as sandwich bread, hamburger buns, hotdog rolls, muffins, or bagels',
                 Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_bakery = list( Description = 'Bakery breads or other freshly made goods, such as cake, cookies, or doughnuts',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_saltysnacks = list( Description = 'Salty snacks, such as chips, crackers, popcorn, or jerky',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_sweetsnacks = list( Description = 'Sweet snacks, such as cookies or cakes',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_cheese = list( Description = 'Cheese',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_milk = list( Description = 'Milk',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_yogurt = list( Description = 'Yogurt',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_butter = list( Description = 'Butter, margarine, or other butter substitutes',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_eggs = list( Description = 'Eggs',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank_otherdairy = list( Description = 'Other dairy products, such as sour cream',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_coffee_tea = list( Description = 'Coffee or tea',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_carbonated_bev_soda = list( Description = 'Soda or other carbonated beverages',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_fruitjuice = list( Description = 'Fruit juices or beverages, such as orange juice or apple cider',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_sportsdrinks = list( Description = 'Sports drinks, such as Gatorade or Powerade',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_alcohol = list( Description = 'Alcoholic beverages, such as beer or wine',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_redmeat = list( Description = 'Red meat, such as beef, pork, or lamb',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_poultry = list( Description = 'Poultry, such as chicken or turkey',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_seafood = list( Description = 'Seafood, such as shrimp, salmon, tilapia, tuna, crab, or lobster',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_pasta_rice = list( Description = 'Pasta, noodles, or rice, such as fettuccine, lasagna, white rice, or brown rice',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_soup = list( Description = 'Soup, such as chicken noodle or tomato',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_nuts_seeds = list( Description = 'Nuts and seeds, such as peanuts, almonds, walnuts, or sunflower seeds',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_nut_fruit_spreads = list( Description = 'Nut butters, jelly and honey, such as peanut or almond butter; or strawberry or grape jelly',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_breakfast_cereals = list( Description = 'Breakfast cereals, such as oatmeal or cornflakes',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_protein_bars = list( Description = 'Breakfast, meal replacement, or protein bars, such as Luna, Cliff, Quest, Quaker, or Nature Valley bars',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_protein_shakes = list( Description = 'Meal replacement shakes or protein powder, such as Glucerna shakes or Muscle Milk',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_preparedfoods = list( Description = 'Fresh prepared foods, such as pizza or salad bar entrees',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_veg_fresh = list( Description = 'Fresh vegetables, such as spinach, carrots, or broccoli',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_fruit_fresh = list( Description = 'Fresh fruits, such as strawberries, apples, or oranges',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_veg_can = list( Description = 'Canned vegetables',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_fruit_can = list( Description = 'Canned fruits',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_veg_frozen = list( Description = 'Frozen vegetables',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_fruit_frozen = list( Description = 'Frozen fruits',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_dinner_frozen = list( Description = 'Frozen dinner items, such as pizza, macaroni and cheese, or French fries',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_breakfast_frozen = list( Description = 'Frozen breakfast items, such as waffles',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_desserts_frozen = list( Description = 'Frozen desserts, such as cakes or pies',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_candy_gum = list( Description = 'Candy or gum, such as chocolate, caramel, or toffee',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_baking_supplies = list( Description = 'Baking supplies, such as flour, sugar, or baking soda',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_condiments = list( Description = 'Condiments or sauces, such as ketchup, mustard, mayonnaise, tomato sauce, barbeque sauce, or hot sauce',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_spreads_dips = list( Description = 'Dips or spreads, such as hummus, French onion dip, or ranch dip',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_salad_dressings = list( Description = 'Salad dressings or toppings, such as oil and vinegar, ranch, honey mustard, or croutons',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_spices_seasonings = list( Description = 'Spices and seasonings, such as salt, pepper, cinnamon, basil, or oregano',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank_cooking_oils = list( Description = 'Oil, cooking spray, or shortening, such as olive oil or coconut oil',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all'))
    )

  # convert formatting to JSON
  rank_json <- RJSONIO::toJSON(rank_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(rank_json, asText = TRUE))){
    print('rank JSON file may be invalid')
  }

  return(rank_json)

}
