#' json_lbc: Generates a json file for the Lifestyle Behavior Checklist
#'
#' This function generates a json file for the scored Lifestyle Behavior Checklist and raw participant responses. This function provides accurate json files ONLY if data is processed using score_lbc function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A string with data stored in JSON format containing meta-data for the Lifestyle Behavior Checklist
#'
#'
#' @export

json_lbc <- function() {

  lbc_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Lifestyle Behavior Checklist. Participants were provided the following instructions: "For each item: (1) mark the number that best describes how much of a problem that behavior has been with your child in the last month, and (2) rate how confident you are in dealing with it. If that behavior is not currently occurring, rate how confident you are that you could successfully deal with your child\'s behavior if it did occur. Remember to put a confidence rating for every item. Mark a number for each behavior from 1 (not at all a problem) to 7 (very much a problem); Rate your confidence from 1 (Certain I cannot do it) to 10 (Certain I can do it)."',
      Reference = 'West F, Morawska A, Joughin K. The Lifestyle Behaviour Checklist: evaluation of the factor structure. Child: Care, Health and Development. 2010;36(4):508-515. doi:10.1111/j.1365-2214.2010.01074.x',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/20337641/'),
    participant_id = list( Description = 'participant id number'),
    lbc1 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child eats too quickly',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc2 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child eats too much',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc3 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child eats unhealthy snacks',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc4 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child whinges or whines about food',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc5 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child yells about food',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc6 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child throws a tantrum about food',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc7 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child refuses to eat certain foods (i.e. fussy eating)',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc8 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child argues about food (e.g. when you say "No More")',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc9 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child demands extra helpings at meals',
                 Levels = list ('0' = '1 - Not at all',
                                '1' = '2',
                                '2' = '3',
                                '3' = '4 - Somewhat',
                                '4' = '5',
                                '5' = '6',
                                '6' = '7 - Very much')),
    lbc10 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child requests food continuously between meals',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc11 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child demands food when shopping or on outings',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc12 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child sneaks food when they know they are not supposed to',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc13 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child hides food',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc14 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child steals food (e.g. from other children\'s lunchboxes)',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc15 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child eats food to comfort themselves when feeling let down or depressed',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc16 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child watches too much television',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc17 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child spends too much time playing video or computer games',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc18 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about doing physical activity (e.g. "This is boring, I\'m too tired, My leg hurts")',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc19 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child refuses to do physical activity',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc20 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about being unfit or feeling low in energy',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc21 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about being overweight',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc22 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about being teased',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc23 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about not having enough friends',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc24 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about being unattractive',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc25 = list( Description = 'To what extent has this behavior been a problem for you with your child?: My child complains about not fitting into clothes',
                  Levels = list ('0' = '1 - Not at all',
                                 '1' = '2',
                                 '2' = '3',
                                 '3' = '4 - Somewhat',
                                 '4' = '5',
                                 '5' = '6',
                                 '6' = '7 - Very much')),
    lbc1_conf = list( Description = 'How confident are you in dealing with it?: My child eats too quickly',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc2_conf = list( Description = 'How confident are you in dealing with it?: My child eats too much',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc3_conf = list( Description = 'How confident are you in dealing with it?: My child eats unhealthy snacks',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc4_conf = list( Description = 'How confident are you in dealing with it?: My child whinges or whines about food',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc5_conf = list( Description = 'How confident are you in dealing with it?: My child yells about food',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc6_conf = list( Description = 'How confident are you in dealing with it?: My child throws a tantrum about food',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc7_conf = list( Description = 'How confident are you in dealing with it?: My child refuses to eat certain foods (i.e. fussy eating)',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc8_conf = list( Description = 'How confident are you in dealing with it?: My child argues about food (e.g. when you say "No More")',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc9_conf = list( Description = 'How confident are you in dealing with it?: My child demands extra helpings at meals',
                      Levels = list ('0' = '1 - Certain I connot do it',
                                     '1' = '2',
                                     '2' = '3',
                                     '3' = '4',
                                     '4' = '5',
                                     '5' = '6',
                                     '6' = '7',
                                     '7' = '8',
                                     '8' = '9',
                                     '9' = '10 - Certain I can do it')),
    lbc10_conf = list( Description = 'How confident are you in dealing with it?: My child requests food continuously between meals',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc11_conf = list( Description = 'How confident are you in dealing with it?: My child demands food when shopping or on outings',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc12_conf = list( Description = 'How confident are you in dealing with it?: My child sneaks food when they know they are not supposed to',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc13_conf = list( Description = 'How confident are you in dealing with it?: My child hides food',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc14_conf = list( Description = 'How confident are you in dealing with it?: My child steals food (e.g. from other children\'s lunchboxes)',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc15_conf = list( Description = 'How confident are you in dealing with it?: My child eats food to comfort themselves when feeling let down or depressed',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc16_conf = list( Description = 'How confident are you in dealing with it?: My child watches too much television',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc17_conf = list( Description = 'How confident are you in dealing with it?: My child spends too much time playing video or computer games',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc18_conf = list( Description = 'How confident are you in dealing with it?: My child complains about doing physical activity (e.g. "This is boring, I\'m too tired, My leg hurts")',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc19_conf = list( Description = 'How confident are you in dealing with it?: My child refuses to do physical activity',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc20_conf = list( Description = 'How confident are you in dealing with it?: My child complains about being unfit or feeling low in energy',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc21_conf = list( Description = 'How confident are you in dealing with it?: My child complains about being overweight',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc22_conf = list( Description = 'How confident are you in dealing with it?: My child complains about being teased',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc23_conf = list( Description = 'How confident are you in dealing with it?: My child complains about not having enough friends',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc24_conf = list( Description = 'How confident are you in dealing with it?: My child complains about being unattractive',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc25_conf = list( Description = 'How confident are you in dealing with it?: My child complains about not fitting into clothes',
                       Levels = list ('0' = '1 - Certain I connot do it',
                                      '1' = '2',
                                      '2' = '3',
                                      '3' = '4',
                                      '4' = '5',
                                      '5' = '6',
                                      '6' = '7',
                                      '7' = '8',
                                      '8' = '9',
                                      '9' = '10 - Certain I can do it')),
    lbc_misbeh = list( Description = 'Food-related misbehavior.',
                       Derivative = TRUE),
    lbc_overeat = list( Description = 'Overeating.',
                        Derivative = TRUE),
    lbc_em_overweight = list( Description = 'Emotion related to being overweight.',
                              Derivative = TRUE),
    lbc_pa = list( Description = 'Physical activity.',
                   Derivative = TRUE),
    lbc_total = list( Description = 'Total score.',
                      Derivative = TRUE))


  # convert formatting to JSON
  lbc_json <- RJSONIO::toJSON(lbc_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(lbc_json, asText = TRUE))){
    print('LBC JSON file may be invalid')
  }

  return(lbc_json)

}
