#' json_cfq: Generates a json file for the Child Feeding Questionnaire
#'
#' This function generates a json file for the scored Child Feeding Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_cfq function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the Child Feeding Questionnaire
#'
#'
#' @export

json_cfq <- function() {

  cfq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Child Feeding Questionnaire. Participants were provided the following instructions: "Using the scale below, please choose one option for each question which best corresponds to your answer. Please answer about your child who is in our study."',
      Reference = 'Birch, L. L., Fisher, J. O., Grimm-Thomas, K., Markey, C. N., Sawyer, R., & Johnson, S. L. (2001). Confirmatory factor analysis of the Child Feeng Questionnaire: A measure of parental attitudes, beliefs and practices about child feeng and obesity proneness. Appetite, 36(3), 201–210. https://doi.org/10.1006/appe.2001.0398',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/11358344/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    cfq_form_date = list( Description = 'Date (YYYY-MM-DD) CFQ form was completed on redcap'),
    cfq1 = list( Description = 'When your child is home, how often are you responsible for feeding him/her?',
                 Levels = list ('0' = 'Never',
                                '1' = 'Seldom',
                                '2' = 'Half of time',
                                '3' = 'Most of time',
                                '4' = 'Always')),
    cfq2 = list( Description = 'How often are you responsible for deciding what your child\'s portion sizes are?',
                 Levels = list ('0' = 'Never',
                                '1' = 'Seldom',
                                '2' = 'Half of time',
                                '3' = 'Most of time',
                                '4' = 'Always')),
    cfq3 = list( Description = 'How often are you responsible for deciding if your child had eaten the right kinds of foods?',
                 Levels = list ('0' = 'Never',
                                '1' = 'Seldom',
                                '2' = 'Half of time',
                                '3' = 'Most of time',
                                '4' = 'Always')),
    cfq4 = list( Description = 'Your childhood (5 to 10 years old)',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq5 = list( Description = 'Your adolescence',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq6 = list( Description = 'Your 20\'s',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq7 = list( Description = 'Currently',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq8 = list( Description = 'Your child during the first year of life',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq9 = list( Description = 'Your child as a toddler',
                 Levels = list ('0' = 'Markedly Underweight',
                                '1' = 'Underweight',
                                '2' = 'Average',
                                '3' = 'Overweight',
                                '4' = 'Markedly Overweight')),
    cfq10 = list( Description = 'Your child as a preschooler',
                  Levels = list ('0' = 'Markedly Underweight',
                                 '1' = 'Underweight',
                                 '2' = 'Average',
                                 '3' = 'Overweight',
                                 '4' = 'Markedly Overweight')),
    cfq11 = list( Description = 'Your child kindergarten through 2nd grade',
                  Levels = list ('0' = 'Markedly Underweight',
                                 '1' = 'Underweight',
                                 '2' = 'Average',
                                 '3' = 'Overweight',
                                 '4' = 'Markedly Overweight')),
    cfq12 = list( Description = 'Your child from 3rd through 5th grade',
                  Levels = list ('0' = 'Markedly Underweight',
                                 '1' = 'Underweight',
                                 '2' = 'Average',
                                 '3' = 'Overweight',
                                 '4' = 'Markedly Overweight')),
    cfq14 = list( Description = 'How concerned are you about your child eating too much when you are not around him/her?',
                  Levels = list ('0' = 'Unconcerned',
                                 '1' = 'Slightly unconcerned',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly concerned',
                                 '4' = 'Very Concerned')),
    cfq15 = list( Description = 'How concerned are you about your child having to diet to maintain a desirable weight?',
                  Levels = list ('0' = 'Unconcerned',
                                 '1' = 'Slightly unconcerned',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly concerned',
                                 '4' = 'Very Concerned')),
    cfq16 = list( Description = 'How concerned are you about your child becoming overweight?',
                  Levels = list ('0' = 'Unconcerned',
                                 '1' = 'Slightly unconcerned',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly concerned',
                                 '4' = 'Very Concerned')),
    cfq17 = list( Description = 'I have to be sure my child does not eat too many sweets (candy, ice cream, cake, or pastries).',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq18 = list( Description = 'I have to be sure my child does not eat too many high fat foods.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq19 = list( Description = 'I have to be sure my child does not eat too many of his/her favorite foods.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq20 = list( Description = 'I intentionally keep some foods out of my child\'s reach.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq21 = list( Description = 'I offer sweets (candy, ice cream, cake, or pastries) to my child as a reward for good behavior.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq22 = list( Description = 'I offer my child his/her favorite foods in exchange for good behavior.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq23 = list( Description = 'If I did not regulate or guide my child\'s eating, he/she would eat too many junk foods.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq24 = list( Description = 'If I did not regulate or guide my child\'s eating, he/she would eat too many of his/her favorite foods.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq25 = list( Description = 'My child should always eat all of the food on his/her plate.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq26 = list( Description = 'I have to be especially careful to ensure my child eats enough.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq27 = list( Description = 'If my child says "I\'m not hungry" I try to get him/her to eat anyway.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq28 = list( Description = 'If I did not guide or regulate my child\'s eating, he/she would eat much less than he/she should.',
                  Levels = list ('0' = 'Disagree',
                                 '1' = 'Slightly disagree',
                                 '2' = 'Neutral',
                                 '3' = 'Slightly agree',
                                 '4' = 'Agree')),
    cfq29 = list( Description = 'How much do you keep track of the sweets (candy, ice cream, cake, or pastries) that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfq30 = list( Description = 'How much do you keep track of the snack food (potato chips, Doritos, cheese puffs) that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfq31 = list( Description = 'How much do you keep track of the high fat foods that your child eats?',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Mostly',
                                 '4' = 'Always')),
    cfq_resp = list( Description = 'Perceived responsibility.',
                     Derivative = TRUE),
    cfq_pcw = list( Description = 'Perceived child weight.',
                    Derivative = TRUE),
    cfq_ppw = list( Description = 'Perceived parental weight.',
                    Derivative = TRUE),
    cfq_cwc = list( Description = 'Parental child weight concerns.',
                    Derivative = TRUE),
    cfq_rest = list( Description = 'Parental restriction.',
                     Derivative = TRUE),
    cfq_pressure = list( Description = 'Parental pressure to eat.',
                         Derivative = TRUE),
    cfq_mon = list( Description = 'Parental monitoring.',
                    Derivative = TRUE))

  # convert formatting to JSON
  cfq_json <- RJSONIO::toJSON(cfq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(cfq_json, asText = TRUE))){
    print('CFQ JSON file may be invalid')
  }

  return(cfq_json)

}
