#' json_bisbas: Generates a json file for the Behavioral Inhibition System/Behavioral Activation System Scale
#'
#' This function generates a json file for the scored Behavioral Inhibition System/Behavioral Activation System Scale and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_bisbas function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Behavioral Inhibition System/Behavioral Activation System Scale
#'
#'
#' @export

json_bisbas <- function() {

  bisbas_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Behavioral Inhibition System/Behavioral Activation System. Participants were provided the following instructions: "Each item of this questionnaire is a statement that a person may either agree with or disagree with. For each item, indicate how much you agree or disagree with what the item says. Please respond to all the items; do not leave any blank. Choose only one response to each statement. Please be as accurate and honest as you can be. Respond to each item as if it were the only item. That is, don\'t worry about being "consistent" in your responses. These answers are about your child. Choose from the following four response options: 1 = very true for me; 2 = somewhat true for me; 3 = somewhat false for me; 4 = very false for me"',
      Reference = 'Carver, C. S., & White, T. L. (1994). Behavioral inhibition, behavioral activation, and affective responses to impending reward and punishment: The BIS/BAS Scales. Journal of Personality and Social Psychology, 67(2), 319–333. https://doi.org/10.1037/0022-3514.67.2.319',
      TermURL = 'https://psycnet.apa.org/record/1995-00067-001'),
    participant_id = list( Description = 'participant id number'),
    bisbas1 = list( Description = 'My child thinks family is the most important thing in life.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas2 = list( Description = 'Even if something bad is about to happen to my child, he/she Somewhat true for me experiences fear or nervousness.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas3 = list( Description = 'My child goes out of his/her way to get things he/she wants.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas4 = list( Description = 'When my child is doing well at something he/she loves to keep at it.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas5 = list( Description = 'My child is always willing to try something new if he/she things it will be fun.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas6 = list( Description = 'How my child dresses is important to him/her.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas7 = list( Description = 'When my child gets something he/she wants, he/she feels excited and energized.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas8 = list( Description = 'Criticism or scolding hurts my child quite a bit.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas9 = list( Description = 'When my child wants something he/she usually goes all-out to get it.',
                  Levels = list ('0' = 'Very true for me',
                                 '1' = 'Somewhat true for me',
                                 '2' = 'Somewhat false for me',
                                 '3' = 'Very false for me')),
    bisbas10 = list( Description = 'My child will Very false for me do things for no other reason than that they might be fun.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas11 = list( Description = 'It\'s hard for my child to find the time to do things such as get a haircut.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas12 = list( Description = 'If my child sees a chance to get something he/she wants, he/she moves on it right away.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas13 = list( Description = 'My child feels pretty worried or upset when he/she thinks or knows somebody is angry at him/her.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas14 = list( Description = 'When my child sees an opportunity for something he/she likes, he/she gets excited right away.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas15 = list( Description = 'My child Very false for me acts on the spur of the moment.',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas16 = list( Description = 'If my child thinks something unpleasant is going to happen he/she usually gets pretty "worked up',
                    Levels = list ('0' = 'Very true for me',
                                   '1' = 'Somewhat true for me',
                                   '2' = 'Somewhat false for me',
                                   '3' = 'Very false for me')),
    bisbas17 = list( Description = 'My child Very false for me wonders why people act the way they do.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas18 = list( Description = 'When good things happen to my child, it affects him/her strongly.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas19 = list( Description = 'My child feels worried when he/she thinks he/she has done poorly at something important.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas20 = list( Description = 'My child craves excitement and new sensations.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas21 = list( Description = 'When my child goes after something he/she uses a "no holds barred" approach.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas22 = list( Description = 'My child has very few fears compared to his/her friends.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas23 = list( Description = 'It would excite my child to win a contest or prize.',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bisbas24 = list( Description = 'My child is worried about making mistakes',
                     Levels = list ('0' = 'Very true for me',
                                    '1' = 'Somewhat true for me',
                                    '2' = 'Somewhat false for me',
                                    '3' = 'Very false for me')),
    bis = list( Description = 'BIS',
                       Derivative = TRUE),
    bas = list( Description = 'BAS',
                Derivative = TRUE),
    bas_funseeking = list( Description = 'BAS Fun seeking',
                Derivative = TRUE),
    bas_drive = list( Description = 'BAS Drive',
                Derivative = TRUE),
    bas_rewardresp = list( Description = 'BAS Reward responsiveness',
                Derivative = TRUE)
    )

  # convert formatting to JSON
  bisbas_json <- RJSONIO::toJSON(bisbas_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(bisbas_json, asText = TRUE))){
    print('bisbas JSON file may be invalid')
  }

  return(bisbas_json)

}
