#' json_spsrq: Generates a json file for the Sensitivity to Punishment and Sensitivity to Reward Questionnaire
#'
#' This function generates a json file for the scored Sensitivity to Punishment and Sensitivity to Reward Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_spsrq function in dataprepr and is only accurate for data collected in Study REACH.
#'
#' @return A string with data stored in JSON format containing meta-data for the Sensitivity to Punishment and Sensitivity to Reward Questionnaire
#'
#'
#' @export

json_spsrq <- function() {

  spsrq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Sensitivity to Punishment and Sensitivity to Reward Questionnaire. Participants were provided the following instructions: "How much do you agree or disagree with each statement as it describes your child in the last year? Use the following response options."',
      Reference = 'Colder CR, Trucco EM, Lopez HI, et al. Revised reinforcement sensitivity theory and laboratory assessment of BIS and BAS in children. Journal of Research in Personality. 2011;45(2):198-207. doi:10.1016/j.jrp.2011.01.005',
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/21603055/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    spsrq_form_date = list( Description = 'Date (YYYY-MM-DD) the spsrq form was completed on Redcap'),
    spsrq1 = list( Description = 'Your child often refrains from doing something because he/she is afraid of getting into trouble',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq2 = list( Description = 'The good prospect of obtaining a reward motivates your child strongly to do some things',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq4 = list( Description = 'Your child responds strongly to praise from friends or family',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq5 = list( Description = 'Your child is often afraid of new or unexpected situations',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq6 = list( Description = 'Your child often gives in to avoid a quarrel',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq7 = list( Description = 'Your child often does things to be praised',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq8 = list( Description = 'Your child is troubled by punishments at home or in school',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq9 = list( Description = 'Your child enjoys being the center of attention',
                   Levels = list ('0' = 'Strongly Disagree',
                                  '1' = 'Disagree',
                                  '2' = 'Neither Agree Nor Disagree',
                                  '3' = 'Agree',
                                  '4' = 'Strongly Agree')),
    spsrq10 = list( Description = 'In unfamiliar tasks, your child worries about failure',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq11 = list( Description = 'It is important to your child that he/she makes a good impression on others',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq12 = list( Description = 'Your child is easily discouraged in difficult situations',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq13 = list( Description = 'Your child needs people to show their affection for him/her all the time',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq14 = list( Description = 'Your child is a shy person',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq15 = list( Description = 'When your child is in a group, he/she tries to stand out as the smartest or the funniest',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq16 = list( Description = 'Whenever possible, your child avoids demonstrating his/her skills for fear of being embarrassed',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq17 = list( Description = 'When your child gets something he/she wants, he/she feels excited and energized',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq18 = list( Description = 'When in a group, your child has difficulty thinking of something to say',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq19 = list( Description = 'Your child does a lot of things for approval',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq20 = list( Description = 'Your child often has difficulty falling asleep because he/she thinks about things he/she has done or must do',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq21 = list( Description = 'The possibility of obtaining social status moves your child to action, even if this involves not playing fair',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq22 = list( Description = 'Your child thinks a lot before complaining about something',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq23 = list( Description = 'Your child generally prefers activities that involve immediate reward',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq24 = list( Description = 'It bothers your child to tell a store clerk that he/she was given the wrong change',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq25 = list( Description = 'Your child often has trouble resisting the temptation of doing forbidden things',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq26 = list( Description = 'Whenever he/she can, your child avoids going to unfamiliar places',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq27 = list( Description = 'Your child likes to compete and do everything he/she can to win',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq28 = list( Description = 'Your child often worries about things he/she said or did',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq29 = list( Description = 'It is easy for your child to associate taste and smells to very pleasant events',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq30 = list( Description = 'It is difficult for your child to talk with someone he/she does not know',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq31 = list( Description = 'There are a large number of objects or sensations that remind your  child of pleasant events',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq32 = list( Description = 'Your child generally tries to avoid speaking in groups',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq33 = list( Description = 'Your child has a lot of difficulty ending a fun activity',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq34 = list( Description = 'Your child could do more things if it were not for his/her fear',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq35 = list( Description = 'Your child sometimes does things for quick reward',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq36 = list( Description = 'Your child is afraid of many things compared to other children his/her age',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq37 = list( Description = 'Your child has difficulty staying focused on his/her school work in the presence of an attractive alternative',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq38 = list( Description = 'Your child worries about things to the extent that academic performance is impaired',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq39 = list( Description = 'Your child engages in risky behavior to obtain a reward',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq40 = list( Description = 'Your child often refrains from doing something he/she likes in order not to be rejected or disapproved of by others',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq41 = list( Description = 'Your child likes competitive activities',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq42 = list( Description = 'Generally, your child pays more attention to threats than to pleasant events',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq43 = list( Description = 'Your child would like to be a socially powerful person',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq44 = list( Description = 'Your child often refrains from doing something because of fear of being embarrassed',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq45 = list( Description = 'Your child likes displaying his/her physical abilities even though it may involve danger',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq46 = list( Description = 'If your child thinks that something unpleasant is going to happen, he/she gets pretty worked up.',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq47 = list( Description = 'Your child craves excitement and new sensations',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq48 = list( Description = 'Criticism or scolding hurts your child very much',
                    Levels = list ('0' = 'Strongly Disagree',
                                   '1' = 'Disagree',
                                   '2' = 'Neither Agree Nor Disagree',
                                   '3' = 'Agree',
                                   '4' = 'Strongly Agree')),
    spsrq_fearshy = list( Description = 'Sensitivity to Punishment - Fear/Shy',
                          Derivative = TRUE),
    spsrq_anxiety = list( Description = 'Sensitivity to Punishment - Anxiety',
                          Derivative = TRUE),
    spsrq_conflictavoid = list( Description = 'Sensitivity to Punishment - Conflict Avoidant',
                                Derivative = TRUE),
    spsrq_impfun = list( Description = 'Sensitivity to Reward - Impulsivity/Fun Seeking',
                         Derivative = TRUE),
    spsrq_drive = list( Description = 'Sensitivity to Reward - Drive',
                        Derivative = TRUE),
    spsrq_socialapproval = list( Description = 'Sensitivity to Reward - Social Approval',
                                 Derivative = TRUE),
    spsrq_sensoryreward = list( Description = 'Sensitivity to Reward - Sensory Reward',
                                Derivative = TRUE))

  # convert formatting to JSON
  spsrq_json <- RJSONIO::toJSON(spsrq_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(spsrq_json, asText = TRUE))){
    print('spsrq JSON file may be invalid')
  }

  return(spsrq_json)

}
