#' json_intake: Generates a json file for intake data
#'
#' This function generates a json file for intake data
#'
#' @return A string with data stored in JSON format containing meta-data for intake data
#'
#'
#' @export

json_intake <- function() {

  intake_list <- list(
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1',
                                          '3' =	'Child visit protocol 3',
                                          '4' =	'Child visit protocol 4',
                                          '5'	= 'Child visit protocol 5')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                       Unit = 'YYYY-MM-DD'),

    # food_paradigm_info variables ----
    test_meal_book = list( Description = 'Book the child selected to listen to during the test meal'),
    test_meal_start_time = list( Description = 'Meal start time',
                                 Unit = "hh:mm"),
    test_meal_15_min_check = list( Description = 'Child was informed that there are 15 minutes remaining to eat their meal:',
                                   Levels = list ('1' =	'Yes',
                                                  '0'	= 'No')),
    test_meal_end_time = list( Description = 'Meal end time',
                               Unit = "hh:mm"),
    test_meal_duration = list( Description = 'Meal duration. Derived in redcap from test_meal_start_time and test_meal_end_time',
                               Derivative = TRUE),
    test_meal_notes = list( Description = 'Researcher notes about meal protocol'),
    meal_prep_notes = list( Description = 'Researcher notes about meal food preparation'),
    advertisement_condition = list( Description = 'Advertisement Condition',
                                    Levels = list ('0' =	'Food',
                                                   '1' =	'Toy',
                                                   '2'	= 'Boring')),
    eah_start_time = list( Description = 'EAH protocol start time',
                                 Unit = "hh:mm"),
    eah_end_time = list( Description = 'EAH protocol start time',
                                 Unit = "hh:mm"),
    eah_notes = list( Description = 'Researcher notes about EAH protocol'),
    eah_prep_notes = list( Description = 'Reseacher notes about EAH food preparation'),

    # VAS liking variables ----
    liking_popcorn = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this popcorn?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_pretzel = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this pretzel?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_corn_chip = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this corn chip?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_oreo = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this cookie?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    liking_brownie = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this brownie?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_starburst = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this Starburst?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_skittle = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this Skittle?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_chocolate = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this chocolate (Hershey Kiss)?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_icecream = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this ice cream?',
                            Levels = list ('0' =	'Hate it',
                                           '1'	= 'Dislike it',
                                           '2'	= 'It\'s okay',
                                           '3'	= 'Like it',
                                           '4'	= 'Love it')),
    liking_grilled_cheese = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this grilled cheese?',
                                  Levels = list ('0' =	'Hate it',
                                                 '1'	= 'Dislike it',
                                                 '2'	= 'It\'s okay',
                                                 '3'	= 'Like it',
                                                 '4'	= 'Love it')),
    liking_chicken_tender = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this chicken tender?',
                                  Levels = list ('0' =	'Hate it',
                                                 '1'	= 'Dislike it',
                                                 '2'	= 'It\'s okay',
                                                 '3'	= 'Like it',
                                                 '4'	= 'Love it')),
    liking_potato_chips = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this potato chip?',
                                Levels = list ('0' =	'Hate it',
                                               '1'	= 'Dislike it',
                                               '2'	= 'It\'s okay',
                                               '3'	= 'Like it',
                                               '4'	= 'Love it')),
    liking_carrot = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this baby carrot?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    liking_fruit = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this fruit cocktail',
                         Levels = list ('0' =	'Hate it',
                                        '1'	= 'Dislike it',
                                        '2'	= 'It\'s okay',
                                        '3'	= 'Like it',
                                        '4'	= 'Love it')),
    liking_water = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this water?',
                         Levels = list ('0' =	'Hate it',
                                        '1'	= 'Dislike it',
                                        '2'	= 'It\'s okay',
                                        '3'	= 'Like it',
                                        '4'	= 'Love it')),

    # EAH wanting variables ----

    eah_wanting_water = list( Description = 'EAH Wanting Questionnaire example: How much do you want to drink water right now?'),
    eah_wanting_corn_chips = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat corn chips right now?'),
    eah_wanting_pretzels = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat pretzels right now?'),
    eah_wanting_starburst = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Starbursts right now?'),
    eah_wanting_brownies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat brownies right now?'),
    eah_wanting_markers = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these markers right now?'),
    eah_wanting_crayons = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these crayons right now?'),
    eah_wanting_ice_cream = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat ice cream right now?'),
    eah_wanting_color_book_2 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_oonies_2 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this Oonies Inflator right now?'),
    eah_wanting_pencils = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these colored pencils right now?'),
    eah_wanting_activity_book = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this activity book right now?'),
    eah_wanting_oreos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Oreos right now?'),
    eah_wanting_popcorn = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat popcorn right now?'),
    eah_wanting_color_book_1 = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_legos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Legos right now?'),
    eah_wanting_squeakee = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Squeakee the Balloon Dog right now?'),
    eah_wanting_hershey_kiss = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Hershey kisses right now?'),
    eah_wanting_dinosaurs = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with dinosaurs right now?'),
    eah_wanting_oonies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Oonies right now?'),
    eah_wanting_skittles = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat skittles right now?'),


    # fullness variables ----
    pre_liking_fullness_time = list( Description = 'Pre-liking (i.e., before VAS liking ratings) fullness rating time',
                                  Unit = "hh:mm:ss"),
    pre_meal_ads_fullness_time = list( Description = 'Pre-meal-advertisement (i.e., efore the advertisement that preceeded the meal) fullness rating time',
                                       Unit = "hh:mm:ss"),
    pre_meal_fullness_time = list( Description = 'Pre-meal fullness rating time',
                                   Unit = "hh:mm:ss"),
    post_meal_fullness_time = list( Description = 'Post-meal fullness rating time',
                                    Unit = "hh:mm:ss"),

    pre_liking_fullness = list( Description = 'Pre-liking (i.e., before VAS liking ratings) fullness rating on a 150 mm visual analgue scale',
                             Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                             Unit = "mm"),

    pre_ad_meal_fullness = list( Description = 'Pre-meal-advertisement (i.e., before the advertisement that preceeded the meal) fullness rating on a 150 mm visual analgue scale',
                                 Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                                 Unit = "mm"),
    pre_meal_fullness = list( Description = 'Pre-meal fullness rating on a 150 mm visual analgue scale',
                              Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                              Unit = "mm"),
    post_meal_fullness = list( Description = 'Post-meal fullness rating on a 150 mm visual analgue scale',
                               Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                               Unit = "mm"),
    pre_ad_eah_fullness_time = list( Description = 'Pre-EAH-advertisement (i.e., before the advertisement that preceeded EAH) fullness fullness rating time',
                                     Unit = "hh:mm:ss"),
    pre_eah_fullness_time = list( Description = 'Pre-EAH fullness fullness rating time',
                                     Unit = "hh:mm:ss"),
    post_eah_fullness_time = list( Description = 'Post-EAH fullness fullness rating time',
                                   Unit = "hh:mm:ss"),
    pre_ad_eah_fullness = list( Description = 'Pre-EAH-advertisement (i.e., before the advertisement that preceeded EAH) fullness rating on a 150 mm visual analgue scale',
                                Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                                Unit = "mm"),
    pre_eah_fullness = list( Description = 'Pre-EAH fullness rating on a 150 mm visual analgue scale',
                             Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                             Unit = "mm"),
    post_eah_fullness = list( Description = 'Post-EAH fullness rating on a 150 mm visual analgue scale',
                              Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                              Unit = "mm"),

    # intake variables ----

    bread_pre_w_o_plate = list( Description = 'Pre-meal weight of bread (grilled cheese component) without plate',
                                Unit = "grams"),
    butter_pre_w_o_plate = list( Description = 'Pre-meal weight of butter (grilled cheese component) on bread slice A without plate',
                                 Unit = "grams"),
    butter_2_pre_w_o_plate = list( Description = 'Pre-meal weight of butter (grilled cheese component) on bread slice B without plate',
                                   Unit = "grams"),
    cheese_pre_w_o_plate = list( Description = 'Pre-meal weight of cheese (grilled cheese component) without plate',
                                 Unit = "grams"),

    grilled_cheese_pre_w_o_plate = list( Description = 'Pre-meal weight of grilled cheese without plate',
                                         Unit = "grams"),
    grilled_cheese_pre_w_plate = list( Description = 'Pre-meal weight of grilled cheese with plate',
                                       Unit = "grams"),
    grilled_cheese_post_w_plate = list( Description = 'Post-meal weight of grilled cheese with plate',
                                        Unit = "grams"),

    tender_pre_w_o_plate = list( Description = 'Pre-meal weight of chicken tender without plate',
                                 Unit = "grams"),
    tender_pre_w_plate = list( Description = 'Pre-meal weight of chicken tender with plate',
                               Unit = "grams"),
    tender_post_w_plate = list( Description = 'Post-meal weight of chicken tender with plate',
                                Unit = "grams"),

    carrot_pre_w_o_plate = list( Description = 'Pre-meal weight of carrots without plate',
                                 Unit = "grams"),
    carrot_pre_w_plate = list( Description = 'Pre-meal weight of carrots with plate',
                               Unit = "grams"),
    carrot_post_w_plate = list( Description = 'Post-meal weight of carrots with plate',
                                Unit = "grams"),

    chips_pre_w_o_plate = list( Description = 'Pre-meal weight of potato chips without plate',
                                Unit = "grams"),
    chips_pre_w_plate = list( Description = 'Pre-meal weight of potato chips with plate',
                              Unit = "grams"),
    chips_post_w_plate = list( Description = 'Post-meal weight of potato chips with plate',
                               Unit = "grams"),

    fruit_pre_w_o_plate = list( Description = 'Pre-meal weight of fruit cocktail without plate',
                                Unit = "grams"),
    fruit_pre_w_plate = list( Description = 'Pre-meal weight of fruit cocktail with plate',
                              Unit = "grams"),
    fruit_post_w_plate = list( Description = 'Post-meal weight of fruit cocktail with plate',
                               Unit = "grams"),

    water_pre_w_o_plate = list( Description = 'Pre-meal weight of water without container',
                                Unit = "grams"),
    water_pre_w_plate = list( Description = 'Pre-meal weight of water with container',
                              Unit = "grams"),
    water_post_w_plate = list( Description = 'Post-meal weight of water with container',
                               Unit = "grams"),

    ranch_pre_w_o_plate = list( Description = 'Pre-meal weight of ranch dressing without container',
                                Unit = "grams"),
    ranch_pre_w_plate = list( Description = 'Pre-meal weight of ranch dressing with container',
                              Unit = "grams"),
    ranch_post_w_plate = list( Description = 'Post-meal weight of ranch dressing with container',
                               Unit = "grams"),

    ketchup_pre_w_o_plate = list( Description = 'Pre-meal weight of ketchup without container',
                                Unit = "grams"),
    ketchup_pre_w_plate = list( Description = 'Pre-meal weight of ketchup with container',
                              Unit = "grams"),
    ketchup_post_w_plate = list( Description = 'Post-meal weight of ketchup with container',
                               Unit = "grams"),

    brownie_pre_w_o_plate = list( Description = 'Pre-EAH weight of brownies without plate',
                                  Unit = "grams"),
    brownie_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                Unit = "grams"),
    brownie_post_w_plate = list( Description = 'Post-EAH weight of brownies with plate',
                                 Unit = "grams"),

    corn_chip_pre_w_o_plate = list( Description = 'Pre-EAH weight of corn chips without plate',
                                    Unit = "grams"),
    corn_chip_pre_w_plate = list( Description = 'Pre-EAH weight of corn chips with plate',
                                  Unit = "grams"),
    corn_chip_post_w_plate = list( Description = 'Post-EAH weight of corn chips with plate',
                                   Unit = "grams"),

    kiss_pre_w_o_plate = list( Description = 'Pre-EAH weight of Hersheys kiss without plate',
                               Unit = "grams"),
    kiss_pre_w_plate = list( Description = 'Pre-EAH weight of Hersheys kiss with plate',
                             Unit = "grams"),
    kiss_post_w_plate = list( Description = 'Post-EAH weight of Hersheys kiss with plate',
                              Unit = "grams"),

    ice_cream_pre_w_o_plate = list( Description = 'Pre-EAH weight of Ice cream without plate',
                                    Unit = "grams"),
    ice_cream_pre_w_plate = list( Description = 'Pre-EAH weight of Ice cream with plate',
                                  Unit = "grams"),
    ice_cream_post_w_plate = list( Description = 'Post-EAH weight of Ice cream with plate',
                                   Unit = "grams"),

    oreo_pre_w_o_plate = list( Description = 'Pre-EAH weight of oreos without plate',
                                    Unit = "grams"),
    oreo_pre_w_plate = list( Description = 'Pre-EAH weight of oreos with plate',
                                  Unit = "grams"),
    oreo_post_w_plate = list( Description = 'Post-EAH weight of oreos with plate',
                                   Unit = "grams"),

    popcorn_pre_w_o_plate = list( Description = 'Pre-EAH weight of popcorn without plate',
                               Unit = "grams"),
    popcorn_pre_w_plate = list( Description = 'Pre-EAH weight of popcorn with plate',
                             Unit = "grams"),
    popcorn_post_w_plate = list( Description = 'Post-EAH weight of popcorn with plate',
                              Unit = "grams"),

    pretzel_pre_w_o_plate = list( Description = 'Pre-EAH weight of pretzels without plate',
                                  Unit = "grams"),
    pretzel_pre_w_plate = list( Description = 'Pre-EAH weight of pretzels with plate',
                                Unit = "grams"),
    pretzel_post_w_plate = list( Description = 'Post-EAH weight of pretzels with plate',
                                 Unit = "grams"),

    skittle_pre_w_o_plate = list( Description = 'Pre-EAH weight of skittles without plate',
                                  Unit = "grams"),
    skittle_pre_w_plate = list( Description = 'Pre-EAH weight of skittles with plate',
                                Unit = "grams"),
    skittle_post_w_plate = list( Description = 'Post-EAH weight of skittles with plate',
                                 Unit = "grams"),

    starburst_pre_w_o_plate = list( Description = 'Pre-EAH weight of starbursts without plate',
                                  Unit = "grams"),
    starburst_pre_w_plate = list( Description = 'Pre-EAH weight of starbursts with plate',
                                Unit = "grams"),
    starburst_post_w_plate = list( Description = 'Post-EAH weight of starbursts with plate',
                                 Unit = "grams"),

    water_eah_pre_w_o_plate = list( Description = 'Pre-EAH weight of water without container',
                                    Unit = "grams"),
    water_eah_pre_w_plate = list( Description = 'Pre-EAH weight of water with container',
                                  Unit = "grams"),
    water_eah_post_w_plate = list( Description = 'Post-EAH weight of water with container',
                                   Unit = "grams"),

    # derivatives: grilled cheese components

    butter_pre_kcal = list( Description = 'Energy content of butter component for grilled cheese. Computed by multiplying (butter_pre_w_o_plate + butter_2pre_w_o_plate) by butter energy density',
                            Derivative = TRUE,
                            Unit = "kcal"),
    bread_pre_kcal = list( Description = 'Energy content of bread component for grilled cheese. Computed by multiplying bread_pre_w_o_plate by bread energy density',
                          Derivative = TRUE,
                           Unit = "kcal"),
    cheese_pre_kcal = list( Description = 'Energy content of cheese component for grilled cheese. Computed by multiplying cheese_pre_w_o_plate by bread energy density',
                           Derivative = TRUE,
                           Unit = "kcal"),
    grilled_cheese_pre_kcal = list( Description = 'Energy content of grilled cheese. Computed by summing butter_pre_kcal, bread_pre_kcal, cheese_pre_kcal',
                            Derivative = TRUE,
                            Unit = "kcal"),
    grilled_cheese_ed = list( Description = 'Energy density of grilled cheese. Computed by dividing grilled_cheese_pre_kcal by grilled_cheese_pre_w_o_plate',
                              Derivative = TRUE,
                              Unit = "kcal/g"),

    # derivatives: _consumed vars
    grilled_cheese_g_consumed = list( Description = 'Weight of grilled_cheese consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                              Derivative = TRUE,
                              Unit = "grams"),
    grilled_cheese_kcal_consumed = list( Description = 'Energy of grilled_cheese consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                         Derivative = TRUE,
                                         Unit = "kcal"),
    tender_g_consumed = list( Description = 'Weight of chicken tender consumed during test meal Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                          Derivative = TRUE,
                                          Unit = "grams"),
    tender_kcal_consumed = list( Description = 'Energy of chicken tender consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                         Derivative = TRUE,
                                         Unit = "kcal"),
    carrot_g_consumed = list( Description = 'Weight of carrots consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    carrot_kcal_consumed = list( Description = 'Energy of carrots consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    chips_g_consumed = list( Description = 'Weight of chips consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    chips_kcal_consumed = list( Description = 'Energy of chips consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    fruit_g_consumed = list( Description = 'Weight of fruit consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    fruit_kcal_consumed = list( Description = 'Energy of fruit consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    water_g_consumed = list( Description = 'Weight of water consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    water_kcal_consumed = list( Description = 'Energy of water consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ranch_g_consumed = list( Description = 'Weight of ranch consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ranch_kcal_consumed = list( Description = 'Energy of ranch consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ketchup_g_consumed = list( Description = 'Weight of ketchup consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ketchup_kcal_consumed = list( Description = 'Energy of ketchup consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    brownie_g_consumed = list( Description = 'Weight of brownies consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    brownie_kcal_consumed = list( Description = 'Energy of brownies consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    corn_chip_g_consumed = list( Description = 'Weight of corn chips consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    corn_chip_kcal_consumed = list( Description = 'Energy of corn chips consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    kiss_g_consumed = list( Description = 'Weight of Hershey\'s kisses consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    kiss_kcal_consumed = list( Description = 'Energy of Hershey\'s kisses consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ice_cream_g_consumed = list( Description = 'Weight of ice cream consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                  Derivative = TRUE,
                                  Unit = "grams"),
    ice_cream_kcal_consumed = list( Description = 'Energy of ice cream consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    oreo_g_consumed = list( Description = 'Weight of oreos consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    oreo_kcal_consumed = list( Description = 'Energy of oreos consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    popcorn_g_consumed = list( Description = 'Weight of popcorn consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                Derivative = TRUE,
                                Unit = "grams"),
    popcorn_kcal_consumed = list( Description = 'Energy of popcorn consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                               Derivative = TRUE,
                               Unit = "kcal"),
    pretzel_g_consumed = list( Description = 'Weight of pretzels consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    pretzel_kcal_consumed = list( Description = 'Energy of pretzels consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    skittle_g_consumed = list( Description = 'Weight of skittles consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                   Derivative = TRUE,
                                   Unit = "grams"),
    skittle_kcal_consumed = list( Description = 'Energy of skittles consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    starburst_g_consumed = list( Description = 'Weight of starbursts consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                   Derivative = TRUE,
                                   Unit = "grams"),
    starburst_kcal_consumed = list( Description = 'Energy of starbursts consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    water_eah_g_consumed = list( Description = 'Weight of water consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    water_eah_kcal_consumed = list( Description = 'Energy of water consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    meal_g_consumed = list( Description = 'Total weight of food consumed during test meal (does not include water)',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    meal_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during test meal',
                                Derivative = TRUE,
                                Unit = "grams"),
    meal_kcal_consumed = list( Description = 'Total energy of food consumed during test meal',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    eah_g_consumed = list( Description = 'Total weight of food consumed during EAH (does not include water)',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    eah_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during EAH',
                                          Derivative = TRUE,
                                          Unit = "grams"),
    eah_kcal_consumed = list( Description = 'Total energy of food consumed during EAH',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    total_g_consumed = list( Description = 'Total weight of food consumed during test meal and EAH (does not include water)',
                               Derivative = TRUE,
                               Unit = "grams"),
    total_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during test meal and EAH',
                                 Derivative = TRUE,
                                 Unit = "grams"),
    totak_kcal_consumed = list( Description = 'Total energy of food consumed during test meal and EAH',
                              Derivative = TRUE,
                              Unit = "kcal")
  )

  # convert formatting to JSON
  intake_json <- RJSONIO::toJSON(intake_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(intake_json, asText = TRUE))){
    print('Intake visit JSON file may be invalid')
  }

  return(intake_json)

}
