#' json_pmum: Generates a json file for the Problematic Media Use Measure
#'
#' This function generates a json file for the scored Problematic Media Use Measure and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_pmum function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Problematic Media Use Measure
#'
#'
#' @export

json_pmum <- function() {

  pmum_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Problematic Media Use Measure. Participants were provided the following instructions: "Please respond to each statement about your child\'s media use with Never, Rarely, Sometimes, Mostly or Always."',
      Reference = 'Domoff SE, Harrison K, Gearhardt AN, Gentile DA, Lumeng JC, Miller AL. Development and Validation of the Problematic Media Use Measure: A Parent Report Measure of Screen Media "Addiction" in Children. Psychol Pop Media Cult. 2019 Jan;8(1):2-11. doi: 10.1037/ppm0000163. Epub 2017 Nov 16. PMID: 30873299; PMCID: PMC6411079.',
      TermURL = 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6411079/'),
    participant_id = list( Description = 'participant id number'),
    pmum1 = list( Description = 'My child lies in order to use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum2 = list( Description = 'My child uses screen media to feel better.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum3 = list( Description = 'My child loses sleep due to screen media.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum4 = list( Description = 'My child uses screen media for increasing amounts of time',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum5 = list( Description = 'My child sneaks using screen media',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum6 = list( Description = 'My child lies about doing chores or school work in order to use screen media.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum7 = list( Description = 'My child feels better when he/she uses screen media.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum8 = list( Description = 'Screen media is all my child tends to think about.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum9 = list( Description = 'My child\'s screen media use negatively affects his/her friendships.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    pmum10 = list( Description = 'My child attempts to use screen media for increasing amounts of time.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum11 = list( Description = 'It is hard for my child to stop using screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum12 = list( Description = 'When my child has had a bad day, screen media seems to be the only thing that helps him/her feel better.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum13 = list( Description = 'There is nothing my child enjoys as much as screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum14 = list( Description = 'My child is always thinking about using screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum15 = list( Description = 'My child\'s screen media use causes problems for the family.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum16 = list( Description = 'The amount of time my child wants to use screen media keeps increasing.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum17 = list( Description = 'The first thing my child asks to do when he/she comes home from school is to use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum18 = list( Description = 'My child would find life boring without screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum19 = list( Description = 'My child gets upset when he/she cannot use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum20 = list( Description = 'Screen media is the only thing that seems to motivate my child.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum21 = list( Description = 'Problems occur for our family when my child cannot use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum22 = list( Description = 'It is really difficult to get my child to stop using screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum23 = list( Description = 'My child becomes angry when he/she cannot use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum24 = list( Description = 'Life would be easier if my child was not so attached to screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum25 = list( Description = 'It is increasingly difficult to pull my child away from screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum26 = list( Description = 'My child becomes frustrated when he/she cannot use screen media.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum27 = list( Description = 'My child\'s screen media use interferes with family activities.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    pmum_total = list( Description = 'Problematic Media Use Measure Score',
                        Derivative = TRUE))

  # convert formatting to JSON
  pmum_json <- RJSONIO::toJSON(pmum_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(pmum_json, asText = TRUE))){
    print('pmum JSON file may be invalid')
  }

  return(pmum_json)

}
