#' json_rank: Generates a json file for the Ranking Food Item Questionnaire
#'
#' This function generates a json file for the (scored?) Ranking Food Item Questionnaire and raw participant responses.
#' This function provides accurate json files ONLY if data is processed using score_rank function in dataprepr and is only accurate for data collected in Study REACH
#'
#' @return A json file documenting the raw inputs and scored values for the Ranking Food Item Questionnaire
#'
#'
#' @export

json_rank <- function() {

  rank_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Ranking Food Item Questionnaire',
      Reference = '',
      TermURL = ''),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                    Levels = list ('ses-1' = 'session 1 / baseline',
                                   'ses-2' = 'session 2 / follow-up')),
    visit = list( Description = 'REACH visit protocol for data collection'),
    rank1 = list(Description = 'Pre-packaged bread items, such as sandwich bread, hamburger buns, hotdog rolls, muffins, or bagels',
                 Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank2 = list( Description = 'Bakery breads or other freshly made goods, such as cake, cookies, or doughnuts',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank3 = list( Description = 'Salty snacks, such as chips, crackers, popcorn, or jerky',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank4 = list( Description = 'Sweet snacks, such as cookies or cakes',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank5 = list( Description = 'Cheese',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank6 = list( Description = 'Milk',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank7 = list( Description = 'Yogurt',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank8 = list( Description = 'Butter, margarine, or other butter substitutes',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank9 = list( Description = 'Eggs',
                  Levels = list('0' = 'Very Important',
                                '1' = 'Important',
                                '2' = 'Moderately Important',
                                '3' = 'Slightly Important',
                                '4' = 'Not Important at all')),
    rank10 = list( Description = 'Other dairy products, such as sour cream',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank11 = list( Description = 'Coffee or tea',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank12 = list( Description = 'Soda or other carbonated beverages',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank13 = list( Description = 'Fruit juices or beverages, such as orange juice or apple cider',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank14 = list( Description = 'Sports drinks, such as Gatorade or Powerade',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank15 = list( Description = 'Alcoholic beverages, such as beer or wine',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank16 = list( Description = 'Red meat, such as beef, pork, or lamb',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank17 = list( Description = 'Poultry, such as chicken or turkey',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank18 = list( Description = 'Seafood, such as shrimp, salmon, tilapia, tuna, crab, or lobster',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank19 = list( Description = 'Pasta, noodles, or rice, such as fettuccine, lasagna, white rice, or brown rice',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank20 = list( Description = 'Soup, such as chicken noodle or tomato',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank21 = list( Description = 'Nuts and seeds, such as peanuts, almonds, walnuts, or sunflower seeds',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank22 = list( Description = 'Nut butters, jelly and honey, such as peanut or almond butter; or strawberry or grape jelly',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank23 = list( Description = 'Breakfast cereals, such as oatmeal or cornflakes',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank24 = list( Description = 'Breakfast, meal replacement, or protein bars, such as Luna, Cliff, Quest, Quaker, or Nature Valley bars',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank25 = list( Description = 'Meal replacement shakes or protein powder, such as Glucerna shakes or Muscle Milk',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank26 = list( Description = 'Fresh prepared foods, such as pizza or salad bar entrees',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank27 = list( Description = 'Fresh vegetables, such as spinach, carrots, or broccoli',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank28 = list( Description = 'Fresh fruits, such as strawberries, apples, or oranges',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank29 = list( Description = 'Canned vegetables',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank30 = list( Description = 'Canned fruits',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank31 = list( Description = 'Frozen vegetables',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank32 = list( Description = 'Frozen fruits',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank33 = list( Description = 'Frozen dinner items, such as pizza, macaroni and cheese, or French fries',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank34 = list( Description = 'Frozen breakfast items, such as waffles',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank35 = list( Description = 'Frozen desserts, such as cakes or pies',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank36 = list( Description = 'Candy or gum, such as chocolate, caramel, or toffee',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank37 = list( Description = 'Baking supplies, such as flour, sugar, or baking soda',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank38 = list( Description = 'Condiments or sauces, such as ketchup, mustard, mayonnaise, tomato sauce, barbeque sauce, or hot sauce',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank39 = list( Description = 'Dips or spreads, such as hummus, French onion dip, or ranch dip',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank40 = list( Description = 'Salad dressings or toppings, such as oil and vinegar, ranch, honey mustard, or croutons',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank41 = list( Description = 'Spices and seasonings, such as salt, pepper, cinnamon, basil, or oregano',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank42 = list( Description = '',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all')),
    rank42 = list( Description = 'Oil, cooking spray, or shortening, such as olive oil or coconut oil',
                   Levels = list('0' = 'Very Important',
                                 '1' = 'Important',
                                 '2' = 'Moderately Important',
                                 '3' = 'Slightly Important',
                                 '4' = 'Not Important at all'))
    )

  # convert formatting to JSON
  rank_json <- RJSONIO::toJSON(rank_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(rank_json, asText = TRUE))){
    print('rank JSON file may be invalid')
  }

  return(rank_json)

}
