#' json_scpf: Generates a json file for the Structure and Control in Parent Feeding questionnaire
#'
#' This function generates a json file for the scored Structure and Control in Parent Feeding questionnaire and raw participant responses.
#'
#' @return A string with data stored in JSON format containing meta-data for the Structure and Control in Parent Feeding questionnaire
#'
#'
#' @export

json_scpf <- function() {

  scpf_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Structure and Control in Parent Feeding questionnaire. This scale had an error when administered, see description of scpf17. Participants were provided the following instructions: "Please select your response to indicate how often these things happen."',
      Reference = 'Savage, J.S., Rollins, B.Y., Kugler, K.C. et al. Development of a theory-based questionnaire to assess structure and control in parent feeding (SCPF). Int J Behav Nutr Phys Act 14, 9 (2017). https://doi.org/10.1186/s12966-017-0466-2',
      TermURL = 'https://ijbnpa.biomedcentral.com/articles/10.1186/s12966-017-0466-2'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-1' = 'session 1 / baseline',
                                      'ses-2' = 'session 2 / follow-up')),
    visit_date = list( Description = 'Date of visit this parent-reported survey was completed',
                        Unit = 'YYYY-MM-DD'),
    scpf1 = list( Description = 'I avoid buying sweets or desserts I don\'t want my child to eat.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf2 = list( Description = 'I let my child eat sweets (ex. cookies, cake, candy, freeze pops, ice cream) anytime during the day.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf3 = list( Description = 'I avoid eating snacks or sweets in front of my child that I don\'t want him/her to eat.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf4 = list( Description = 'I serve my child sweets or desserts (ex. cookies, cake, candy, freeze pops, ice cream).',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf5 = list( Description = 'I have clear rules about when my child can eat snacks or sweets.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf6 = list( Description = 'I serve my child sugar sweetened drinks (ex. fruit drink, soda, iced tea, or sports/energy drinks).',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf7 = list( Description = 'I serve small child-size helpings at snacks.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf8 = list( Description = 'I keep a lot of snack foods (potato chips, cheese puffs, tortilla chips) in my house.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf9 = list( Description = 'I hide foods that I don\'t want my child to eat.',
                  Levels = list ('0' = 'Never',
                                 '1' = 'Rarely',
                                 '2' = 'Sometimes',
                                 '3' = 'Often',
                                 '4' = 'Always')),
    scpf10 = list( Description = 'If my child is eating too much I take some of it away.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf11 = list( Description = 'I avoid taking my child to places where he/she might ask me for sweets, snacks, or junk food.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf12 = list( Description = 'I get upset when my child eats too many sweets and salty foods without asking.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf13 = list( Description = 'I serve my child French fries.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf14 = list( Description = 'When my child is drinking too much of a sugar-sweetened  beverage, I take the cup/bottle away or pour some out.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf15 = list( Description = 'I have my child sit down in a chair/highchair at home when  eating meals.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf16 = list( Description = 'I let my child eat snack foods anytime during the day.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf17 = list( Description = 'This item should have been "If I did not control my child\'s eating, s/he would eat much less than s/he should." but was erroneously replaced with "I give snacks or drinks as a way to distract and keep my child quiet when my child is sad or upset." Therefore, data for scpf17 have been marked as missing.'),
    scpf18 = list( Description = 'If my child seems full, I encourage him/her to finish his/her food anyway.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf19 = list( Description = 'I praise my child after each bite to encourage him/her to finish his/her food.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf20 = list( Description = 'I keep a lot of fresh fruits and vegetables in my home.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf21 = list( Description = 'I try to get my child to finish his/her food.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf22 = list( Description = 'I keep a lot of sweets/desserts (candy, ice cream, cake, pies, pastries) in my home.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf23 = list( Description = 'I serve my child a green, yellow, or orange vegetable each day.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf24 = list( Description = 'I try to get my child to eat even if s/he doesn\'t seem hungry or says "I\'m not hungry."',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf25 = list( Description = 'I have very firm rules about what types of foods I allow my child to have (with no exceptions).',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf26 = list( Description = 'My child eats at scheduled meal and snack times, not in between.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf27 = list( Description = 'I serve small child-size helpings at meals.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf28 = list( Description = 'My child eats breakfast at about the same time and place (e.g., at kitchen  table or at school each morning).',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf29 = list( Description = 'I have to trick, distract, play with, or praise my child to get him/ her to finish his/her food.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf30 = list( Description = 'My child eats dinner at about the same time each night (within 15 minutes).',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf31 = list( Description = 'I let my child have sugar sweetened drinks (ex. fruit drink, soda, iced tea, or sports/energy drinks) anytime during the day.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf32 = list( Description = 'I do not allow other people to give sweets and snacks to my child without asking me.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf33 = list( Description = 'I try not to eat unhealthy foods when my child is around.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf34 = list( Description = 'In my home, I hide snack foods from my child that I don\'t want my child to eat.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Rarely',
                                  '2' = 'Sometimes',
                                  '3' = 'Often',
                                  '4' = 'Always')),
    scpf_limit_exp = list( Description = 'Limit Exposure',
                           Derivative = TRUE),
    scpf_consistent = list( Description = 'Consistent feeding routines',
                          Derivative = TRUE),
    scpf_restriction = list( Description = 'Restriction',
                            Derivative = TRUE),
    scpf_pressure = list( Description = 'Pressure',
                            Derivative = TRUE)
  )


  # convert formatting to JSON
  scpf_json <- RJSONIO::toJSON(scpf_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(scpf_json, asText = TRUE))){
    print('scpf JSON file may be invalid')
  }

  return(scpf_json)

}
