#' qc_redcap: Check raw and processed redcap data for quality issues
#'
#' This function checks processed redcap data for the following qualities:
#' \itemize{
#'  \item{Duplicate data:}
#'  \itemize{
#'     \item{Checks participant dataframe for duplicate subject IDs}
#'     \item{Checks intake dataframe for duplicate subject + visit combinations}
#'     \item{Checks puberty dataframe for duplicate subject + session + respondent combinations}
#'     \item{Checks all other dataframes for duplicate subject and session combinations}
#'  }
#'  \item{Data types:}
#'  \itemize{
#'     \item{ ?? Checks that raw intake data (pre and post-weights) are numerical. These columns are converted to numeric in data processing pipeline and non-numeric data would be converted to NA}
#'     \item{Checks LOC data: }
#'   }
#'  \item{Data values:}
#'  \itemize{
#'     \item{Checks participant dataframe for child ages outside 7-9}
#'     \item{Checks intake dataframe for negative consumption variables}
#'   }
#'  \item{Missing data:}
#'  \itemize{
#'     \item{}
#'   }
#' }
#'
#' @param redcap_data list of lists of dataframes. This is generated by proc_redcap(return = TRUE)
#'
#' @examples
#'
#' \dontrun{
#'
#' # return data from proc_redcap()
#' redcap_data <- proc_redcap(visit_data_path, data_de_path, return = TRUE)
#'
#' # run QC on phenotype_data in redcap_data
#' qc_redcap(redcap_data)
#'
#' }
#' @export
qc_redcap <- function(redcap_data) {

  #### Set up/initial checks #####

  # check that phenotype_data exist and is a list of data.frames
  data_arg <- methods::hasArg(redcap_data)

  if (isTRUE(data_arg)) {
    if (!is.list(redcap_data)) {
      stop("redcap_data must be a list of lists of dataframes. It is the output of proc_redcap(return=TRUE)")
    }
  } else if (isFALSE(data_arg)) {
    stop("must specify redcap_data arg")
  }

  # extract data
  phenotype_data <- redcap_data$phenotype_data

  #### Quality check: duplicate data #####

  for (df_name in names(phenotype_data)) {

    # extract dataframe
    df <- phenotype_data[[df_name]]

    # check participants dataframe for duplicate subs
    if (df_name == "participants" | df_name == "researcher_notes") {

      # extract rows with duplicate subs
      duplicate_rows <- df[duplicated(df[c("participant_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Warning: Duplicate participant_id rows in ", df_name))
        print(duplicate_rows)
      }

      # check intake dataframe for duplicate subs and visit
    } else if (df_name == "intake") {

      # extract rows with duplicate sub and visit combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "visit_protocol")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Warning: Duplicate participant_id+visit_protocol rows in ", df_name))

      }

      # check puberty dataframe for duplicate sub, ses, and respondent
    } else if (df_name == "puberty") {

      # extract rows with duplicate sub visit, and respondent combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id", "respondent")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Warning: Duplicate participant_id+session_id+respondent rows in ", df_name))
      }

    } else if (df_name == "parent_updates") {

      # extract rows with duplicate sub visit, and respondent combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "update_form_date")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Warning: Duplicate participant_id+session_id+update_form_date rows in ", df_name))
      }

      # check all other dataframes for duplicate sub + ses combinations
    } else {

      # extract rows with duplicate sub and ses combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Warning: Duplicate participant_id+session_id rows in ", df_name))
      }

    }

  }

  #### Quality check: data types #####

  ### check input intake data

  ## note: checking processed data doesnt make sense - these columns are converted to numeric during processing to enable computations
  # if (!is.null(phenotype_data$intake)) {
  #
  #   # extract intake data
  #   intake_data <- phenotype_data$intake
  #
  #   # define intake columns to check
  #   intake_vars <- grep('post_w_plate|pre_w_o_plate|pre_w_plate', names(intake_data), value = TRUE)
  #
  #   # identify non-numeric columns
  #   non_numeric_cols <- sapply(intake_data[c(intake_vars)], function(col) !is.numeric(col))
  #
  #
  # } else {
  #
  #     cat("intake dataframe (phenotype_data$intake) not included in redcap_data")  #
  # }

  #### Quality check: data values #####

  # participants data
  if (!is.null(phenotype_data$participants)) {

    # extract v1 age data
    ages <- phenotype_data$participants[c("participant_id", "child_protocol_1_age")]

    if (min(ages$child_protocol_1_age, na.rm = TRUE) < 7) {
      cat("Warning: minimum child_protocol_1_age in participants_data is below expected value (7). Check birthdates and visit dates. \n")
      subset[!is.na(ages$child_protocol_1_age) & ages$child_protocol_1_age < 7, ]

    }

    if (max(ages$child_protocol_1_age, na.rm = TRUE) >= 10) {
      cat("Warning: minimum child_protocol_1_age in participants_data is above expected value (>=10). Check birthdates and visit dates. \n")
      subset[!is.na(ages$child_protocol_1_age) & ages$child_protocol_1_age >= 10, ]
    }

  } else {

    cat("Participant dataframe (phenotype_data$participants) not included in redcap_data")

  }

  # intake data
  if (!is.null(phenotype_data$intake)) {

    # define consumption (g) vars
    consumption_vars <- grep('grams_consumed', names(phenotype_data$intake), value = TRUE)

    for (consumption_var in consumption_vars) {

      # extract grams consumed for given item
      item_intake_data <- phenotype_data$intake[c("participant_id", "visit_protocol", consumption_var)]

      # extract rows with values below 0
      negative_rows <- item_intake_data[!is.na(item_intake_data[[consumption_var]]) & item_intake_data[[consumption_var]] < 0, ]

      if (nrow(negative_rows) > 0) {
        cat(paste0("Warning: Negative consumption values in intake data variable: ", consumption_var, ". Check pre and post-weights. \n"))
        print(negative_rows)
      }

    }


  } else {

    cat("Participant dataframe (phenotype_data$participants) not included in redcap_data")

  }
  #### Quality check: missing data #####


}

