#' qc_redcap: Check raw and processed redcap data for quality issues
#'
#' This function checks processed redcap data for the following qualities:
#' \itemize{
#'  \item{Duplicate data:}
#'  \itemize{
#'     \item{Checks participant dataframe for duplicate subject IDs}
#'     \item{Checks intake dataframe for duplicate subject + visit combinations}
#'     \item{Checks puberty dataframe for duplicate subject + session + respondent combinations}
#'     \item{Checks all other dataframes for duplicate subject and session combinations}
#'  }
#'  \item{Data types:}
#'  \itemize{
#'     \item{ ?? Checks that raw intake data (pre and post-weights) are numerical. These columns are converted to numeric in data processing pipeline and non-numeric data would be converted to NA}
#'     \item{Checks LOC data: }
#'   }
#'  \item{Data values:}
#'  \itemize{
#'     \item{Checks participant dataframe for child ages outside 7-9}
#'     \item{Checks intake dataframe for negative consumption variables}
#'   }
#'  \item{Missing data:}
#'  \itemize{
#'     \item{}
#'   }
#' }
#'
#' @param phenotype_data a list of phenotype dataframes generated by proc_redcap()
#'
#' @examples
#'
#' \dontrun{
#'
#' # return data from proc_redcap()
#' redcap_data <- proc_redcap(visit_data_path, data_de_path, return = TRUE)
#'
#' # run QC on phenotype_data in redcap_data
#' qc_redcap(redcap_data)
#'
#' }
qc_redcap <- function(redcap_data) {

  #### Set up/initial checks #####

  # check that phenotype_data exist and is a list of data.frames
  data_arg <- methods::hasArg(phenotype_data)

  if (isTRUE(data_arg)) {
    if (!is.list(phenotype_data)) {
      stop("phenotype_data must be a list of dataframes")
    }
  } else if (isFALSE(data_arg)) {
    stop("must specify phenotype_data arg")
  }

  # extract data
  phenotype_data <- redcap_data$phenotype_data
  phenotype_data <- redcap_data$phenotype_data

  #### Quality check: duplicate data #####

  for (df_name in names(phenotype_data)) {

    # extract dataframe
    df <- phenotype_data[[df_name]]

    # check participants dataframe for duplicate subs
    if (df_name == "participants") {

      # extract rows with duplicate subs
      duplicate_rows <- df[duplicated(df[c("participant_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id rows in ", df_name))
        print(duplicate_rows)
      }

      # check intake dataframe for duplicate subs and visit
    } else if (df_name == "intake") {

      # extract rows with duplicate sub and visit combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "visit_protocol")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+visit_protocol rows in ", df_name))

      }

      # check puberty dataframe for duplicate sub, ses, and respondent
    } else if (df_name == "puberty") {

      # extract rows with duplicate sub visit, and respondent combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id", "respondent")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+session_id+respondent rows in ", df_name))
      }

      # check all other dataframes for duplicate sub + ses combinations
    } else {

      # extract rows with duplicate sub and ses combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+session_id rows in ", df_name))
      }

    }

  }

  #### Quality check: data types #####

  ### check input intake data

  ## note: checking processed data doesnt make sense - these columns are converted to numeric during processing to enable computations
  # if (!is.null(phenotype_data$intake)) {
  #
  #   # extract intake data
  #   intake_data <- phenotype_data$intake
  #
  #   # define intake columns to check
  #   intake_vars <- grep('post_w_plate|pre_w_o_plate|pre_w_plate', names(intake_data), value = TRUE)
  #
  #   # identify non-numeric columns
  #   non_numeric_cols <- sapply(intake_data[c(intake_vars)], function(col) !is.numeric(col))
  #
  #
  # } else {
  #
  #     cat("intake dataframe (phenotype_data$intake) not included in redcap_data")  #
  # }

  #### Quality check: data values #####

  # participants data
  if (!is.null(phenotype_data$participants)) {

    # extract data
    participants_data <- phenotype_data$participants

    # check age
    if (min(participants_data$child_protocol_1_age, na.rm = TRUE) < 7) {
      cat("minimum child_protocol_1_age in participants_data is below expected value (7). Check birthdates and visit dates")
    }

    if (max(participants_data$child_protocol_1_age, na.rm = TRUE) >= 10) {
      cat("minimum child_protocol_1_age in participants_data is above expected value (>=10). Check birthdates and visit dates")
    }

  } else {

    cat("Participant dataframe (phenotype_data$participants) not included in redcap_data")

  }

  # intake data
  if (!is.null(phenotype_data$intake)) {

    # extract data
    intake_data <- phenotype_data$intake

    # define consumption (g) vars
    consumption_vars <- grep('grams_consumed', names(intake_data), value = TRUE)

    var = "tender_grams_consumed"
    for (var in consumption_vars) {

      subset <- intake_data[c("participant_id", "visit_protocol", var)]

      # extract rows with values below 0
      negative_rows <- subset[!is.na(subset[[var]]) & subset[[var]] < 0, ]

      if (nrow(negative_rows) > 0) {
        cat(paste0("Negative consumption values in intake data variable: ", var, ". Check pre and post-weights. \n"))
        print(negative_rows)
      }

    }


  } else {

    cat("Participant dataframe (phenotype_data$participants) not included in redcap_data")

  }
  #### Quality check: missing data #####


}

