#' qc_redcap: Check processed redcap data for quality issues
#'
#' This function checks processed redcap data for the following qualities:
#' \itemize{
#'  \item{Duplicate data:}
#'  \itemize{
#'     \item{Checks participant dataframe contains 1 row per subject}
#'     \item{Checks intake dataframe contains 1 row per subject + visit combination}
#'     \item{Checks puberty dataframe contains 1 row per subject + session + respondent combination}
#'     \item{Checks all other dataframes contains 1 row per subject and session combination}
#'  }
#'  \item{Data types:}
#'  \itemize{
#'     \item{Checks that intake data (pre and post-weights) are numerical}
#'     \item{Checks LOC data: }
#'   }
#'  \item{Data values:}
#'  \itemize{
#'     \item{Checks child ages at V1 between >8 and <10}
#'     \item{Checks intake consumption (g) <= amount served}
#'   }
#'  \item{Missing data:}
#'  \itemize{
#'     \item{}
#'   }
#' }
#'
#' @param phenotype_data a list of phenotype dataframes generated by proc_redcap()
#'
#' @examples
#'
#' \dontrun{
#'
#' # return data from proc_redcap()
#' redcap_data <- proc_redcap(visit_data_path, data_de_path, return = TRUE)
#' phenotype_data <- redcap_data$phenotype_data
#'
#' # run QC on phenotype_data in redcap_data
#' qc_redcap(phenotype_data)
#'
#' }
qc_redcap <- function(phenotype_data) {

  #### Set up/initial checks #####

  # check that phenotype_data exist and is a list of data.frames
  data_arg <- methods::hasArg(phenotype_data)

  if (isTRUE(data_arg)) {
    if (!is.list(phenotype_data)) {
      stop("phenotype_data must be a list of dataframes")
    }
  } else if (isFALSE(data_arg)) {
    stop("must specify phenotype_data arg")
  }

  #### Quality check: duplicate data #####

  for (df_name in names(phenotype_data)) {

    # extract dataframe
    df <- phenotype_data[[df_name]]

    # check participants dataframe for duplicate subs
    if (df_name == "participants") {

      # extract rows with duplicate subs
      duplicate_rows <- df[duplicated(df[c("participant_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate subject rows in ", df_name, " :\n"))
        print(duplicate_rows)
      }

      # check intake dataframe for duplicate subs and visit
    } else if (df_name == "intake") {

      # extract rows with duplicate sub and visit combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "visit_protocol")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+visit_protocol rows in ", df_name, " :\n"))

      }

      # check puberty dataframe for duplicate sub, ses, and respondent
    } else if (df_name == "puberty") {

      # extract rows with duplicate sub visit, and respondent combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id", "respondent")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+session_id+respondent rows in ", df_name, " :\n"))
      }

      # check all other dataframes for duplicate sub + ses combinations
    } else {

      # extract rows with duplicate sub and ses combos
      duplicate_rows <- df[duplicated(df[c("participant_id", "session_id")]), ]

      if (nrow(duplicate_rows) > 0) {
        cat(paste0("Duplicate participant_id+session_id rows in ", df_name, " :\n"))
      }

    }

  }

  #### Quality check: data types #####

  #### Quality check: data values #####

  #### Quality check: missing data #####
}

