#' util_task_rrv: Clean and organize RRV data into BIDS rawdata
#'
#' This function formats and organizes RRV data from bids/sourcedata into bids/rawdata for a given subject
#' If subject has RRV text file, rrv_parse_text() will be called. If subject does not have text file but has game.csv, game.csv will processed to generate a dataframe like those generated by rrv_parse_text()
#'
#' @inheritParams util_copy_to_source
#' @inheritParams util_copy_to_source
#' @inheritParams util_task_foodview
#' @inheritParams util_copy_to_source
#'
#' @return statement of task completed
#'
#' @examples
#'
#' \dontrun{
#' # process task data for the Food View Task
#' rrv_data <- util_task_rrv(sub_str = 'sub-001', ses_str = 'ses-1', base_wd = base_wd)
#'
#' }
#' @importFrom utils read.table
#' @importFrom rlang .data
#' @export

util_task_rrv <- function(sub_str, ses_str, base_wd, overwrite = FALSE) {

  #### Set up/initial checks #####

  # check that audit_data exist and is a data.frame
  data_arg <- methods::hasArg(base_wd)

  if (isTRUE(data_arg)) {
    if (!is.character(base_wd)) {
      stop('base_wd must be entered as a string')
    } else if (!file.exists(base_wd)) {
      stop('base_wd entered, but file does not exist. Check base_wd string.')
    }
  } else if (isFALSE(data_arg)) {
    stop('base_wd must be entered as a string')
  }


  #### Clean Data #####
  # get file path
  source_beh_file <- file.path(base_wd, 'bids', 'sourcedata', sub_str, ses_str, 'beh', paste0(sub_str, '_', ses_str, '_task-rrv.tsv'))

  # load data, abort processing no file or >1 file matches pattern
  if (file.exists(source_beh_file)) {
    rrv_data <- read.table(source_beh_file, header = TRUE, sep = '\t', na.strings='n/a')
  } else {
    print(paste(sub_str, 'has no RRV tsv.'))
    return()
  }

  names(rrv_data)[names(rrv_data) == 'sub'] <- 'participant_id'

  rrv_data['session_id'] <- 'ses-1'

  # convert time column to seconds

  # ## create a logical vector to check for 'seconds' in the session_time column
  # is_seconds <- grepl('seconds', rrv_data[['ses_time']])
  #
  # ## process rows with time in seconds: remove 'seconds' string and make numeric
  # seconds_part <- as.numeric(gsub(' seconds', '', rrv_data[is_seconds, 'ses_time']))
  #
  # ## process rows with time in minutes: convert to seconds
  # minutes_part <- as.numeric(rrv_data[!is_seconds, 'ses_time']) * 60

  # ## replace values in session_time with processed values
  # rrv_data['ses_time'] <- NA # set to NA first, otherwise column will remain 'character' type
  # rrv_data[is_seconds, 'ses_time'] <- round(seconds_part, 3)
  # rrv_data[!is_seconds, 'ses_time'] <- round(minutes_part, 3)

  # reorder columns -- save as rrv_data
  rrv_data <- rrv_data[c('participant_id', 'session_id', names(rrv_data)[!grepl('id', names(rrv_data))])]

  #### Export Data  #####

  # make raw beh directory if it doesn't exist
  raw_beh_wd <- file.path(base_wd, 'bids', 'rawdata', sub_str, ses_str, 'beh')

  if (!dir.exists(raw_beh_wd)) {
    dir.create(raw_beh_wd, recursive = TRUE)
  }

  # export files if don't exist or overwrite = TRUE
  beh_outfile <- file.path(raw_beh_wd, paste0(sub_str, '_', ses_str, '_task-rrv_events.tsv'))

  if (!file.exists(beh_outfile) | isTRUE(overwrite)) {
    utils::write.table(rrv_data, beh_outfile, sep = '\t', quote = FALSE, row.names = FALSE, na = 'n/a')

    if (isTRUE(overwrite)){
      return('overwrote with new version')
    } else {
      return('complete')
    }
  } else {
    return('exists')
  }

}

