#' util_merge_questionnaires: merges data for questionnaires that were repeated at baseline and follow-up
#'
#' This function data for questionnaires that were repeated at baseline and follow-up. The following questionnaires will be merged across visits and returned individually in a list:
#'
#'
#' @param child_v1_data full set of child visit 1 data generated by util_redcap_child_v1
#' @param child_v4_data full set of child visit 5 data generated by util_redcap_child_v4
#' @param child_v5_data full set of child visit 5 data generated by util_redcap_child_v5
#' @param parent_v1_data full set of parent visit 1 data generated by util_redcap_parent_v1
#' @param parent_v2_data full set of parent visit 3 data generated by util_redcap_parent_v2
#' @param parent_v3_data full set of parent visit 3 data generated by util_redcap_parent_v3
#' @param parent_v4_data full set of parent visit 4 data generated by util_redcap_parent_v4
#' @param parent_v5_data full set of parent visit 5 data generated by util_redcap_parent_v5
#'
#' @return Will return a list of merged data files:
#'  \itemize{
#'    \item{stq_all}
#'    \item{kbas_all}
#'    \item{loc_all}
#'    \item{household_all}
#'    \item{cebq_all}
#'    \item{cbq_all}
#'    \item{cshq_all}
#'    \item{pstca_all}
#'    \item{audit_all}
#'    \item{pmum_all}
#'    \item{cfpq_all}
#'    \item{rank_all}
#'    \item{class_all}
#'    \item{puberty_all}
#'    \item{updates_all}
#'  }
#'
#' @examples
#'
#' # process data
#' merged_qs_list <- util_merge_questionnaires(child_v1_data, child_v4_data, child_v5_data, parent_v1_data, parent_v2_data, parent_v3_data, parent_v4_data, parent_v5_data)
#'
#' @seealso [proc_redcap()], [util_redcap_child_v1()], [util_redcap_child_v4()], [util_redcap_child_v5()], [util_redcap_parent_v1()], [util_redcap_parent_v2()], [util_redcap_parent_v3()], [util_redcap_parent_v4()], [util_redcap_parent_v5()]
#'
#' @export
#'


util_merge_questionnaires <- function(child_v1_data, child_v4_data, child_v5_data, parent_v1_data, parent_v2_data, parent_v3_data, parent_v4_data, parent_v5_data) {

  stq_all <- rbind.data.frame(child_v1_data$stq_data$data, child_v5_data$stq_data$data)

  kbas_all <- rbind.data.frame(child_v1_data$kbas_data$data, child_v5_data$kbas_data$data)

  loc_all <- rbind(data.table::setDT(child_v4_data$loc_data$data), data.table::setDT(child_v5_data$loc_data$data), fill = TRUE)
  loc_all <- as.data.frame(loc_all)

  household_all <- rbind(data.table::setDT(parent_v1_data$household_data$data), data.table::setDT(parent_v5_data$household_data$data), fill = TRUE)
  household_all <- as.data.frame(household_all)

  cebq_all <- rbind.data.frame(parent_v1_data$cebq_data$data$bids_phenotype, parent_v5_data$cebq_data$data$bids_phenotype)

  cbq_all <- rbind.data.frame(parent_v2_data$cbq_data$data$bids_phenotype, parent_v5_data$cbq_data$data$bids_phenotype)

  cshq_all <- rbind.data.frame(parent_v2_data$cshq_data$data$bids_phenotype, parent_v5_data$cshq_data$data$bids_phenotype)

  # not scored/in bids_phenotype yet
  pstca_all <- rbind.data.frame(parent_v3_data$pstca_data$data, parent_v5_data$ptsca_data$data)

  audit_all <- rbind.data.frame(parent_v4_data$audit_data$data$bids_phenotype, parent_v5_data$audit_data$data$bids_phenotype)

  # not scored/in bids_phenotype yet
  pmum_all <- rbind.data.frame(parent_v4_data$pmum_data$data, parent_v5_data$pmum_data$data)

  cfpq_all <- rbind.data.frame(parent_v4_data$cfpq_data$data$bids_phenotype, parent_v5_data$cfpq_data$data$bids_phenotype)

  # not scored/in bids_phenotype yet - will it be?
  rank_all <- rbind.data.frame(parent_v1_data$rank_data$data, parent_v5_data$rank_data$data)

  # not scored/in bids_phenotype yet - will it be?
  class_all <- rbind.data.frame(parent_v3_data$class_data$data, parent_v5_data$class_data$data)

  # stack child (V5) and parent (V1, V5) puberty data
  puberty_all <- rbind(data.table::setDT(parent_v1_data$puberty_data$data$bids_phenotype), data.table::setDT(parent_v5_data$puberty_data$data$bids_phenotype), data.table::setDT(child_v5_data$puberty_data$data$bids_phenotype), fill = TRUE)
  puberty_all <- as.data.frame(puberty_all)

  updates_all <- rbind(data.table::setDT(parent_v2_data$visit2_updates$data), data.table::setDT(parent_v3_data$visit3_updates$data), data.table::setDT(parent_v4_data$visit4_updates$data), data.table::setDT(parent_v5_data$visit5_updates$data), fill = TRUE)
  updates_all <- as.data.frame(updates_all)

  # return data
  return(list(stq_all = stq_all,
              kbas_all = kbas_all,
              loc_all = loc_all,
              household_all = household_all,
              cebq_all = cebq_all,
              cbq_all = cbq_all,
              cshq_all = cshq_all,
              pstca_all = pstca_all,
              audit_all = audit_all,
              pmum_all = pmum_all,
              cfpq_all = cfpq_all,
              rank_all = rank_all,
              class_all = class_all,
              puberty_all = puberty_all,
              updates_all = updates_all))

}
