#' util_merged_intake: merges and formats all data related to meals and EAH
#'
#' This function merges all data related to meals and EAH and calculates intake values
#'
#'
#' @param child_v1_data full set of child visit 1 data generated by util_redcap_child_v1
#' @param child_v3_data full set of child visit 3 data generated by util_redcap_child_v3
#' @param child_v4_data full set of child visit 4 data generated by util_redcap_child_v4
#' @param child_v5_data full set of child visit 5 data generated by util_redcap_child_v5
#' @param proc_de_data full set of processed double-entry data generated by util_redcap_de
#' @examples
#'
#' # process data
#' merged_intake <- util_merged_intake(child_v1_data, child_v3_data, child_v4_data, child_v5_data)
#'
#' @seealso [proc_redcap()], [util_redcap_child_v1()], [util_redcap_child_v3()], [util_redcap_child_v4()], [util_redcap_child_v5()], [util_redcap_de()], [util_calc_intake()]
#'
#' @export
#'


util_merged_intake <- function(child_v1_data, child_v3_data, child_v4_data, child_v5_data, proc_de_data) {

  liking_all <- rbind.data.frame(child_v1_data$liking_data$data, child_v5_data$liking_data$data)

  wanting_all <- rbind.data.frame(child_v3_data$eah_wanting$data, child_v4_data$eah_wanting$data, child_v5_data$eah_wanting$data)

  fullness_all <- rbind(data.table::setDT(child_v1_data$freddy_data$data), data.table::setDT(child_v4_data$freddy_data$data), data.table::setDT(child_v5_data$freddy_data$data), fill=TRUE)
  fullness_all <- as.data.frame(fullness_all)

  food_paradigm_info_all <- rbind(data.table::setDT(child_v1_data$food_paradigm_info$data), data.table::setDT(child_v3_data$food_paradigm_info$data), data.table::setDT(child_v4_data$food_paradigm_info$data), data.table::setDT(child_v5_data$food_paradigm_info$data), fill = TRUE)
  food_paradigm_info_all <- as.data.frame(food_paradigm_info_all)

  # non-double entered
  # intake_all <- rbind(data.table::setDT(child_v1_data$intake_data$data), data.table::setDT(child_v3_data$intake_data$data), data.table::setDT(child_v4_data$intake_data$data), data.table::setDT(child_v5_data$intake_data$data), fill = TRUE)
  # intake_all <- as.data.frame(intake_all)
  #
  # intake_all <- util_calc_intake(intake_all)

  intake_all <- rbind(data.table::setDT(proc_de_data$intake_v1$data), data.table::setDT(proc_de_data$intake_v3$data), data.table::setDT(proc_de_data$intake_v4$data), data.table::setDT(proc_de_data$intake_v5$data), fill = TRUE)
  intake_all <- as.data.frame(intake_all)

  intake_all <- util_calc_intake(intake_all)

  merged_intake <- merge(food_paradigm_info_all, liking_all[!grepl('visit_protocol|visit_date', names(liking_all))], by=c('participant_id', 'session_id'), all = TRUE)
  merged_intake <- merge(merged_intake, wanting_all[!grepl('session_id|visit_date|advertisement_condition', names(wanting_all))], by=c('participant_id', 'visit_protocol'), all = TRUE)
  merged_intake <- merge(merged_intake, fullness_all[!grepl('session_id|visit_date|advertisement_condition', names(fullness_all))], by=c('participant_id', 'visit_protocol'), all = TRUE)
  merged_intake <- merge(merged_intake, intake_all[!grepl('session_id|visit_date|advertisement_condition', names(intake_all))], by=c('participant_id', 'visit_protocol'), all = TRUE)

  # re-order
  merged_intake <- merged_intake[c('participant_id', 'session_id', names(merged_intake)[!grepl('_id', names(merged_intake))])]

  # return data
  return(merged_intake)

}
